# Generated by Django 5.2.14 on 2026-05-23 11:10
#
# T-OS-001 — Marco 3 schema inicial (OS + AtividadeDaOS).
# Cria sequence global os_numero_seq_global (ADR-0056 + INV-OS-NUM-001)
# + tabelas ordens_servico/atividade_da_os.
#
# RLS policies + triggers anti-mutation + unique partial index (INV-OS-CONC-001)
# = T-OS-002+T-OS-003 (migrations-irmas na sequencia).
# rls-policy: external 0002_rls_policies_e_triggers

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0023_us_cli_003_pii_regularizacao'),
        ('equipamentos', '0027_seed_authz_versionar'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        # Sequence global pra numeração OS (ADR-0056 + INV-OS-NUM-001).
        # Buracos por rollback aceitos; UNIQUE(tenant, numero_os) garante unicidade por tenant.
        migrations.RunSQL(
            sql='CREATE SEQUENCE IF NOT EXISTS os_numero_seq_global;',
            reverse_sql='DROP SEQUENCE IF EXISTS os_numero_seq_global;',
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_os', models.BigIntegerField(help_text='Gerado por sequence global os_numero_seq_global no DEFAULT da migration (ADR-0056 + INV-OS-NUM-001). UNIQUE(tenant, numero_os). Buracos por rollback aceitos.')),
                ('cliente_referencia_hash', models.CharField(help_text='HMAC-SHA256 do cliente_id original — preserva audit pos-anonimizacao (ADR-0032).', max_length=64)),
                ('cliente_key_id', models.CharField(help_text='KMS key id usada no hash.', max_length=40)),
                ('orcamento_origem_id', models.UUIDField(blank=True, help_text='FK orcamento (db_constraint=False ate modulo Orcamentos chegar). NULL em OS avulsa (US-OS-015).', null=True)),
                ('sucessao_societaria_id', models.UUIDField(blank=True, help_text='FK SucessaoSocietaria (a criar GATE-OS-SUCESSAO-EVIDENCIA Wave A) em reabertura cross-cliente M&A (INV-OS-SUC-001).', null=True)),
                ('estado', models.CharField(choices=[('rascunho', 'Rascunho'), ('agendada', 'Agendada'), ('em_execucao', 'Em execucao'), ('concluida', 'Concluida'), ('cancelada', 'Cancelada'), ('faturada', 'Faturada'), ('paga', 'Paga')], default='rascunho', help_text='Estado COMPUTADO a partir das atividades (INV-OS-ATIV-001).', max_length=20)),
                ('tipo_predominante', models.CharField(blank=True, default='', help_text='Calculado em transicao para CONCLUIDA. Regra de empate: calibracao sempre vence.', max_length=30)),
                ('nao_conformidade_global', models.BooleanField(default=False, help_text='True quando >=1 AtividadeDaOS em NAO_CONFORME.')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, help_text='Snapshot inicial vindo do orcamento.', max_digits=14)),
                ('valor_total_atualizado', models.DecimalField(decimal_places=2, default=0, help_text='Recalculado a cada cancelamento parcial — ADR-0042 + INV-OS-FAT-001.', max_digits=14)),
                ('analise_critica_id', models.UUIDField(blank=True, help_text='cl. 7.1 ISO 17025 (P-OS-R2 + INV-OS-ANAL-001). NOT NULL em produtiva; nullable agora p/ migration; T-OS-046 cria validacao 412 OrcamentoSemAnaliseCritica.', null=True)),
                ('analise_critica_snapshot_hash', models.CharField(blank=True, default='', help_text='Snapshot probatorio do momento da abertura (INV-DOC-CANON-001).', max_length=64)),
                ('regra_decisao_acordada', models.CharField(blank=True, default='', help_text='Snapshot cl. 7.1.3 (ADR-0024). Overridable por cliente em M4 calibracao.', max_length=20)),
                ('equipamento_recebimento_id', models.UUIDField(blank=True, help_text='FK EquipamentoRecebimento (db_constraint=False — modulo equipamentos M2 traz). cl. 7.5 ISO 17025 (P-OS-R4). NULL em OS de campo; NOT NULL em OS de bancada (T-OS-047).', null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('criada_por_user_id', models.UUIDField(blank=True, help_text='Quem abriu (auditoria + cl. 7.1 capacidade_tecnica_confirmada_por em US-OS-015).', null=True)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, help_text='Pode ficar NULL pos-anonimizacao (ADR-0032 + INV-OS-ANON-001).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='clientes.cliente')),
                ('equipamento', models.ForeignKey(help_text='INV-OS-EQP-001: equipamento BAIXADO/DESCARTADO bloqueia abertura.', on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='equipamentos.equipamento')),
                ('os_origem', models.ForeignKey(blank=True, help_text='FK reabertura (US-OS-006).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reaberturas', to='ordens_servico.os')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Ordem de Servico',
                'verbose_name_plural': 'Ordens de Servico',
                'db_table': 'ordens_servico',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='AtividadeDaOS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('calibracao', 'Calibracao'), ('manutencao_corretiva', 'Manutencao corretiva'), ('manutencao_preventiva', 'Manutencao preventiva'), ('instalacao', 'Instalacao'), ('verificacao_inmetro', 'Verificacao INMETRO'), ('vistoria', 'Vistoria')], help_text='Enum fechado de 6 valores (INV-OS-ATIV-003).', max_length=30)),
                ('sequencia', models.IntegerField(help_text='Ordem de execucao; gate sequencia ADR-0041.')),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('agendada', 'Agendada'), ('em_execucao', 'Em execucao'), ('concluida', 'Concluida'), ('nao_conforme', 'Nao conforme'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('tecnico_executor_id', models.UUIDField(blank=True, help_text='FK user.id (db_constraint=False). Executor designado eh unico autorizado (INV-OS-ATIV-005).', null=True)),
                ('agendada_para', models.DateTimeField(blank=True, null=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('valor_unitario_snapshot', models.DecimalField(decimal_places=2, default=0, help_text='Snapshot do preco no momento (US-OS-015 + INV-CLI-PRICE-001).', max_digits=14)),
                ('link_modulo_tecnico_id', models.UUIDField(blank=True, help_text='FK reversa para Calibracao/Manutencao (db_constraint=False). Preenchido em <=janela_tenant via INV-OS-CAL-LINK-001 (default 72h alerta / 15 dias NC RBC perfil A).', null=True)),
                ('geo_lat', models.FloatField(blank=True, help_text='Opt-in (RAT-07 + INV-OS-GEO-001). TTL 5a pos-conclusao via job os-geo-truncamento (P-OS-A2).', null=True)),
                ('geo_long', models.FloatField(blank=True, null=True)),
                ('geo_municipio_hash', models.CharField(blank=True, default='', help_text='Hash do municipio (preservado mesmo pos-TTL — INV-OS-GEO-001 item d).', max_length=64)),
                ('tenant', models.ForeignKey(help_text='Herda da OS (INV-OS-ATIV-002 cross-tenant proibido).', on_delete=django.db.models.deletion.PROTECT, related_name='atividades_os', to='tenant.tenant')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades', to='ordens_servico.os')),
            ],
            options={
                'verbose_name': 'Atividade da OS',
                'verbose_name_plural': 'Atividades da OS',
                'db_table': 'atividade_da_os',
                'ordering': ['os', 'sequencia'],
            },
        ),
        migrations.AddIndex(
            model_name='os',
            index=models.Index(fields=['tenant', 'estado', 'criada_em'], name='os_tenant_est_cri_idx'),
        ),
        migrations.AddIndex(
            model_name='os',
            index=models.Index(fields=['tenant', 'cliente'], name='os_tenant_cliente_idx'),
        ),
        migrations.AddIndex(
            model_name='os',
            index=models.Index(fields=['tenant', 'equipamento'], name='os_tenant_equip_idx'),
        ),
        migrations.AddConstraint(
            model_name='os',
            constraint=models.UniqueConstraint(fields=('tenant', 'numero_os'), name='uq_ordens_servico_numero_por_tenant'),
        ),
        migrations.AddIndex(
            model_name='atividadedaos',
            index=models.Index(fields=['tenant', 'os', 'sequencia'], name='atv_tenant_os_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='atividadedaos',
            index=models.Index(fields=['tenant', 'tecnico_executor_id', 'estado'], name='atv_tenant_tec_est_idx'),
        ),
        # Aplica DEFAULT nextval('os_numero_seq_global') ao campo numero_os
        # (Django ORM nao suporta DEFAULT vindo de sequence — ADR-0056 + INV-OS-NUM-001).
        migrations.RunSQL(
            sql=(
                "ALTER TABLE ordens_servico ALTER COLUMN numero_os "
                "SET DEFAULT nextval('os_numero_seq_global');"
            ),
            reverse_sql='ALTER TABLE ordens_servico ALTER COLUMN numero_os DROP DEFAULT;',
        ),
    ]
