# Generated by Django 5.2.14 on 2026-05-23 13:14
#
# T-OS-010 - TipoAtividadeConfig (6 tipos fechados + flags).
#
# Cobertura:
# - INV-OS-ATIV-003: enum fechado de 6 valores (calibracao,
#   manutencao_corretiva, manutencao_preventiva, instalacao,
#   verificacao_inmetro, vistoria).
# - Padrao C soft-delete (ADR-0031): coluna `deletado_em` + UNIQUE
#   parcial WHERE deletado_em IS NULL.
# - RLS pattern v2 (ADR-0002 §6).
# - Flags governam validacoes downstream:
#   * tipo_bloqueia_concorrencia -> entra na unique partial index
#     INV-OS-CONC-001 (T-OS-003 separado).
#   * requer_competencia_rt -> predicate rt_competencia_cobre obrigatorio.
#   * executa_em_campo -> equipamento_recebimento_id opcional vs obrigatorio.
#
# Seed: data migration 0004 (proximo passo) cria 6 entradas por tenant
# com defaults RBC perfil A (72h alerta / 15 dias NC para calibracao).

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models

RLS_FORWARD = """
ALTER TABLE tipo_atividade_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE tipo_atividade_config FORCE ROW LEVEL SECURITY;

CREATE POLICY tipo_atividade_config_tenant_isolation_select ON tipo_atividade_config
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY tipo_atividade_config_tenant_isolation_update ON tipo_atividade_config
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY tipo_atividade_config_tenant_isolation_delete ON tipo_atividade_config
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY tipo_atividade_config_tenant_isolation_insert ON tipo_atividade_config
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);
"""

RLS_REVERSE = """
DROP POLICY IF EXISTS tipo_atividade_config_tenant_isolation_insert ON tipo_atividade_config;
DROP POLICY IF EXISTS tipo_atividade_config_tenant_isolation_delete ON tipo_atividade_config;
DROP POLICY IF EXISTS tipo_atividade_config_tenant_isolation_update ON tipo_atividade_config;
DROP POLICY IF EXISTS tipo_atividade_config_tenant_isolation_select ON tipo_atividade_config;
ALTER TABLE tipo_atividade_config DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0002_rls_policies'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAtividadeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('calibracao', 'Calibracao'), ('manutencao_corretiva', 'Manutencao corretiva'), ('manutencao_preventiva', 'Manutencao preventiva'), ('instalacao', 'Instalacao'), ('verificacao_inmetro', 'Verificacao INMETRO'), ('vistoria', 'Vistoria')], max_length=30)),
                ('requer_competencia_rt', models.BooleanField(default=False, help_text='Predicate rt_competencia_cobre exigido (INV-CAL-RT-001 + cl. 6.2).')),
                ('tipo_bloqueia_concorrencia', models.BooleanField(default=False, help_text='Matriz ADR-0041. True = entra na unique partial index INV-OS-CONC-001.')),
                ('executa_em_campo', models.BooleanField(default=False, help_text='True = tecnico vai ao cliente; False = bancada laboratorio.')),
                ('prazo_link_calibracao_alerta_h', models.IntegerField(blank=True, help_text='Watchdog os-calibracao-link: horas ate alerta P2. NULL se tipo != calibracao.', null=True)),
                ('prazo_link_calibracao_nc_dias_uteis', models.IntegerField(blank=True, help_text='Watchdog os-calibracao-link: dias uteis ate NC automatica.', null=True)),
                ('deletado_em', models.DateTimeField(blank=True, help_text='Padrao C soft-delete (ADR-0031). UNIQUE parcial WHERE deletado_em IS NULL.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Cada tenant tem 6 entradas. Seed inicial via data migration.', on_delete=django.db.models.deletion.PROTECT, related_name='tipos_atividade_config', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Configuracao de tipo de atividade',
                'verbose_name_plural': 'Configuracoes de tipos de atividade',
                'db_table': 'tipo_atividade_config',
                'ordering': ['tenant', 'tipo'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deletado_em__isnull', True)), fields=('tenant', 'tipo'), name='uq_tipo_atividade_config_por_tenant_ativos')],
            },
        ),
        migrations.RunSQL(sql=RLS_FORWARD, reverse_sql=RLS_REVERSE),
    ]
