# Generated by Django 5.2.14 on 2026-05-23 13:33
#
# T-OS-003 - concorrencia atividades no mesmo equipamento (INV-OS-CONC-001).
#
# Cobertura:
# - INV-OS-CONC-001 + ADR-0041: 2 atividades simultaneas EM_EXECUCAO no
#   mesmo equipamento, ambas com tipo_bloqueia_concorrencia=true, viola
#   uma unique partial index. INSERT/UPDATE de transicao estoura unique
#   violation -> 412 deterministico.
#
# Desnormalizacao:
# - `atividade_da_os.equipamento_id_desnormalizado` copia OS.equipamento_id
# - `atividade_da_os.tipo_bloqueia_concorrencia` copia TipoAtividadeConfig
#   .tipo_bloqueia_concorrencia (lookup por tipo + tenant_id).
# - Ambas copiadas via trigger BEFORE INSERT (atomico).
# - Trigger BEFORE UPDATE bloqueia mutacao desses campos pos-INSERT.
#
# Unique partial index:
# - CREATE UNIQUE INDEX idx_atividade_em_execucao_por_equip
#     ON atividade_da_os (tenant_id, equipamento_id_desnormalizado)
#     WHERE estado='em_execucao' AND tipo_bloqueia_concorrencia=true;
#
# tests-coverage: tests/regressao/test_inv_os_conc_001_concorrencia_matriz.py (T-OS-115)

from __future__ import annotations

from django.db import migrations, models

TRIGGER_FORWARD = """
-- Funcao denormaliza equipamento_id + tipo_bloqueia_concorrencia
-- no INSERT em atividade_da_os.
CREATE OR REPLACE FUNCTION atividade_da_os_concorrencia_denormalize_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
DECLARE
    v_equip uuid;
    v_bloq boolean;
BEGIN
    -- Copia equipamento_id da OS pai.
    SELECT equipamento_id INTO v_equip
    FROM ordens_servico WHERE id = NEW.os_id;
    NEW.equipamento_id_desnormalizado := v_equip;

    -- Lookup do tipo_bloqueia_concorrencia em TipoAtividadeConfig.
    -- Default conservador: TRUE (bloquear) se config ausente, pra ser
    -- defensivo. Em uso real, o seed T-OS-010 garante existencia.
    SELECT tipo_bloqueia_concorrencia INTO v_bloq
    FROM tipo_atividade_config
    WHERE tenant_id = NEW.tenant_id
      AND tipo = NEW.tipo
      AND deletado_em IS NULL
    LIMIT 1;
    NEW.tipo_bloqueia_concorrencia := COALESCE(v_bloq, TRUE);

    RETURN NEW;
END;
$body$;

CREATE TRIGGER atividade_da_os_concorrencia_denormalize_trg
    BEFORE INSERT ON atividade_da_os
    FOR EACH ROW
    EXECUTE FUNCTION atividade_da_os_concorrencia_denormalize_check();

-- Funcao bloqueia mutacao dos 2 campos desnormalizados pos-INSERT
-- (sao snapshot imutavel; OS.equipamento_id e config nao mudam pra atividade).
CREATE OR REPLACE FUNCTION atividade_da_os_concorrencia_imutavel_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF OLD.equipamento_id_desnormalizado IS DISTINCT FROM NEW.equipamento_id_desnormalizado THEN
        RAISE EXCEPTION
            'INV-OS-CONC-001: equipamento_id_desnormalizado imutavel pos-INSERT';
    END IF;
    IF OLD.tipo_bloqueia_concorrencia IS DISTINCT FROM NEW.tipo_bloqueia_concorrencia THEN
        RAISE EXCEPTION
            'INV-OS-CONC-001: tipo_bloqueia_concorrencia imutavel pos-INSERT';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER atividade_da_os_concorrencia_imutavel_trg
    BEFORE UPDATE ON atividade_da_os
    FOR EACH ROW
    EXECUTE FUNCTION atividade_da_os_concorrencia_imutavel_check();

-- Unique partial index INV-OS-CONC-001 (ADR-0041).
-- Garante que so 1 atividade EM_EXECUCAO bloqueante por (tenant, equipamento).
CREATE UNIQUE INDEX idx_atividade_em_execucao_por_equip
    ON atividade_da_os (tenant_id, equipamento_id_desnormalizado)
    WHERE estado = 'em_execucao' AND tipo_bloqueia_concorrencia = TRUE;
"""


TRIGGER_REVERSE = """
DROP INDEX IF EXISTS idx_atividade_em_execucao_por_equip;
DROP TRIGGER IF EXISTS atividade_da_os_concorrencia_imutavel_trg ON atividade_da_os;
DROP FUNCTION IF EXISTS atividade_da_os_concorrencia_imutavel_check();
DROP TRIGGER IF EXISTS atividade_da_os_concorrencia_denormalize_trg ON atividade_da_os;
DROP FUNCTION IF EXISTS atividade_da_os_concorrencia_denormalize_check();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0004_seed_tipo_atividade_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadedaos',
            name='equipamento_id_desnormalizado',
            field=models.UUIDField(blank=True, help_text='Desnormalizado de OS.equipamento_id via trigger BEFORE INSERT. Existe em atividade_da_os porque o unique partial index INV-OS-CONC-001 exige todas as colunas na mesma tabela.', null=True),
        ),
        migrations.AddField(
            model_name='atividadedaos',
            name='tipo_bloqueia_concorrencia',
            field=models.BooleanField(default=False, help_text='Desnormalizado de TipoAtividadeConfig.tipo_bloqueia_concorrencia via trigger BEFORE INSERT. True = entra no unique partial index idx_atividade_em_execucao_por_equip (INV-OS-CONC-001 + ADR-0041).'),
        ),
        migrations.RunSQL(sql=TRIGGER_FORWARD, reverse_sql=TRIGGER_REVERSE),
    ]
