# Generated by Django 5.2.14 on 2026-05-23 13:54
#
# T-OS-005 - ConsentimentoBiometriaTouch (LGPD art. 11 II "a").
#
# Cobertura:
# - INV-OS-CONSBIO-001 (P-OS-A1): FK 1:1 obrigatoria de AceiteAtividade
#   quando captura biometria touch. Sem o consentimento pre-gravado,
#   AceiteAtividade nao pode ser criada -> 412 ConsentimentoBiometriaAusente.
# - Padrao B (ADR-0031): trigger PG bloqueia UPDATE/DELETE pos-INSERT
#   (audit-immutability). Entidade probatoria — 25a WORM equivalente.
# - RLS pattern v2 (ADR-0002 §6) — 4 policies.
# - INV-DOC-CANON-001: texto_hash imutavel garante prova determinística
#   em 25 anos (texto canonico mora em docs/conformidade/comum/termos/).
#
# REQUER OAB: texto canonico do consentimento — GATE-OS-CONSBIO-TEXTO-OAB
# (pre-1o tenant externo). Esta migration cria SOMENTE a tabela; o termo
# em si vira em arquivo .md OAB-validado.
#
# tests-coverage: tests/regressao/test_inv_os_consbio_001_consentimento.py (T-OS-118)

from __future__ import annotations

import uuid

import django.db.models.deletion
from django.db import migrations, models

RLS_FORWARD = """
ALTER TABLE consentimento_biometria_touch ENABLE ROW LEVEL SECURITY;
ALTER TABLE consentimento_biometria_touch FORCE ROW LEVEL SECURITY;

CREATE POLICY consentimento_biometria_touch_tenant_isolation_select ON consentimento_biometria_touch
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY consentimento_biometria_touch_tenant_isolation_update ON consentimento_biometria_touch
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY consentimento_biometria_touch_tenant_isolation_delete ON consentimento_biometria_touch
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY consentimento_biometria_touch_tenant_isolation_insert ON consentimento_biometria_touch
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- =============================================================
-- Padrao B (ADR-0031): bloqueia UPDATE e DELETE pos-INSERT.
-- Audit-immutability — entidade probatoria.
-- =============================================================
CREATE OR REPLACE FUNCTION consentimento_biometria_touch_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'INV-OS-CONSBIO-001: ConsentimentoBiometriaTouch eh imutavel pos-INSERT (Padrao B ADR-0031)';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-OS-CONSBIO-001: ConsentimentoBiometriaTouch nao pode ser deletado (audit imutavel)';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER consentimento_biometria_touch_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON consentimento_biometria_touch
    FOR EACH ROW
    EXECUTE FUNCTION consentimento_biometria_touch_anti_mutation_check();
"""

RLS_REVERSE = """
DROP TRIGGER IF EXISTS consentimento_biometria_touch_anti_mutation_trg ON consentimento_biometria_touch;
DROP FUNCTION IF EXISTS consentimento_biometria_touch_anti_mutation_check();
DROP POLICY IF EXISTS consentimento_biometria_touch_tenant_isolation_insert ON consentimento_biometria_touch;
DROP POLICY IF EXISTS consentimento_biometria_touch_tenant_isolation_delete ON consentimento_biometria_touch;
DROP POLICY IF EXISTS consentimento_biometria_touch_tenant_isolation_update ON consentimento_biometria_touch;
DROP POLICY IF EXISTS consentimento_biometria_touch_tenant_isolation_select ON consentimento_biometria_touch;
ALTER TABLE consentimento_biometria_touch DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0005_concorrencia_desnormalizacao_e_index'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimentoBiometriaTouch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_referencia_hash', models.CharField(help_text='HMAC-SHA256 do cliente_id original (ADR-0032).', max_length=64)),
                ('cliente_key_id', models.CharField(max_length=40)),
                ('texto_canonico_id', models.UUIDField(help_text='FK -> docs/conformidade/comum/termos/consentimento-biometria-touch.md (db_constraint=False ate modulo termos existir). REQUER OAB.')),
                ('texto_hash', models.CharField(help_text='SHA-256 do texto canonico exibido (INV-DOC-CANON-001).', max_length=64)),
                ('versao_politica', models.CharField(help_text='Semver da Politica de Privacidade vigente no momento.', max_length=20)),
                ('concedido_em', models.DateTimeField(help_text="Timestamp do toque no botao 'concordo e assino' (SEPARADO de 'concluir').")),
                ('tela_renderizada_evidencia', models.BinaryField(blank=True, help_text='Screenshot opcional da tela exibida (RIPD pode exigir).', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(help_text='Atividade que vai gerar o AceiteAtividade (FK reversa 1:1).', on_delete=django.db.models.deletion.PROTECT, related_name='consentimentos_biometria', to='ordens_servico.atividadedaos')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimentos_biometria_touch', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Consentimento de biometria touch',
                'verbose_name_plural': 'Consentimentos de biometria touch',
                'db_table': 'consentimento_biometria_touch',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', 'atividade'], name='cbio_tenant_atv_idx')],
                'constraints': [models.UniqueConstraint(fields=('atividade',), name='uq_consentimento_biometria_por_atividade')],
            },
        ),
        migrations.RunSQL(sql=RLS_FORWARD, reverse_sql=RLS_REVERSE),
    ]
