# Generated by Django 5.2.14 on 2026-05-23 14:34
#
# T-OS-004 - AceiteAtividade (registro probatorio do aceite do cliente).
#
# Cobertura:
# - INV-OS-ACEITE-BIO-001: biometria_payload_encrypted cifrado com
#   BIOMETRIA_KEY_<tenant_id> dedicada por tenant (LGPD art. 5o II + 11).
# - INV-OS-CONSBIO-001 (trigger PG): se biometria_payload_encrypted IS
#   NOT NULL, consentimento_id deve ser NOT NULL. Sem consentimento ->
#   RAISE EXCEPTION (paralelo: 412 ConsentimentoBiometriaAusente no
#   handler de aplicacao).
# - INV-DOC-CANON-001 (ADR-0029): texto_canonicalizado em UTF-8 + LF +
#   NFC + marcadores. texto_hash garante prova determinística 25a.
# - Padrao B (ADR-0031): trigger PG bloqueia UPDATE/DELETE pos-INSERT.
# - RLS pattern v2 (ADR-0002 §6) — 4 policies.
#
# tests-coverage: tests/regressao/test_inv_os_aceite_bio_001_kms.py +
# test_inv_doc_canon_001_aceite.py (T-OS-120)

from __future__ import annotations

import uuid

import django.db.models.deletion
from django.db import migrations, models

RLS_FORWARD = """
ALTER TABLE aceite_atividade ENABLE ROW LEVEL SECURITY;
ALTER TABLE aceite_atividade FORCE ROW LEVEL SECURITY;

CREATE POLICY aceite_atividade_tenant_isolation_select ON aceite_atividade
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY aceite_atividade_tenant_isolation_update ON aceite_atividade
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY aceite_atividade_tenant_isolation_delete ON aceite_atividade
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY aceite_atividade_tenant_isolation_insert ON aceite_atividade
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- =============================================================
-- INV-OS-CONSBIO-001 — biometria exige consentimento previo (FK 1:1).
-- BEFORE INSERT: se biometria_payload_encrypted nao nulo,
-- consentimento_id deve estar populado E ser do mesmo tenant +
-- mesma atividade do aceite.
-- =============================================================
CREATE OR REPLACE FUNCTION aceite_atividade_consbio_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
DECLARE
    v_cb_tenant uuid;
    v_cb_atv uuid;
BEGIN
    IF NEW.biometria_payload_encrypted IS NOT NULL AND NEW.consentimento_id IS NULL THEN
        RAISE EXCEPTION
            'INV-OS-CONSBIO-001: AceiteAtividade com biometria exige consentimento_id NOT NULL (LGPD art. 11 II a)';
    END IF;

    -- Se consentimento foi referenciado, valida tenant + atividade match
    -- (defensivo contra cross-tenant via FK polimorfica).
    IF NEW.consentimento_id IS NOT NULL THEN
        SELECT tenant_id, atividade_id INTO v_cb_tenant, v_cb_atv
        FROM consentimento_biometria_touch
        WHERE id = NEW.consentimento_id;

        IF v_cb_tenant IS NULL THEN
            RAISE EXCEPTION
                'INV-OS-CONSBIO-001: consentimento_id % nao existe',
                NEW.consentimento_id;
        END IF;

        IF v_cb_tenant <> NEW.tenant_id THEN
            RAISE EXCEPTION
                'INV-OS-CONSBIO-001: consentimento de tenant diferente (esperado %, achado %)',
                NEW.tenant_id, v_cb_tenant;
        END IF;

        IF v_cb_atv <> NEW.atividade_id THEN
            RAISE EXCEPTION
                'INV-OS-CONSBIO-001: consentimento de atividade diferente (esperado %, achado %)',
                NEW.atividade_id, v_cb_atv;
        END IF;
    END IF;

    RETURN NEW;
END;
$body$;

CREATE TRIGGER aceite_atividade_consbio_trg
    BEFORE INSERT ON aceite_atividade
    FOR EACH ROW
    EXECUTE FUNCTION aceite_atividade_consbio_check();

-- =============================================================
-- Padrao B (ADR-0031) — anti-mutation pos-INSERT.
-- =============================================================
CREATE OR REPLACE FUNCTION aceite_atividade_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'AceiteAtividade eh imutavel pos-INSERT (Padrao B ADR-0031)';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'AceiteAtividade nao pode ser deletado (audit imutavel)';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER aceite_atividade_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON aceite_atividade
    FOR EACH ROW
    EXECUTE FUNCTION aceite_atividade_anti_mutation_check();
"""

RLS_REVERSE = """
DROP TRIGGER IF EXISTS aceite_atividade_anti_mutation_trg ON aceite_atividade;
DROP FUNCTION IF EXISTS aceite_atividade_anti_mutation_check();
DROP TRIGGER IF EXISTS aceite_atividade_consbio_trg ON aceite_atividade;
DROP FUNCTION IF EXISTS aceite_atividade_consbio_check();
DROP POLICY IF EXISTS aceite_atividade_tenant_isolation_insert ON aceite_atividade;
DROP POLICY IF EXISTS aceite_atividade_tenant_isolation_delete ON aceite_atividade;
DROP POLICY IF EXISTS aceite_atividade_tenant_isolation_update ON aceite_atividade;
DROP POLICY IF EXISTS aceite_atividade_tenant_isolation_select ON aceite_atividade;
ALTER TABLE aceite_atividade DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0006_consentimentobiometriatouch'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AceiteAtividade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_referencia_hash', models.CharField(help_text='HMAC-SHA256 do cliente_id original (ADR-0032).', max_length=64)),
                ('cliente_key_id', models.CharField(max_length=40)),
                ('texto_canonicalizado', models.TextField(help_text='UTF-8 sem BOM + LF + NFC + marcadores <<<CORPO INICIO/FIM>>> (ADR-0029).')),
                ('texto_hash', models.CharField(help_text='SHA-256 do texto pos-canonicalizacao (INV-DOC-CANON-001).', max_length=64)),
                ('biometria_payload_encrypted', models.BinaryField(blank=True, help_text='Cifrado com BIOMETRIA_KEY_<tenant_id> (INV-OS-ACEITE-BIO-001). NULL em aceites SEM biometria (caso de dispensa US-OS-013).', null=True)),
                ('biometria_key_id', models.CharField(blank=True, default='', help_text='Id da chave KMS dedicada por tenant. Vazio se sem biometria.', max_length=40)),
                ('coletado_em', models.DateTimeField(help_text='Timestamp servidor da coleta.')),
                ('geo_lat', models.FloatField(blank=True, help_text='Opt-in (RAT-07 + INV-OS-GEO-001). Mesma precisao limitada da atividade.', null=True)),
                ('geo_long', models.FloatField(blank=True, null=True)),
                ('geo_municipio_hash', models.CharField(blank=True, default='', max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceites', to='ordens_servico.atividadedaos')),
                ('consentimento', models.ForeignKey(blank=True, help_text='FK 1:1 NOT NULL quando ha biometria touch (INV-OS-CONSBIO-001). NULL apenas em aceites SEM biometria (cenario US-OS-013 dispensa).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aceite', to='ordens_servico.consentimentobiometriatouch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceites_atividade', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Aceite de atividade',
                'verbose_name_plural': 'Aceites de atividade',
                'db_table': 'aceite_atividade',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', 'atividade'], name='aceite_tenant_atv_idx')],
                'constraints': [models.UniqueConstraint(fields=('atividade',), name='uq_aceite_por_atividade')],
            },
        ),
        migrations.RunSQL(sql=RLS_FORWARD, reverse_sql=RLS_REVERSE),
    ]
