# Generated by Django 5.2.14 on 2026-05-23 14:47
#
# T-OS-006 - EvidenciaFotoAtividade (P-OS-T5 + INV-OS-SYNC-001 reescrito).
#
# Cobertura:
# - Padrao B append-only (ADR-0031): INSERT permitido em qualquer estado
#   da atividade (inclusive terminal — gera EventoDeOS tipo
#   'foto_evidencia_tardia' em T-OS-008 EventoDeOS futuramente).
# - UPDATE: somente revogado_em mutavel (LGPD art. 18 — face cliente).
#   Qualquer outro campo modificado -> RAISE EXCEPTION.
# - DELETE: bloqueado (audit imutavel 25a B2 WORM).
# - INV-OS-SYNC-001: client_event_id UNIQUE por tenant — sync mobile
#   ADR-0027 (anti-duplicacao em retry).
# - RLS pattern v2 (ADR-0002 §6) — 4 policies.
#
# tests-coverage: tests/regressao/test_inv_os_sync_001_fotos.py (T-OS-120)

from __future__ import annotations

import uuid

import django.db.models.deletion
from django.db import migrations, models

RLS_FORWARD = """
ALTER TABLE evidencia_foto_atividade ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidencia_foto_atividade FORCE ROW LEVEL SECURITY;

CREATE POLICY evidencia_foto_atividade_tenant_isolation_select ON evidencia_foto_atividade
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY evidencia_foto_atividade_tenant_isolation_update ON evidencia_foto_atividade
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY evidencia_foto_atividade_tenant_isolation_delete ON evidencia_foto_atividade
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY evidencia_foto_atividade_tenant_isolation_insert ON evidencia_foto_atividade
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- =============================================================
-- Padrao B append-only — UPDATE so permite setar revogado_em.
-- DELETE bloqueado completamente.
-- =============================================================
CREATE OR REPLACE FUNCTION evidencia_foto_atividade_append_only_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        -- Permite somente setar revogado_em (LGPD art. 18 — face cliente).
        IF OLD.id IS DISTINCT FROM NEW.id
           OR OLD.tenant_id IS DISTINCT FROM NEW.tenant_id
           OR OLD.atividade_id IS DISTINCT FROM NEW.atividade_id
           OR OLD.tipo IS DISTINCT FROM NEW.tipo
           OR OLD.b2_uri IS DISTINCT FROM NEW.b2_uri
           OR OLD.foto_sha256 IS DISTINCT FROM NEW.foto_sha256
           OR OLD.client_event_id IS DISTINCT FROM NEW.client_event_id
           OR OLD.client_event_created_at IS DISTINCT FROM NEW.client_event_created_at
           OR OLD.enviada_em IS DISTINCT FROM NEW.enviada_em
           OR OLD.tecnico_executor_id IS DISTINCT FROM NEW.tecnico_executor_id
           OR OLD.geo_lat IS DISTINCT FROM NEW.geo_lat
           OR OLD.geo_long IS DISTINCT FROM NEW.geo_long
           OR OLD.geo_municipio_hash IS DISTINCT FROM NEW.geo_municipio_hash
           OR OLD.criado_em IS DISTINCT FROM NEW.criado_em THEN
            RAISE EXCEPTION
                'EvidenciaFotoAtividade eh append-only: so revogado_em pode mudar (LGPD art. 18 face cliente)';
        END IF;
        -- Tambem proibe re-revogar (revogado_em deve ir de NULL -> data, nunca data -> NULL ou data -> outra_data).
        IF OLD.revogado_em IS NOT NULL AND OLD.revogado_em IS DISTINCT FROM NEW.revogado_em THEN
            RAISE EXCEPTION
                'EvidenciaFotoAtividade.revogado_em jah setado: nao pode ser alterado novamente';
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'EvidenciaFotoAtividade nao pode ser deletada (audit imutavel B2 WORM 25a)';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER evidencia_foto_atividade_append_only_trg
    BEFORE UPDATE OR DELETE ON evidencia_foto_atividade
    FOR EACH ROW
    EXECUTE FUNCTION evidencia_foto_atividade_append_only_check();
"""

RLS_REVERSE = """
DROP TRIGGER IF EXISTS evidencia_foto_atividade_append_only_trg ON evidencia_foto_atividade;
DROP FUNCTION IF EXISTS evidencia_foto_atividade_append_only_check();
DROP POLICY IF EXISTS evidencia_foto_atividade_tenant_isolation_insert ON evidencia_foto_atividade;
DROP POLICY IF EXISTS evidencia_foto_atividade_tenant_isolation_delete ON evidencia_foto_atividade;
DROP POLICY IF EXISTS evidencia_foto_atividade_tenant_isolation_update ON evidencia_foto_atividade;
DROP POLICY IF EXISTS evidencia_foto_atividade_tenant_isolation_select ON evidencia_foto_atividade;
ALTER TABLE evidencia_foto_atividade DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0007_aceiteatividade'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaFotoAtividade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('checklist_item', 'Item de checklist'), ('conclusao', 'Conclusao'), ('nc', 'Nao conformidade'), ('no_show', 'No-show'), ('recusa_aceite', 'Recusa de aceite')], max_length=30)),
                ('b2_uri', models.TextField(help_text='URL Backblaze B2 WORM (foto armazenada imutavel 25a).')),
                ('foto_sha256', models.CharField(help_text='SHA-256 da foto pos EXIF strip (cadeia probatoria).', max_length=64)),
                ('client_event_id', models.UUIDField(help_text='UUID gerado pelo client (sync mobile ADR-0027).')),
                ('client_event_created_at', models.DateTimeField(help_text='Timestamp do client no momento da captura (offline-first).')),
                ('enviada_em', models.DateTimeField(help_text='Timestamp do servidor no upload.')),
                ('tecnico_executor_id', models.UUIDField(blank=True, help_text='FK user.id (db_constraint=False); pode ser diferente do tecnico_executor_id atual da atividade.', null=True)),
                ('geo_lat', models.FloatField(blank=True, null=True)),
                ('geo_long', models.FloatField(blank=True, null=True)),
                ('geo_municipio_hash', models.CharField(blank=True, default='', max_length=64)),
                ('revogado_em', models.DateTimeField(blank=True, help_text='LGPD art. 18 (face cliente). Unico campo mutavel via UPDATE.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_foto', to='ordens_servico.atividadedaos')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_foto', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Evidencia foto de atividade',
                'verbose_name_plural': 'Evidencias foto de atividade',
                'db_table': 'evidencia_foto_atividade',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', 'atividade'], name='evid_tenant_atv_idx'), models.Index(fields=['tenant', 'atividade', 'tipo'], name='evid_tenant_atv_tip_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'client_event_id'), name='uq_evidencia_foto_client_event_por_tenant')],
            },
        ),
        migrations.RunSQL(sql=RLS_FORWARD, reverse_sql=RLS_REVERSE),
    ]
