# Generated by Django 5.2.14 on 2026-05-23 15:13
#
# T-OS-008 - EventoDeOS (timeline append-only sanitizada).
#
# Cobertura:
# - INV-OS-AUD-001: payload sanitizado NA ESCRITA — proibe cliente_id/
#   tecnico_id/ator_id cru; so *_hash HMAC. Helper unico
#   audit/event_helpers.publicar_evento garante sanitizacao.
# - INV-AUDIT-IMMUT-002 (RAT-08): trigger PG bloqueia UPDATE/DELETE
#   pos-INSERT. Estende padrao da audit principal pra evento_*.
# - INV-DOC-CANON-001: payload_hash garante prova determinística do
#   estado original 25a.
# - INV-OS-TXT-001: payload_data jamais carrega texto livre cru — apenas
#   hashes ou enums.
# - ADR-0033 bus envelope v10: correlation_id propagado entre modulos.
# - RLS pattern v2 (ADR-0002 §6) — 4 policies.
#
# tests-coverage: tests/regressao/test_inv_os_aud_001.py (T-OS-NNN)

from __future__ import annotations

import uuid

import django.db.models.deletion
from django.db import migrations, models

RLS_FORWARD = """
ALTER TABLE evento_de_os ENABLE ROW LEVEL SECURITY;
ALTER TABLE evento_de_os FORCE ROW LEVEL SECURITY;

CREATE POLICY evento_de_os_tenant_isolation_select ON evento_de_os
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY evento_de_os_tenant_isolation_update ON evento_de_os
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY evento_de_os_tenant_isolation_delete ON evento_de_os
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY evento_de_os_tenant_isolation_insert ON evento_de_os
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- =============================================================
-- INV-AUDIT-IMMUT-002 — append-only (UPDATE e DELETE proibidos).
-- =============================================================
CREATE OR REPLACE FUNCTION evento_de_os_append_only_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'INV-AUDIT-IMMUT-002: EventoDeOS eh append-only (UPDATE proibido)';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-AUDIT-IMMUT-002: EventoDeOS eh append-only (DELETE proibido)';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER evento_de_os_append_only_trg
    BEFORE UPDATE OR DELETE ON evento_de_os
    FOR EACH ROW
    EXECUTE FUNCTION evento_de_os_append_only_check();
"""

RLS_REVERSE = """
DROP TRIGGER IF EXISTS evento_de_os_append_only_trg ON evento_de_os;
DROP FUNCTION IF EXISTS evento_de_os_append_only_check();
DROP POLICY IF EXISTS evento_de_os_tenant_isolation_insert ON evento_de_os;
DROP POLICY IF EXISTS evento_de_os_tenant_isolation_delete ON evento_de_os;
DROP POLICY IF EXISTS evento_de_os_tenant_isolation_update ON evento_de_os;
DROP POLICY IF EXISTS evento_de_os_tenant_isolation_select ON evento_de_os;
ALTER TABLE evento_de_os DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0008_evidenciafotoatividade'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDeOS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('atividade_adicionada', 'Atividade adicionada'), ('atividade_iniciada', 'Atividade iniciada'), ('atividade_concluida', 'Atividade concluida'), ('atividade_nao_conforme', 'Atividade nao conforme'), ('atividade_nc_resolvida', 'Atividade NC resolvida'), ('atividade_cancelada', 'Atividade cancelada'), ('atividade_reagendada', 'Atividade reagendada'), ('atividade_tecnico_transferido', 'Tecnico transferido'), ('no_show_cliente', 'No-show cliente'), ('dispensa_aceite_emitida', 'Dispensa de aceite emitida'), ('foto_evidencia_tardia', 'Foto evidencia em atividade terminal'), ('watchdog_estendido', 'Watchdog cal-link estendido'), ('os_aberta', 'OS aberta'), ('os_atribuida', 'OS atribuida'), ('os_concluida', 'OS concluida'), ('os_cancelada', 'OS cancelada'), ('os_reaberta', 'OS reaberta'), ('os_escopo_alterado', 'OS escopo alterado (ADR-0042)'), ('sla_breach', 'SLA quebrado')], max_length=40)),
                ('payload_hash', models.CharField(help_text='SHA-256 do payload sanitizado (INV-OS-AUD-001 + INV-DOC-CANON-001).', max_length=64)),
                ('payload_data', models.JSONField(default=dict, help_text='Payload sanitizado — NAO contem PII cru. Hashes em vez de cliente_id/tecnico_id/ator_id. Helper unico audit/event_helpers.publicar_evento garante sanitizacao.')),
                ('correlation_id', models.UUIDField(help_text='Correlation ID propagado entre modulos (ADR-0033 bus envelope v10).')),
                ('actor_user_id', models.UUIDField(blank=True, help_text='User que disparou (NULL em jobs automaticos: watchdog, retry).', null=True)),
                ('occurred_at', models.DateTimeField(help_text='Timestamp do evento de negocio (pode preceder criado_em em sync mobile).')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atividade', models.ForeignKey(blank=True, help_text='Opcional; preenchido quando o evento eh de atividade especifica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='ordens_servico.atividadedaos')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='ordens_servico.os')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_os', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Evento de OS',
                'verbose_name_plural': 'Eventos de OS',
                'db_table': 'evento_de_os',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['tenant', 'os', 'occurred_at'], name='evt_os_tenant_os_occ_idx'), models.Index(fields=['tenant', 'atividade', 'occurred_at'], name='evt_os_tenant_atv_idx'), models.Index(fields=['tenant', 'tipo', 'occurred_at'], name='evt_os_tenant_tip_idx'), models.Index(fields=['tenant', 'correlation_id'], name='evt_os_tenant_corr_idx')],
            },
        ),
        migrations.RunSQL(sql=RLS_FORWARD, reverse_sql=RLS_REVERSE),
    ]
