# Generated by Django 5.2.14 on 2026-05-23 15:43
#
# T-OS-007 - DispensaAceiteAtividade (US-OS-013 + P-OS-A4 advogado).
#
# Cobertura:
# - P-OS-A4 (CDC art. 39): precedente_tipo obrigatorio + a3_assinatura_hash
#   + termo_pdf_sha256. Dispensa unilateral sem precedente eh inversao
#   indevida do onus probatorio em juizo (STJ pequenas causas).
# - INV-DOC-CANON-001 (ADR-0029): termo_pdf_sha256 garante prova
#   determinística 25a (B2 WORM).
# - INV-OS-TXT-001: motivo_hash em vez de texto cru.
# - Padrao B (ADR-0031): trigger PG bloqueia UPDATE/DELETE pos-INSERT.
# - RLS pattern v2 (ADR-0002 §6) — 4 policies.
#
# REQUER OAB: modelo do TermoDispensaAceite em docs/conformidade/comum/termos/
# (GATE-OS-CONSBIO-TEXTO-OAB pre-1o tenant externo).
#
# tests-coverage: tests/integracao/test_us_os_013_dispensar_aceite.py (T-OS-133)

from __future__ import annotations

import uuid

import django.db.models.deletion
from django.db import migrations, models

RLS_FORWARD = """
ALTER TABLE dispensa_aceite_atividade ENABLE ROW LEVEL SECURITY;
ALTER TABLE dispensa_aceite_atividade FORCE ROW LEVEL SECURITY;

CREATE POLICY dispensa_aceite_atividade_tenant_isolation_select ON dispensa_aceite_atividade
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY dispensa_aceite_atividade_tenant_isolation_update ON dispensa_aceite_atividade
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY dispensa_aceite_atividade_tenant_isolation_delete ON dispensa_aceite_atividade
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY dispensa_aceite_atividade_tenant_isolation_insert ON dispensa_aceite_atividade
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- =============================================================
-- Padrao B (ADR-0031) — anti-mutation pos-INSERT.
-- =============================================================
CREATE OR REPLACE FUNCTION dispensa_aceite_atividade_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'DispensaAceiteAtividade eh imutavel pos-INSERT (Padrao B ADR-0031)';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'DispensaAceiteAtividade nao pode ser deletada (audit imutavel)';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER dispensa_aceite_atividade_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON dispensa_aceite_atividade
    FOR EACH ROW
    EXECUTE FUNCTION dispensa_aceite_atividade_anti_mutation_check();
"""

RLS_REVERSE = """
DROP TRIGGER IF EXISTS dispensa_aceite_atividade_anti_mutation_trg ON dispensa_aceite_atividade;
DROP FUNCTION IF EXISTS dispensa_aceite_atividade_anti_mutation_check();
DROP POLICY IF EXISTS dispensa_aceite_atividade_tenant_isolation_insert ON dispensa_aceite_atividade;
DROP POLICY IF EXISTS dispensa_aceite_atividade_tenant_isolation_delete ON dispensa_aceite_atividade;
DROP POLICY IF EXISTS dispensa_aceite_atividade_tenant_isolation_update ON dispensa_aceite_atividade;
DROP POLICY IF EXISTS dispensa_aceite_atividade_tenant_isolation_select ON dispensa_aceite_atividade;
ALTER TABLE dispensa_aceite_atividade DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0009_evento_de_os'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensaAceiteAtividade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo_hash', models.CharField(help_text='SHA-256 do motivo livre (anti-PII INV-OS-TXT-001). Texto cru NUNCA persistido — soh em B2 WORM se necessario.', max_length=64)),
                ('autorizado_por_gerente_id', models.UUIDField(help_text='FK user.id (db_constraint=False). Papel gerente verificado em camada de aplicacao.')),
                ('a3_assinatura_hash', models.CharField(help_text='SHA-256 da assinatura A3 do gerente (P-OS-A4 — nao basta sessao autenticada).', max_length=64)),
                ('a3_certificado_emissor_hash', models.CharField(help_text='Hash do AC emissor (ICP-Brasil); valida cadeia OCSP/CRL em camada de aplicacao.', max_length=64)),
                ('a3_assinada_em', models.DateTimeField(help_text='Timestamp da assinatura A3.')),
                ('termo_pdf_b2_uri', models.TextField(help_text='URL Backblaze B2 WORM do TermoDispensaAceite (REQUER OAB modelo).')),
                ('termo_pdf_sha256', models.CharField(help_text='SHA-256 do PDF (INV-DOC-CANON-001 — prova determinística 25a).', max_length=64)),
                ('precedente_tipo', models.CharField(choices=[('no_show', 'No-show do cliente'), ('recusa_explicita', 'Recusa explicita gravada'), ('impossibilidade_tecnica', 'Impossibilidade tecnica de captura')], help_text='Obrigatorio (P-OS-A4). Sem precedente -> 412 DispensaSemPrecedente.', max_length=30)),
                ('precedente_evento_id', models.UUIDField(blank=True, help_text='FK -> EventoDeOS (precedente=no_show) ou EvidenciaFotoAtividade (precedente=recusa_explicita). db_constraint=False — FK polimorfica.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensas_aceite', to='ordens_servico.atividadedaos')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensas_aceite', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Dispensa de aceite de atividade',
                'verbose_name_plural': 'Dispensas de aceite de atividade',
                'db_table': 'dispensa_aceite_atividade',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', 'atividade'], name='disp_tenant_atv_idx')],
                'constraints': [models.UniqueConstraint(fields=('atividade',), name='uq_dispensa_aceite_por_atividade')],
            },
        ),
        migrations.RunSQL(sql=RLS_FORWARD, reverse_sql=RLS_REVERSE),
    ]
