# Generated by Django 5.2.14 on 2026-05-23 15:55
#
# T-OS-009 - ChecklistDaAtividade (Padrao A — estado por item).
#
# Cobertura:
# - US-OS-004 (concluir atividade): checklist 100% preenchido ou
#   nao_aplicavel obrigatorio para `concluirAtividade` (AC-OS-004-1).
# - Padrao A (ADR-0031): mutavel via service layer; estados:
#   pendente -> preenchido | nao_aplicavel.
# - INV-OS-TXT-001: descricao_hash + valor_hash em vez de texto cru.
# - INV-DOC-CANON-001: descricao_hash canonicalizado (prova 25a).
# - RLS pattern v2 (ADR-0002 §6) — 4 policies.
#
# tests-coverage: tests/integracao/test_us_os_004_concluir_atividade.py (T-OS-124)

from __future__ import annotations

import uuid

import django.db.models.deletion
from django.db import migrations, models

RLS_FORWARD = """
ALTER TABLE checklist_da_atividade ENABLE ROW LEVEL SECURITY;
ALTER TABLE checklist_da_atividade FORCE ROW LEVEL SECURITY;

CREATE POLICY checklist_da_atividade_tenant_isolation_select ON checklist_da_atividade
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY checklist_da_atividade_tenant_isolation_update ON checklist_da_atividade
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY checklist_da_atividade_tenant_isolation_delete ON checklist_da_atividade
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY checklist_da_atividade_tenant_isolation_insert ON checklist_da_atividade
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);
"""

RLS_REVERSE = """
DROP POLICY IF EXISTS checklist_da_atividade_tenant_isolation_insert ON checklist_da_atividade;
DROP POLICY IF EXISTS checklist_da_atividade_tenant_isolation_delete ON checklist_da_atividade;
DROP POLICY IF EXISTS checklist_da_atividade_tenant_isolation_update ON checklist_da_atividade;
DROP POLICY IF EXISTS checklist_da_atividade_tenant_isolation_select ON checklist_da_atividade;
ALTER TABLE checklist_da_atividade DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0010_dispensa_aceite_atividade'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistDaAtividade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordem', models.IntegerField(help_text='Sequencia de apresentacao do item.')),
                ('descricao_hash', models.CharField(help_text='SHA-256 da descricao canonicalizada (INV-DOC-CANON-001).', max_length=64)),
                ('descricao_publica', models.CharField(help_text="Descricao curta sem PII (rotulo do item — ex: 'Leitura padrao 1 kg').", max_length=200)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('preenchido', 'Preenchido'), ('nao_aplicavel', 'Nao aplicavel')], default='pendente', max_length=20)),
                ('valor_hash', models.CharField(blank=True, default='', help_text='Hash do valor cru preenchido (anti-PII). Vazio em pendente/nao_aplicavel.', max_length=64)),
                ('valor_publico', models.CharField(blank=True, default='', help_text='Valor exibivel sem PII (numero, OK/NOK, enum).', max_length=200)),
                ('preenchido_por_user_id', models.UUIDField(blank=True, null=True)),
                ('preenchido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_itens', to='ordens_servico.atividadedaos')),
                ('evidencia_foto', models.ForeignKey(blank=True, help_text='Opcional — foto vinculada ao item (ex: foto de display).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_itens', to='ordens_servico.evidenciafotoatividade')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_atividades', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Item de checklist de atividade',
                'verbose_name_plural': 'Itens de checklist de atividade',
                'db_table': 'checklist_da_atividade',
                'ordering': ['atividade', 'ordem'],
                'indexes': [models.Index(fields=['tenant', 'atividade', 'estado'], name='chk_tenant_atv_est_idx')],
                'constraints': [models.UniqueConstraint(fields=('atividade', 'ordem'), name='uq_checklist_atividade_ordem')],
            },
        ),
        migrations.RunSQL(sql=RLS_FORWARD, reverse_sql=RLS_REVERSE),
    ]
