# Generated by Django 5.2.14 on 2026-05-23 16:05
#
# T-OS-011 - NaoConformidadeAtividade + SLAContrato (fecha Fase 1 P4).
#
# Cobertura:
# - US-OS-005 + cl. 8.7 ISO 17025 (P-OS-R5): NaoConformidadeAtividade
#   com 5 campos CAPA. resolverNC exige todos 4 nao-NULL -> 412
#   CAPAIncompleto (AC-OS-005-5).
# - INV-012 + INV-OS-ATIV-001 + INV-OS-TXT-001: razao_*_hash anti-PII.
# - US-OS-007 saga 4 + INV-INT-013: SLAContrato com vigencia. Cancelar
#   OS com SLA prioridade alta|emergencia dispara consumer sla-breach.
# - ADR-0030 JanelaVigencia: vigencia_inicio/vigencia_fim/revogado_em.
# - GATE-RBC-CAPA-1: registro_capa_id FK pra qualidade Wave B.
# - Padrao B em NaoConformidadeAtividade — trigger anti-mutation com
#   excecoes controladas para campos CAPA (transicao pendente->resolvida).
# - Padrao A em SLAContrato — mutavel; revogado_em soft-delete.
# - RLS pattern v2 (ADR-0002 §6) — 4 policies em ambas.

from __future__ import annotations

import uuid

import django.db.models.deletion
from django.db import migrations, models

RLS_FORWARD = """
-- =============================================================
-- nao_conformidade_atividade — RLS pattern v2
-- =============================================================
ALTER TABLE nao_conformidade_atividade ENABLE ROW LEVEL SECURITY;
ALTER TABLE nao_conformidade_atividade FORCE ROW LEVEL SECURITY;

CREATE POLICY nao_conformidade_atividade_tenant_isolation_select ON nao_conformidade_atividade
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY nao_conformidade_atividade_tenant_isolation_update ON nao_conformidade_atividade
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY nao_conformidade_atividade_tenant_isolation_delete ON nao_conformidade_atividade
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY nao_conformidade_atividade_tenant_isolation_insert ON nao_conformidade_atividade
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- Padrao B com excecoes para CAPA: bloqueia mutacao dos campos
-- imutaveis pos-INSERT (razao_*_hash, marcada_em/por). Permite UPDATE
-- nos campos CAPA (causa_raiz/acao_corretiva/eficacia/registro_capa)
-- e revogado_em (transicoes legitimas).
CREATE OR REPLACE FUNCTION nao_conformidade_atividade_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF OLD.id IS DISTINCT FROM NEW.id
           OR OLD.tenant_id IS DISTINCT FROM NEW.tenant_id
           OR OLD.atividade_id IS DISTINCT FROM NEW.atividade_id
           OR OLD.razao_nao_conformidade_hash IS DISTINCT FROM NEW.razao_nao_conformidade_hash
           OR OLD.marcada_em IS DISTINCT FROM NEW.marcada_em
           OR OLD.marcada_por_user_id IS DISTINCT FROM NEW.marcada_por_user_id
           OR OLD.criado_em IS DISTINCT FROM NEW.criado_em THEN
            RAISE EXCEPTION
                'NaoConformidadeAtividade: campos imutaveis pos-INSERT (so CAPA + revogado_em editavel)';
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'NaoConformidadeAtividade nao pode ser deletada (audit imutavel)';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER nao_conformidade_atividade_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON nao_conformidade_atividade
    FOR EACH ROW
    EXECUTE FUNCTION nao_conformidade_atividade_anti_mutation_check();

-- =============================================================
-- sla_contrato — RLS pattern v2
-- =============================================================
ALTER TABLE sla_contrato ENABLE ROW LEVEL SECURITY;
ALTER TABLE sla_contrato FORCE ROW LEVEL SECURITY;

CREATE POLICY sla_contrato_tenant_isolation_select ON sla_contrato
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY sla_contrato_tenant_isolation_update ON sla_contrato
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY sla_contrato_tenant_isolation_delete ON sla_contrato
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY sla_contrato_tenant_isolation_insert ON sla_contrato
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);
"""

RLS_REVERSE = """
DROP POLICY IF EXISTS sla_contrato_tenant_isolation_insert ON sla_contrato;
DROP POLICY IF EXISTS sla_contrato_tenant_isolation_delete ON sla_contrato;
DROP POLICY IF EXISTS sla_contrato_tenant_isolation_update ON sla_contrato;
DROP POLICY IF EXISTS sla_contrato_tenant_isolation_select ON sla_contrato;
ALTER TABLE sla_contrato DISABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS nao_conformidade_atividade_anti_mutation_trg ON nao_conformidade_atividade;
DROP FUNCTION IF EXISTS nao_conformidade_atividade_anti_mutation_check();
DROP POLICY IF EXISTS nao_conformidade_atividade_tenant_isolation_insert ON nao_conformidade_atividade;
DROP POLICY IF EXISTS nao_conformidade_atividade_tenant_isolation_delete ON nao_conformidade_atividade;
DROP POLICY IF EXISTS nao_conformidade_atividade_tenant_isolation_update ON nao_conformidade_atividade;
DROP POLICY IF EXISTS nao_conformidade_atividade_tenant_isolation_select ON nao_conformidade_atividade;
ALTER TABLE nao_conformidade_atividade DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_us_cli_003_pii_regularizacao'),
        ('ordens_servico', '0011_checklist_da_atividade'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaoConformidadeAtividade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razao_nao_conformidade_hash', models.CharField(help_text='SHA-256 do texto cru (anti-PII INV-OS-TXT-001).', max_length=64)),
                ('marcada_em', models.DateTimeField(help_text='Timestamp da marcacao NC.')),
                ('marcada_por_user_id', models.UUIDField(help_text='FK user.id (db_constraint=False). Metrologista ou RT.')),
                ('registro_capa_id', models.UUIDField(blank=True, help_text='FK -> qualidade.registro_capa (Wave B; db_constraint=False). Preenchido por consumer reverso quando modulo qualidade nascer (GATE-RBC-CAPA-1).', null=True)),
                ('causa_raiz_hash', models.CharField(blank=True, default='', help_text='Anti-PII (INV-OS-TXT-001). Obrigatorio em resolverNC.', max_length=64)),
                ('acao_corretiva_descricao_hash', models.CharField(blank=True, default='', help_text='Anti-PII. Obrigatorio em resolverNC.', max_length=64)),
                ('eficacia_verificada_em', models.DateTimeField(blank=True, null=True)),
                ('eficacia_verificada_por_user_id', models.UUIDField(blank=True, help_text='Geralmente RT ou gerente_qualidade — predicate ABAC valida.', null=True)),
                ('revogado_em', models.DateTimeField(blank=True, help_text='Raro — apenas se NC foi marcada por engano (audit preserva).', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nao_conformidades', to='ordens_servico.atividadedaos')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nao_conformidades', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Nao conformidade de atividade',
                'verbose_name_plural': 'Nao conformidades de atividade',
                'db_table': 'nao_conformidade_atividade',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', 'atividade'], name='nc_tenant_atv_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revogado_em__isnull', True)), fields=('atividade',), name='uq_nc_ativa_por_atividade')],
            },
        ),
        migrations.CreateModel(
            name='SLAContrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('emergencia', 'Emergencia')], default='normal', max_length=20)),
                ('prazo_atendimento_horas', models.IntegerField(help_text='Horas a partir de OSAberta para atribuirTecnico (US-OS-002b).')),
                ('prazo_conclusao_horas', models.IntegerField(help_text='Horas a partir de OSAberta para concluirAtividade da ultima atividade.')),
                ('descricao_publica', models.CharField(blank=True, default='', help_text='Descricao sem PII (categoria de servico).', max_length=200)),
                ('vigencia_inicio', models.DateTimeField(help_text='ADR-0030 JanelaVigencia.')),
                ('vigencia_fim', models.DateTimeField(blank=True, help_text='NULL = aberta.', null=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_revogacao_hash', models.CharField(blank=True, default='', max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='sla_contratos', to='clientes.cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sla_contratos', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Contrato de SLA',
                'verbose_name_plural': 'Contratos de SLA',
                'db_table': 'sla_contrato',
                'ordering': ['-vigencia_inicio'],
                'indexes': [models.Index(fields=['tenant', 'cliente', 'vigencia_inicio'], name='sla_tenant_cli_vig_idx')],
            },
        ),
        migrations.RunSQL(sql=RLS_FORWARD, reverse_sql=RLS_REVERSE),
    ]
