# Generated by Django 5.2.14 on 2026-05-25 + edicao manual para acrescentar
# index parcial e documentar ADR-0063 Opcao A lazy.
#
# T-CAL-024 — Migration cross-marco M3->M4 calibracao (ADR-0063 Opcao A lazy).
#
# Adiciona AtividadeDaOS.grandeza VARCHAR(50) com default='' (backfill
# automatico Django). Predicate rt_competencia_cobre(grandeza) consulta
# este campo a partir do Marco 4 quando Calibracao plugar valor real.
#
# Em Marco 3 dogfooding: grandeza='' (fail-open documentado AC-OS-002-3,
# AC-OS-002b-4, AC-OS-003-6, AC-OS-012-2 — ver ADR-0063).
#
# # rls-policy: external 0002 (tenant.atividade_da_os RLS ja existe)
# # tests-coverage: tests/regressao/test_adr_0063_lazy.py (T-CAL-152)

from django.db import migrations, models


INDEX_PARCIAL_FORWARD = """
-- ADR-0063 Opcao A lazy: index parcial para queries do predicate
-- rt_competencia_cobre quando grandeza preenchida (M4 calibracao pluga).
CREATE INDEX IF NOT EXISTS atv_tenant_grandeza_partial_idx
    ON atividade_da_os (tenant_id, grandeza)
    WHERE grandeza <> '';
"""

INDEX_PARCIAL_REVERSE = """
DROP INDEX IF EXISTS atv_tenant_grandeza_partial_idx;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0013_seed_authz_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadedaos',
            name='grandeza',
            field=models.CharField(
                blank=True,
                default='',
                help_text=(
                    "ADR-0063 Opcao A lazy - preenchido quando tipo='calibracao' "
                    "por Calibracao.grandeza (Marco 4). Vazio em Marco 3 (fail-open). "
                    "Predicate rt_competencia_cobre(grandeza) consulta este campo."
                ),
                max_length=50,
            ),
        ),
        migrations.RunSQL(sql=INDEX_PARCIAL_FORWARD, reverse_sql=INDEX_PARCIAL_REVERSE),
    ]
