# Generated by Django 5.2.14 on 2026-05-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0014_atividade_grandeza_adr0063'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadedaos',
            name='grandeza',
            field=models.CharField(blank=True, default='', help_text="ADR-0063 Opcao A lazy — preenchido quando tipo='calibracao' por Calibracao.grandeza (Marco 4). Vazio em Marco 3 (fail-open). Predicate rt_competencia_cobre(grandeza) consulta este campo.", max_length=50),
        ),
    ]
