# Generated by Django 5.2.14 on 2026-05-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0016_perfil_no_evento_san_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventodeos',
            name='perfil_no_evento',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text="Snapshot perfil regulatorio tenant no momento do evento OS. Trigger BEFORE INSERT popula via current_setting('app.perfil_tenant'). ADR-0067.", max_length=1, null=True),
        ),
    ]
