# Generated by Django 5.2.14 on 2026-05-30 04:23
#
# T-ECMC-010/011 — M6 metrologia/escopos-cmc schema inicial (2 tabelas).
# escopo_cmc (raiz, colunas tipadas D-ECMC-2) + escopo_extraido (staging PDF).
# UNIQUE(tenant,grandeza,faixa_min,faixa_max,procedimento_id,versao)
# nulls_distinct=False (INV-ECMC-001). Indice parcial cobertura (TL-C-11).
#
# RLS policies = migration-irma 0002_rls_policies (ADR-0002 §6 pattern v2).
# Triggers WORM Padrao B (block-delete + campo metrologico CONFIRMADO imutavel)
# = 0003_triggers_worm. GRANT app_user = 0004_grants_app_user.
# metrology-affecting: escopo_cmc cmc_valor/faixa tocam decisao RBC (ADR-0025 cl. 7.11)
#
# rls-policy: external 0002_rls_policies

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0010_remove_tenantperfilhistorico_tph_tenant_recente_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscopoCMC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grandeza', models.CharField(choices=[('massa', 'massa'), ('temperatura', 'temperatura'), ('pressao', 'pressao'), ('volume', 'volume'), ('comprimento', 'comprimento'), ('eletrica_tensao', 'eletrica_tensao'), ('eletrica_corrente', 'eletrica_corrente'), ('eletrica_resistencia', 'eletrica_resistencia'), ('eletrica_potencia', 'eletrica_potencia'), ('tempo', 'tempo'), ('frequencia', 'frequencia'), ('forca', 'forca'), ('torque', 'torque'), ('dureza', 'dureza'), ('umidade', 'umidade'), ('ph', 'ph'), ('densidade', 'densidade'), ('vazao', 'vazao'), ('velocidade', 'velocidade'), ('aceleracao', 'aceleracao')], help_text='Grandeza RBC (VO Grandeza). Índice de filtro de cobertura.', max_length=30)),
                ('faixa_min', models.DecimalField(decimal_places=12, help_text='Limite inferior da faixa (Decimal).', max_digits=30)),
                ('faixa_max', models.DecimalField(decimal_places=12, help_text='Limite superior (faixa_min < faixa_max).', max_digits=30)),
                ('unidade', models.CharField(help_text='Unidade SI/RBC da faixa (whitelist VO).', max_length=20)),
                ('cmc_forma', models.CharField(choices=[('ABSOLUTA', 'ABSOLUTA'), ('RELATIVA_LINEAR', 'RELATIVA_LINEAR')], default='ABSOLUTA', help_text='ABSOLUTA (cmc_valor constante) ou RELATIVA_LINEAR (a + b·|X|) — ADR-0074.', max_length=20)),
                ('cmc_valor', models.DecimalField(decimal_places=12, help_text='ABSOLUTA: a própria CMC; RELATIVA_LINEAR: termo fixo `a`. Menor incerteza declarada.', max_digits=30)),
                ('cmc_unidade', models.CharField(help_text='Unidade da CMC.', max_length=20)),
                ('cmc_coef_relativo', models.DecimalField(blank=True, decimal_places=12, help_text='Coeficiente `b` (só RELATIVA_LINEAR — CMC = a + b·|X|).', max_digits=30, null=True)),
                ('rbc_acreditado', models.BooleanField(default=False, help_text="True só perfil A (INV-ECMC-002 — `tenant_perfil_e(['A'])`; forçado False p/ B/C/D server-side, anti-fraude FAIL L6). Bloqueio 412 RBC-only.")),
                ('numero_escopo_cgcre', models.CharField(blank=True, default='', help_text='Nº do escopo CGCRE (decisão K).', max_length=60)),
                ('procedimento_id', models.UUIDField(blank=True, help_text='FK método (módulo procedimentos-calibracao Wave A; NOT NULL p/ RBC — T-ECMC-007).', null=True)),
                ('documento_regulatorio_id', models.UUIDField(blank=True, help_text='FK Licenças (INV-012; NULLABLE até módulo existir).', null=True)),
                ('versao', models.IntegerField(default=1, help_text='Revisão preserva versão anterior (AC-CAL-015-2).')),
                ('vigente_a_partir', models.DateTimeField(help_text='Início da vigência desta versão.')),
                ('estado', models.CharField(choices=[('RASCUNHO_EXTRAIDO', 'RASCUNHO_EXTRAIDO'), ('CONFIRMADO', 'CONFIRMADO'), ('REVOGADO', 'REVOGADO')], default='CONFIRMADO', help_text='Em escopo_cmc só CONFIRMADO/REVOGADO (rascunho vive em escopo_extraido).', max_length=20)),
                ('origem', models.CharField(choices=[('MANUAL', 'MANUAL'), ('EXTRACAO_PDF', 'EXTRACAO_PDF')], default='MANUAL', help_text='Proveniência: MANUAL ou EXTRACAO_PDF (decisão N).', max_length=20)),
                ('revision', models.IntegerField(default=0, help_text='Optimistic lock CAS. UPDATE WHERE revision=:esperada.')),
                ('vigencia_inicio', models.DateTimeField(help_text='Vigência canônica ADR-0030.')),
                ('vigencia_fim', models.DateTimeField(blank=True, help_text='NULL = aberta. One-shot ao ser superada por nova versão.', null=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, help_text='Cadeia forense.')),
                ('revogado_em', models.DateTimeField(blank=True, help_text='Soft-delete B (ADR-0031). NULL = vigente.', null=True)),
                ('motivo_revogacao', models.TextField(blank=True, default='', help_text='>=10 chars quando revogado (ADR-0030).')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escopos_cmc', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Escopo CMC',
                'verbose_name_plural': 'Escopos CMC',
                'db_table': 'escopo_cmc',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(condition=models.Q(('estado', 'CONFIRMADO'), ('revogado_em__isnull', True)), fields=['tenant', 'grandeza', 'vigencia_fim'], name='ecmc_cobertura_idx'), models.Index(fields=['tenant', 'grandeza', 'estado'], name='ecmc_tenant_gr_est_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'grandeza', 'faixa_min', 'faixa_max', 'procedimento_id', 'versao'), name='uq_escopo_cmc_chave_natural', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='EscopoExtraido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origem_pdf_storage_key', models.CharField(help_text='Chave opaca do PDF CGCRE (documento público).', max_length=200)),
                ('numero_escopo_cgcre', models.CharField(blank=True, default='', max_length=60)),
                ('extraido_em', models.DateTimeField()),
                ('linhas', models.JSONField(default=list, help_text='Lista de LinhaEscopoExtraida (texto cru + confiança).')),
                ('confirmado_em', models.DateTimeField(blank=True, help_text='NULL = pendente conferência humana.', null=True)),
                ('confirmado_por_id_hash', models.CharField(blank=True, default='', max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escopos_extraidos', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Escopo Extraído (staging)',
                'verbose_name_plural': 'Escopos Extraídos (staging)',
                'db_table': 'escopo_extraido',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', 'confirmado_em'], name='eextr_tenant_conf_idx')],
            },
        ),
    ]
