# Generated by Django 5.2.15 on 2026-06-09 00:18
#
# T-FIS-020 — frente fiscal/NFS-e schema inicial (1 tabela achatada).
# nota_fiscal_servico (colunas tipadas) + UNIQUE negocio (tenant, origem_id, versao)
# — INV-FIS-005 idempotencia de negocio.
#
# RLS policies = migration-irma 0002_rls_policies (ADR-0002 §6 pattern v2).
# Triggers WORM Padrao B (block-delete + campos probatorios imutaveis; status
# mutavel por transicao D-FIS-4) = 0003_triggers_worm. GRANT app_user = 0004.
#
# rls-policy: external 0002_rls_policies

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0012_aplicar_evento_cgcre_vigencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalServico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origem_id', models.UUIDField(help_text='Certificado ou OS que disparou a emissão (idempotência de negócio).')),
                ('versao', models.IntegerField(default=1, help_text='Tentativa de emissão para a origem (REJECTED → nova versão).')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('AUTHORIZED', 'AUTHORIZED'), ('REJECTED', 'REJECTED'), ('CANCELED', 'CANCELED')], help_text='PENDING/AUTHORIZED/REJECTED/CANCELED (D-FIS-3). Mutável só por transição válida.', max_length=20)),
                ('tipo_servico', models.CharField(choices=[('calibracao', 'calibracao'), ('manutencao', 'manutencao'), ('outro', 'outro')], help_text='CALIBRACAO exige documento metrológico por perfil (INV-FIS-001).', max_length=20)),
                ('perfil_no_evento', models.CharField(help_text='Snapshot do perfil regulatório do tenant na emissão (ADR-0067 §3).', max_length=1)),
                ('valor_centavos', models.BigIntegerField(help_text='Valor do serviço em centavos (input do caller).')),
                ('cliente_referencia_hash', models.CharField(help_text='Pseudônimo do tomador na trilha (INV-FIS-009 — sem PII clara).', max_length=80)),
                ('provider_invoice_id', models.CharField(blank=True, default='', help_text='id do documento no fornecedor (vazio até emitir).', max_length=120)),
                ('autorizacao_codigo', models.CharField(blank=True, default='', help_text='Código de autorização do fornecedor.', max_length=120)),
                ('rejeicao_motivo', models.TextField(blank=True, default='', help_text='Motivo da rejeição (REJECTED).')),
                ('certificado_id', models.UUIDField(blank=True, help_text='Vínculo metrológico (perfil A/B/C). FK lógica ao M8.', null=True)),
                ('declaracao_id', models.UUIDField(blank=True, help_text='Declaração de calibração básica (perfil D).', null=True)),
                ('tipo_acreditacao_vinculo', models.CharField(blank=True, choices=[('RBC', 'RBC'), ('NAO_RBC', 'NAO_RBC')], default='', help_text='Snapshot do Certificado.tipo_acreditacao do M8 (INV-FIS-002 — nunca reconsulta Tenant).', max_length=10)),
                ('snapshot_hash', models.CharField(help_text='Hash versionado canonicalizado da emissão (ADR-0029/0064). Imutável.', max_length=200)),
                ('emitido_em', models.DateTimeField(blank=True, help_text='One-shot quando autorizada.', null=True)),
                ('cancelado_em', models.DateTimeField(blank=True, help_text='One-shot no cancelamento SEFAZ.', null=True)),
                ('motivo_cancelamento', models.TextField(blank=True, default='', help_text='>=30 chars quando cancelada (AC-FIS-003-1).')),
                ('revision', models.IntegerField(default=0, help_text='Optimistic lock CAS na transição de status.')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, help_text='Cadeia forense.')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_servico', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Nota Fiscal de Serviço (NFS-e)',
                'verbose_name_plural': 'Notas Fiscais de Serviço (NFS-e)',
                'db_table': 'nota_fiscal_servico',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='nfse_tenant_status_idx'), models.Index(fields=['tenant', 'origem_id'], name='nfse_tenant_origem_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'origem_id', 'versao'), name='uq_nfse_origem_versao')],
            },
        ),
    ]
