# Generated by Django 5.2.15 on 2026-06-16 13:04 — + RLS/WORM/grants manuais (Fatia 3b-3 / T-CR-044b)
# rls-policy: notificacao_inadimplencia ENABLE+FORCE+4 policies v2 (ADR-0002 §6)
# audit-immutability: notificacao_inadimplencia INSERT-only (block-update/delete) — prova CDC, nao toca cadeia auditoria
"""T-CR-044b (Fatia 3b-3) — model `NotificacaoInadimplencia` (prova de envio do aviso
D+30/D+45) + RLS pattern v2 + WORM INSERT-only + GRANT app_user.

INSERT-only (block-update/delete — ADR-0031 Padrão B / molde pagamento_titulo do 0003):
a prova de aviso CDC é imutável. RLS isola por tenant (INV-TENANT-*). Base do fail-closed
do bloqueio perfil A (adapter de inadimplência só inclui título com aviso registrado).

# tests-coverage: tests/test_contas_receber_inadimplencia_fatia3.py
"""

import uuid

import django.db.models.deletion
from django.db import migrations, models

_RLS_FORWARD = """
ALTER TABLE notificacao_inadimplencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE notificacao_inadimplencia FORCE ROW LEVEL SECURITY;

CREATE POLICY notificacao_inadimplencia_tenant_isolation_select ON notificacao_inadimplencia
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY notificacao_inadimplencia_tenant_isolation_update ON notificacao_inadimplencia
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY notificacao_inadimplencia_tenant_isolation_delete ON notificacao_inadimplencia
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY notificacao_inadimplencia_tenant_isolation_insert ON notificacao_inadimplencia
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);
"""

_RLS_REVERSE = """
DROP POLICY IF EXISTS notificacao_inadimplencia_tenant_isolation_insert ON notificacao_inadimplencia;
DROP POLICY IF EXISTS notificacao_inadimplencia_tenant_isolation_delete ON notificacao_inadimplencia;
DROP POLICY IF EXISTS notificacao_inadimplencia_tenant_isolation_update ON notificacao_inadimplencia;
DROP POLICY IF EXISTS notificacao_inadimplencia_tenant_isolation_select ON notificacao_inadimplencia;
ALTER TABLE notificacao_inadimplencia DISABLE ROW LEVEL SECURITY;
"""

_WORM_FORWARD = """
CREATE OR REPLACE FUNCTION notificacao_inadimplencia_block_update()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    RAISE EXCEPTION
        'INV-CR-NOTIF-WORM: notificacao_inadimplencia e INSERT-only (prova CDC). '
        'Nao e permitido UPDATE (T-CR-044b / ADR-0031 Padrao B).';
    RETURN NEW;
END;
$body$;

CREATE TRIGGER notificacao_inadimplencia_block_update_trg
    BEFORE UPDATE ON notificacao_inadimplencia
    FOR EACH ROW
    EXECUTE FUNCTION notificacao_inadimplencia_block_update();

CREATE OR REPLACE FUNCTION notificacao_inadimplencia_block_delete()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    RAISE EXCEPTION
        'INV-CR-NOTIF-WORM: notificacao_inadimplencia e INSERT-only (prova CDC). '
        'Nao e permitido DELETE (T-CR-044b / ADR-0031 Padrao B).';
    RETURN OLD;
END;
$body$;

CREATE TRIGGER notificacao_inadimplencia_block_delete_trg
    BEFORE DELETE ON notificacao_inadimplencia
    FOR EACH ROW
    EXECUTE FUNCTION notificacao_inadimplencia_block_delete();
"""

_WORM_REVERSE = """
DROP TRIGGER IF EXISTS notificacao_inadimplencia_block_delete_trg ON notificacao_inadimplencia;
DROP FUNCTION IF EXISTS notificacao_inadimplencia_block_delete();
DROP TRIGGER IF EXISTS notificacao_inadimplencia_block_update_trg ON notificacao_inadimplencia;
DROP FUNCTION IF EXISTS notificacao_inadimplencia_block_update();
"""

_GRANT_FORWARD = "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE notificacao_inadimplencia TO app_user;"
_GRANT_REVERSE = "REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLE notificacao_inadimplencia FROM app_user;"


class Migration(migrations.Migration):
    dependencies = [
        ("contas_receber", "0006_resolver_cr_webhook"),
        ("tenant", "0012_aplicar_evento_cgcre_vigencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificacaoInadimplencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "cliente_referencia_hash",
                    models.CharField(
                        help_text="HMAC do cliente (pseudônimo — D-CR-16). Sem e-mail/PII direta (D-CR-19).",
                        max_length=80,
                    ),
                ),
                (
                    "marco",
                    models.CharField(
                        help_text="Marco do aviso: 'D30' (prévio) | 'D45' (final). Imutável.",
                        max_length=3,
                    ),
                ),
                (
                    "dias_vencido",
                    models.IntegerField(help_text="Dias em atraso no momento do aviso."),
                ),
                (
                    "perfil_no_evento",
                    models.CharField(
                        help_text="Snapshot CHAR(1) do perfil do tenant no aviso (D-CR-6). Wave A: só 'A'.",
                        max_length=1,
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        default="email_cliente",
                        help_text="Canal do aviso (email_cliente). Aviso ao admin = evento, não e-mail.",
                        max_length=20,
                    ),
                ),
                ("enviada_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notificacoes_inadimplencia",
                        to="tenant.tenant",
                    ),
                ),
                (
                    "titulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notificacoes_inadimplencia",
                        to="contas_receber.titulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação de Inadimplência",
                "verbose_name_plural": "Notificações de Inadimplência",
                "db_table": "notificacao_inadimplencia",
                "ordering": ["enviada_em"],
                "indexes": [
                    models.Index(fields=["tenant", "titulo"], name="cr_notif_inad_tenant_tit_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "titulo", "marco"), name="uq_cr_notif_inad_titulo_marco"
                    )
                ],
            },
        ),
        migrations.RunSQL(sql=_RLS_FORWARD, reverse_sql=_RLS_REVERSE),
        migrations.RunSQL(sql=_WORM_FORWARD, reverse_sql=_WORM_REVERSE),
        migrations.RunSQL(sql=_GRANT_FORWARD, reverse_sql=_GRANT_REVERSE),
    ]
