# Generated by Django 5.2.15 on 2026-06-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_receber', '0007_notificacaoinadimplencia'),
        ('tenant', '0012_aplicar_evento_cgcre_vigencia'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_event_id', ''), _negated=True), fields=('tenant', 'gateway_event_id'), name='uq_cr_pagamento_gateway_event'),
        ),
    ]
