# Generated by Django 5.2.14 on 2026-05-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_out', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhookdestino',
            new_name='webhook_des_tenant__afbcd6_idx',
            old_name='webhook_des_tenant__a83e22_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdestino',
            new_name='webhook_des_tenant__5b138d_idx',
            old_name='webhook_des_tenant__c9d4e1_idx',
        ),
        migrations.AlterField(
            model_name='webhookdestino',
            name='categorias_dados',
            field=models.JSONField(default=list, help_text='Array de CategoriaDado. Adapter valida payload contra esta lista.'),
        ),
        migrations.AlterField(
            model_name='webhookdestino',
            name='chave_expires_at',
            field=models.DateField(help_text='Vencimento da chave HMAC (rotacao <=90d - SEG-FC1-03).'),
        ),
        migrations.AlterField(
            model_name='webhookdestino',
            name='chave_hmac_id',
            field=models.CharField(help_text='ID opaco da chave HMAC (lookup em KMS quando F-C3; ate la, env var).', max_length=120),
        ),
        migrations.AlterField(
            model_name='webhookdestino',
            name='dpa_assinado_em',
            field=models.DateField(help_text='Data de assinatura do DPA.'),
        ),
        migrations.AlterField(
            model_name='webhookdestino',
            name='dpa_url',
            field=models.URLField(help_text='Link pro DPA assinado (S3, Drive interno, etc.).', max_length=500),
        ),
        migrations.AlterField(
            model_name='webhookdestino',
            name='dpa_vence_em',
            field=models.DateField(help_text='Data limite de vigencia do DPA (null/infinito proibido).'),
        ),
        migrations.AlterField(
            model_name='webhookdestino',
            name='finalidade',
            field=models.TextField(help_text="Ex: 'cobranca recorrente cliente final', 'envio cartao verde INMETRO'."),
        ),
        migrations.AlterField(
            model_name='webhookdestino',
            name='nome',
            field=models.CharField(help_text="Ex: 'Asaas', 'INMETRO', 'SendGrid'.", max_length=120),
        ),
        migrations.AlterField(
            model_name='webhookdestino',
            name='permite_http',
            field=models.BooleanField(default=False, help_text='Se True, permite porta 80 (anti-pratica; usar so em destino legado).'),
        ),
        migrations.AlterField(
            model_name='webhookdestino',
            name='url_base',
            field=models.URLField(help_text='URL base do destino (ex: https://api.asaas.com). Sem path final.', max_length=500),
        ),
    ]
