# Generated by Django 5.2.14 on 2026-05-18 03:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import src.infrastructure.usuario.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Normalizado pra lowercase. Identificador unico de login.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                ("nome_completo", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Acesso ao /admin/ Django (independente de perfis de aplicacao).",
                    ),
                ),
                (
                    "mfa_obrigatorio",
                    models.BooleanField(
                        default=False,
                        help_text="True para perfis sensiveis (RT, admin_tenant). Marco F-B liga django-otp.",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuarios",
                "ordering": ["email"],
            },
            managers=[
                ("objects", src.infrastructure.usuario.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioPerfilTenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "perfil",
                    models.CharField(
                        help_text="Identificador do perfil (ex: 'admin_tenant', 'tecnico', 'rt_signatario', 'cliente_externo_leitura'). Catalogo completo entra Marco F-B (ADR-0012).",
                        max_length=50,
                    ),
                ),
                ("valido_de", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "valido_ate",
                    models.DateTimeField(
                        blank=True,
                        help_text="NULL = sem expiracao. Perfis temporarios (auditor visitante) usam.",
                        null=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="perfis_usuario",
                        to="tenant.tenant",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="perfis_tenant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil do usuario por tenant",
                "verbose_name_plural": "Perfis do usuario por tenant",
                "db_table": "usuario_perfil_tenant",
                "indexes": [
                    models.Index(
                        fields=["usuario", "valido_de", "valido_ate"], name="ix_perfil_resolucao"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "tenant", "perfil"), name="uq_usuario_tenant_perfil"
                    )
                ],
            },
        ),
    ]
