# Generated by Django 5.2.14 on 2026-05-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_is_break_glass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_break_glass',
            field=models.BooleanField(default=False, help_text='Conta admin-recovery (acesso emergencial pos-MFA perdido). Exige U2F (WebAuthn) — NAO aceita TOTP (defesa contra mesmo vetor que tirou TOTP da conta principal). Login dispara alerta CRITICO + evento Admin.BreakGlass.Usado. Criar via manage.py criar_admin_recovery.'),
        ),
    ]
