# Generated by Django 5.2.15 on 2026-06-11 13:21
"""T-PPS-021 — CreateModel ×5 + UNIQUEs + CHECKs (frente produtos-pecas-servicos).

UNIQUEs: uq_pps_item_codigo (INV-PPS-CODIGO-UNICO) + uq_pps_versao_n +
uq_pps_kit_filho + uq_pps_tabela_padrao (parcial WHERE eh_padrao — D-PPS-3).
CHECKs: preco>0 ×2 (TL-PPS-16) + quantidade>0.

# rls-policy: external 0002_rls_policies
# audit-immutability: skip -- CreateModel puro; triggers WORM em 0003
# tests-coverage: tests/test_pps_schema_fatia1b.py +
# management/commands/validar_produtos_pecas_servicos.py
"""

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0012_aplicar_evento_cgcre_vigencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_interno', models.CharField(help_text='SKU canônico do tenant (imutável — trigger 0003 não cobre; ADR-0007 use case não expõe edição).', max_length=60)),
                ('tipo', models.CharField(choices=[('produto', 'produto'), ('peca', 'peca'), ('servico', 'servico'), ('kit', 'kit')], help_text='produto|peca|servico|kit — imutável. produto×peca são rótulos (TL-PPS-14).', max_length=10)),
                ('codigo_fabricante', models.CharField(blank=True, default='', help_text='Identifica produto, não pessoa (não-PII — ADV-PPS-09).', max_length=60)),
                ('controla_estoque', models.BooleanField(help_text='Flag ESTRUTURAL do item (TL-PPS-12 — não é atributo de versão). Saldo é do módulo Estoque (non-goal).')),
                ('status', models.CharField(choices=[('ativo', 'ativo'), ('inativo', 'inativo')], default='ativo', help_text='ativo|inativo (ADR-0031 — sem DELETE; AC-CAT-005-1).', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_catalogo', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Item de catálogo',
                'verbose_name_plural': 'Itens de catálogo',
                'db_table': 'item_catalogo',
            },
        ),
        migrations.CreateModel(
            name='ItemCatalogoVersao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('versao_n', models.IntegerField(help_text='Denso por item: 1,2,3... (max+1 sob lock).')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='', help_text='Texto livre — em evento WORM vai HASHIFICADA (ADV-PPS-02).')),
                ('categoria', models.CharField(blank=True, default='', max_length=100)),
                ('unidade_medida', models.CharField(help_text='Texto curto validado contra seed de UMs (TL-PPS-11).', max_length=20)),
                ('preco_padrao', models.DecimalField(decimal_places=2, help_text='Preço de LISTA (ADR-0081) — VO Preco: escala 2, > 0 (CHECK).', max_digits=12)),
                ('vigencia_inicio', models.DateTimeField()),
                ('vigencia_fim', models.DateTimeField(blank=True, help_text='One-shot NULL→data (trigger 0003).', null=True)),
                ('revogado_em', models.DateTimeField(blank=True, help_text='One-shot — versão errada sai da exclusion e nunca resolve (lição M2).', null=True)),
                ('motivo_revogacao', models.CharField(blank=True, default='', max_length=200)),
                ('criado_por', models.UUIDField(help_text='Pseudônimo art. 12 LGPD (RAT-PPS-CRIADO-POR); evento WORM leva só hash.')),
                ('motivo', models.CharField(blank=True, default='', help_text='Texto livre — em evento WORM vai HASHIFICADO (ADV-PPS-02).', max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes', to='produtos_pecas_servicos.itemcatalogo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes_catalogo', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Versão de item de catálogo',
                'verbose_name_plural': 'Versões de item de catálogo',
                'db_table': 'item_catalogo_versao',
            },
        ),
        migrations.CreateModel(
            name='KitComposicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Fracionária legítima (0.5 kg de solda) — > 0 (CHECK).', max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item_filho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_em_kits', to='produtos_pecas_servicos.itemcatalogo')),
                ('kit_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composicao', to='produtos_pecas_servicos.itemcatalogo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kits_composicao', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Composição de kit',
                'verbose_name_plural': 'Composições de kit',
                'db_table': 'kit_composicao',
            },
        ),
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, default='')),
                ('eh_padrao', models.BooleanField(default=False, help_text='Única por tenant no MVP (UNIQUE parcial — molde INV-037).')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabelas_preco', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Tabela de preço',
                'verbose_name_plural': 'Tabelas de preço',
                'db_table': 'tabela_preco',
            },
        ),
        migrations.CreateModel(
            name='LinhaTabelaPreco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço de VENDA — > 0 (CHECK; 0 é sentinela da OS — TL-PPS-16).', max_digits=12)),
                ('vigencia_inicio', models.DateTimeField()),
                ('vigencia_fim', models.DateTimeField(blank=True, null=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_revogacao', models.CharField(blank=True, default='', max_length=200)),
                ('origem_sugestao', models.CharField(choices=[('manual', 'manual'), ('soma_partes', 'soma_partes')], default='manual', help_text='manual|soma_partes — origem do VALOR sugerido na criação (ADV-PPS-08).', max_length=12)),
                ('criado_por', models.UUIDField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas_preco', to='produtos_pecas_servicos.itemcatalogo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas_tabela_preco', to='tenant.tenant')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas', to='produtos_pecas_servicos.tabelapreco')),
            ],
            options={
                'verbose_name': 'Linha de tabela de preço',
                'verbose_name_plural': 'Linhas de tabela de preço',
                'db_table': 'linha_tabela_preco',
            },
        ),
        migrations.AddIndex(
            model_name='itemcatalogo',
            index=models.Index(fields=['tenant', 'status'], name='ix_pps_item_status'),
        ),
        migrations.AddConstraint(
            model_name='itemcatalogo',
            constraint=models.UniqueConstraint(fields=('tenant', 'codigo_interno'), name='uq_pps_item_codigo'),
        ),
        migrations.AddIndex(
            model_name='itemcatalogoversao',
            index=models.Index(fields=['tenant', 'item'], name='ix_pps_versao_item'),
        ),
        migrations.AddConstraint(
            model_name='itemcatalogoversao',
            constraint=models.UniqueConstraint(fields=('tenant', 'item', 'versao_n'), name='uq_pps_versao_n'),
        ),
        migrations.AddConstraint(
            model_name='itemcatalogoversao',
            constraint=models.CheckConstraint(condition=models.Q(('preco_padrao__gt', 0)), name='ck_pps_versao_preco_positivo'),
        ),
        migrations.AddConstraint(
            model_name='kitcomposicao',
            constraint=models.UniqueConstraint(fields=('tenant', 'kit_item', 'item_filho'), name='uq_pps_kit_filho'),
        ),
        migrations.AddConstraint(
            model_name='kitcomposicao',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='ck_pps_kit_qtd_positiva'),
        ),
        migrations.AddConstraint(
            model_name='tabelapreco',
            constraint=models.UniqueConstraint(condition=models.Q(('eh_padrao', True)), fields=('tenant',), name='uq_pps_tabela_padrao'),
        ),
        migrations.AddIndex(
            model_name='linhatabelapreco',
            index=models.Index(fields=['tenant', 'tabela', 'item'], name='ix_pps_linha_chave'),
        ),
        migrations.AddConstraint(
            model_name='linhatabelapreco',
            constraint=models.CheckConstraint(condition=models.Q(('preco__gt', 0)), name='ck_pps_linha_preco_positivo'),
        ),
    ]
