# Generated by Django 5.2.14 on 2026-05-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idempotencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chaveidempotencia',
            new_name='idempotenci_expira__713b53_idx',
            old_name='idempotenci_expira__db3a82_idx',
        ),
        migrations.RenameIndex(
            model_name='chaveidempotencia',
            new_name='idempotenci_tenant__01539e_idx',
            old_name='idempotenci_tenant__cf9d33_idx',
        ),
    ]
