# Generated by Django 5.2.14 on 2026-06-01 22:46
# rls-policy: external 0002_rls_policies (RLS pattern v2 nas 5 tabelas — molde M5-M8)
# audit-immutability: external 0003_triggers_worm (WORM Padrao B — revisao/evento append-only)

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0011_acreditacao_vigencia_fim'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRegulatorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ACREDITACAO_CGCRE', 'ACREDITACAO_CGCRE'), ('ALVARA', 'ALVARA'), ('LICENCA_AMBIENTAL', 'LICENCA_AMBIENTAL'), ('LICENCA_SANITARIA', 'LICENCA_SANITARIA'), ('CERTIDAO_NEGATIVA', 'CERTIDAO_NEGATIVA'), ('ART', 'ART'), ('RRT', 'RRT'), ('CERT_DIGITAL_A1', 'CERT_DIGITAL_A1'), ('CERT_DIGITAL_A3', 'CERT_DIGITAL_A3'), ('AUTORIZACAO_ANVISA', 'AUTORIZACAO_ANVISA'), ('AUTORIZACAO_INMETRO', 'AUTORIZACAO_INMETRO'), ('OUTRO', 'OUTRO')], help_text='Tipo do documento (acreditação CGCRE, ART/RRT, licença, etc).', max_length=30)),
                ('numero', models.CharField(help_text='Número do documento no órgão emissor.', max_length=120)),
                ('orgao_emissor', models.CharField(help_text='Órgão emissor (CGCRE, CREA, etc).', max_length=120)),
                ('vigencia_inicio', models.DateField(help_text='Início da vigência (data_emissao da revisão atual).')),
                ('vigencia_fim', models.DateField(help_text='Fim da vigência (data_validade). ADR-0030.')),
                ('bloqueante', models.BooleanField(default=False, help_text='Vencido bloqueia operação dependente (INV-032). Fronteira por tipo (D-LIC-5).')),
                ('status_cache', models.CharField(choices=[('VIGENTE', 'VIGENTE'), ('VENCE_EM_BREVE', 'VENCE_EM_BREVE'), ('VENCIDO', 'VENCIDO'), ('EM_RENOVACAO', 'EM_RENOVACAO')], default='VIGENTE', help_text='Cache do status calculado (verdade = vigencia_fim vs hoje). Recalculado no job.', max_length=20)),
                ('escopo', models.TextField(blank=True, default='', help_text='Grandezas/faixas — obrigatório para ACREDITACAO_CGCRE (RBC-M9-05).')),
                ('numero_cgcre', models.CharField(blank=True, default='', help_text='Nº CGCRE (acreditação).', max_length=60)),
                ('ilac_mra_aderido', models.BooleanField(default=False, help_text='Aderência ILAC-MRA (só perfil A — espelha Tenant.ilac_mra).')),
                ('titular_referencia_hash', models.CharField(blank=True, default='', help_text='Hash KMS do CPF/nome do titular (ART/RRT) — ADR-0032 PII anonimizável.', max_length=128)),
                ('titular_referencia_key_id', models.CharField(blank=True, default='', help_text='key_id versionado (vN) do hash — ADR-0032.', max_length=40)),
                ('responsavel_id', models.UUIDField(blank=True, help_text='FK Usuario que cuida da renovação (mutável).', null=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('perfil_emissor_no_momento', models.CharField(blank=True, default='', help_text='Snapshot do perfil do tenant na criação (ADR-0067).', max_length=1)),
                ('revision', models.IntegerField(default=0, help_text='Optimistic lock CAS. UPDATE WHERE revision=:esperada.')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, help_text='Cadeia forense.')),
                ('revogado_em', models.DateTimeField(blank=True, help_text='Soft-delete B (ADR-0031). NULL = vigente.', null=True)),
                ('motivo_revogacao', models.TextField(blank=True, default='', help_text='>=10 chars quando revogado (ADR-0030).')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('criado_por', models.UUIDField(help_text='Ator do cadastro.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_regulatorios', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Documento Regulatório',
                'verbose_name_plural': 'Documentos Regulatórios',
                'db_table': 'documento_regulatorio',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='BloqueioOperacional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('ACREDITACAO_CGCRE', 'ACREDITACAO_CGCRE'), ('ALVARA', 'ALVARA'), ('LICENCA_AMBIENTAL', 'LICENCA_AMBIENTAL'), ('LICENCA_SANITARIA', 'LICENCA_SANITARIA'), ('CERTIDAO_NEGATIVA', 'CERTIDAO_NEGATIVA'), ('ART', 'ART'), ('RRT', 'RRT'), ('CERT_DIGITAL_A1', 'CERT_DIGITAL_A1'), ('CERT_DIGITAL_A3', 'CERT_DIGITAL_A3'), ('AUTORIZACAO_ANVISA', 'AUTORIZACAO_ANVISA'), ('AUTORIZACAO_INMETRO', 'AUTORIZACAO_INMETRO'), ('OUTRO', 'OUTRO')], help_text='Determina a fronteira REBAIXA vs HARD-409 (D-LIC-5).', max_length=30)),
                ('operacao_bloqueada', models.CharField(help_text="Ex.: 'assinatura_certificado'.", max_length=80)),
                ('data_inicio_bloqueio', models.DateTimeField()),
                ('data_fim_bloqueio', models.DateTimeField(blank=True, help_text='NULL = ativo. Auto-resolve na renovação.', null=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloqueios_operacionais', to='tenant.tenant')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloqueios', to='licencas_acreditacoes.documentoregulatorio')),
            ],
            options={
                'verbose_name': 'Bloqueio Operacional',
                'verbose_name_plural': 'Bloqueios Operacionais',
                'db_table': 'bloqueio_operacional',
                'ordering': ['-data_inicio_bloqueio'],
            },
        ),
        migrations.CreateModel(
            name='AlertaVencimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_disparo', models.DateField()),
                ('janela_dias', models.IntegerField(help_text='90/60/30/15/7 (JANELAS_ALERTA_DIAS).')),
                ('canal', models.CharField(choices=[('EMAIL', 'EMAIL'), ('DASHBOARD', 'DASHBOARD'), ('APP', 'APP')], max_length=20)),
                ('destinatario_id', models.UUIDField()),
                ('status', models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('ENVIADO', 'ENVIADO'), ('LIDO', 'LIDO'), ('FALHOU', 'FALHOU')], default='PENDENTE', max_length=20)),
                ('tentativas', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_vencimento', to='tenant.tenant')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='licencas_acreditacoes.documentoregulatorio')),
            ],
            options={
                'verbose_name': 'Alerta de Vencimento',
                'verbose_name_plural': 'Alertas de Vencimento',
                'db_table': 'alerta_vencimento',
                'ordering': ['-data_disparo'],
            },
        ),
        migrations.CreateModel(
            name='EventoEmergencialLicenca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operacao_executada', models.CharField(max_length=80)),
                ('justificativa', models.TextField(help_text='>=100 chars (INV-033 reconciliado — D-LIC-7).')),
                ('justificativa_hash', models.CharField(help_text='sha256 da justificativa (WORM).', max_length=64)),
                ('admin_id', models.UUIDField()),
                ('assinatura_a3_id', models.UUIDField(help_text='FK A3 (existência exigida; validação cripto diferida).')),
                ('libera_apenas_nao_rbc', models.BooleanField(default=False, help_text='True quando o bloqueio é de acreditação CGCRE (D-LIC-6).')),
                ('expira_em', models.DateTimeField(help_text='Janela ≤7d.')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bloqueio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_emergenciais', to='licencas_acreditacoes.bloqueiooperacional')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_emergenciais_licenca', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Evento Emergencial (Licença)',
                'verbose_name_plural': 'Eventos Emergenciais (Licença)',
                'db_table': 'evento_emergencial_licenca',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RevisaoDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_revisao', models.IntegerField(help_text='Incremental por documento (1 = cadastro inicial).')),
                ('data_emissao', models.DateField()),
                ('data_validade', models.DateField(help_text='data_validade > data_emissao.')),
                ('anexo_id', models.UUIDField(help_text='FK Anexo (B2 WORM).')),
                ('anexo_sha256', models.CharField(help_text='sha256 server-side (INV-LIC-ANEXO-001).', max_length=64)),
                ('motivo', models.CharField(choices=[('CADASTRO_INICIAL', 'CADASTRO_INICIAL'), ('RENOVACAO', 'RENOVACAO'), ('RETIFICACAO', 'RETIFICACAO')], max_length=20)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('criado_por', models.UUIDField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisoes', to='licencas_acreditacoes.documentoregulatorio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisoes_documento', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Revisão de Documento',
                'verbose_name_plural': 'Revisões de Documento',
                'db_table': 'revisao_documento',
                'ordering': ['documento', '-numero_revisao'],
            },
        ),
        migrations.AddIndex(
            model_name='documentoregulatorio',
            index=models.Index(fields=['tenant', 'tipo', 'status_cache'], name='docreg_tenant_tipo_st_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoregulatorio',
            index=models.Index(fields=['tenant', 'vigencia_fim'], name='docreg_tenant_vigfim_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentoregulatorio',
            constraint=models.UniqueConstraint(fields=('tenant', 'tipo', 'numero', 'orgao_emissor'), name='uq_documento_regulatorio_chave_natural'),
        ),
        migrations.AddIndex(
            model_name='bloqueiooperacional',
            index=models.Index(fields=['tenant', 'documento', 'data_fim_bloqueio'], name='bloq_tenant_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='alertavencimento',
            index=models.Index(fields=['tenant', 'status', 'data_disparo'], name='alerta_tenant_st_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertavencimento',
            constraint=models.UniqueConstraint(fields=('tenant', 'documento', 'janela_dias'), name='uq_alerta_vencimento_idempotente'),
        ),
        migrations.AddIndex(
            model_name='eventoemergenciallicenca',
            index=models.Index(fields=['tenant', 'bloqueio'], name='evtemerg_tenant_bloq_idx'),
        ),
        migrations.AddConstraint(
            model_name='revisaodocumento',
            constraint=models.UniqueConstraint(fields=('tenant', 'documento', 'numero_revisao'), name='uq_revisao_documento_numero'),
        ),
    ]
