# Generated by Django 5.2.15 on 2026-06-10 04:21
#
# T-CFG-021 — frente configuracoes-sistema schema inicial (5 tabelas).
# empresa + filial (INV-036/037) | imposto (catalogo versionado imutavel) |
# serie_documento (2 regimes ADR-0080; chave TL-06 com UNIQUE parcial p/
# filial NULL=global) | numero_documento_reservado (reserva gap-less,
# espelha numero_certificado_reservado do M8 — TL-02).
#
# RLS policies = migration-irma 0002_rls_policies (ADR-0002 §6 pattern v2).
# Triggers INV-028 / INV-CFG-IMPOSTO-IMUTAVEL / numeracao = 0003. Exclusion
# constraint btree_gist (INV-CFG-IMPOSTO-SEM-SOBREPOSICAO) = 0004. GRANT
# app_user = 0005. Seed authz = 0006.
#
# rls-policy: external 0002_rls_policies

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenant", "0012_aplicar_evento_cgcre_vigencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("razao_social", models.CharField(max_length=200)),
                (
                    "cnpj",
                    models.CharField(
                        help_text="Normalizado pelo VO CNPJ (ADR-0017 — alfanumérico IN RFB 2.229/2024).",
                        max_length=14,
                    ),
                ),
                (
                    "regime_tributario",
                    models.CharField(
                        choices=[
                            ("normal", "normal"),
                            ("simples_nacional", "simples_nacional"),
                            ("mei", "mei"),
                            ("lucro_presumido", "lucro_presumido"),
                            ("lucro_real", "lucro_real"),
                            ("imune", "imune"),
                            ("isento", "isento"),
                        ],
                        help_text="Conjunto final exigível = validação contador/OAB pré-produção (D-CFG-9).",
                        max_length=20,
                    ),
                ),
                ("inscricao_estadual", models.CharField(blank=True, default="", max_length=20)),
                ("inscricao_municipal", models.CharField(blank=True, default="", max_length=20)),
                ("endereco", models.TextField(blank=True, default="")),
                ("logo_url", models.CharField(blank=True, default="", max_length=300)),
                ("site", models.CharField(blank=True, default="", max_length=200)),
                ("telefone", models.CharField(blank=True, default="", max_length=20)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empresas_config",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa (cadastro tributário)",
                "verbose_name_plural": "Empresas (cadastro tributário)",
                "db_table": "empresa",
            },
        ),
        migrations.CreateModel(
            name="Filial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        help_text="CNPJ próprio da filial (AC-CFG-001-2; VO ADR-0017).",
                        max_length=14,
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "eh_matriz",
                    models.BooleanField(
                        default=False,
                        help_text="Exatamente 1 por empresa (INV-037 — UNIQUE parcial).",
                    ),
                ),
                ("endereco", models.TextField(blank=True, default="")),
                ("inscricao_estadual", models.CharField(blank=True, default="", max_length=20)),
                ("inscricao_municipal", models.CharField(blank=True, default="", max_length=20)),
                ("telefone", models.CharField(blank=True, default="", max_length=20)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filiais",
                        to="configuracoes_sistema.empresa",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filiais_config",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filial",
                "verbose_name_plural": "Filiais",
                "db_table": "filial",
            },
        ),
        migrations.CreateModel(
            name="Imposto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("icms", "icms"),
                            ("iss", "iss"),
                            ("pis", "pis"),
                            ("cofins", "cofins"),
                            ("irrf", "irrf"),
                            ("csll", "csll"),
                            ("inss", "inss"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "aliquota",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Pontos percentuais 0..100 (VO Aliquota). Imutável — nova linha por vigência.",
                        max_digits=7,
                    ),
                ),
                ("vigencia_inicio", models.DateTimeField()),
                (
                    "vigencia_fim",
                    models.DateTimeField(
                        blank=True,
                        help_text="NULL = vigência aberta. Encerrar = one-shot NULL→data (D-CFG-3).",
                        null=True,
                    ),
                ),
                (
                    "revogado_em",
                    models.DateTimeField(
                        blank=True,
                        help_text="One-shot. Linha cadastrada errada (DELETE físico é bloqueado — retenção 5a).",
                        null=True,
                    ),
                ),
                (
                    "motivo_revogacao",
                    models.TextField(
                        blank=True, default="", help_text="≥10 chars quando revogado (INV-VIG-002)."
                    ),
                ),
                ("cfop_padrao", models.CharField(blank=True, default="", max_length=10)),
                ("ncm_padrao", models.CharField(blank=True, default="", max_length=10)),
                (
                    "iss_retido_fonte",
                    models.BooleanField(
                        default=False, help_text="LC 116/2003 art. 6º (ADV-02/D-CFG-9)."
                    ),
                ),
                (
                    "tem_st",
                    models.BooleanField(
                        default=False, help_text="ST do ICMS é atributo, NÃO regime (ADV-03)."
                    ),
                ),
                (
                    "simples_excedeu_sublimite",
                    models.BooleanField(
                        default=False, help_text="Sublimite do Simples estourado (ADV-02)."
                    ),
                ),
                ("observacoes", models.TextField(blank=True, default="")),
                ("correlation_id", models.UUIDField(default=uuid.uuid4)),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "filial",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = catálogo do tenant inteiro (ISS municipal usa filial).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impostos",
                        to="configuracoes_sistema.filial",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impostos_config",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imposto (linha de catálogo)",
                "verbose_name_plural": "Impostos (catálogo tributário)",
                "db_table": "imposto",
                "ordering": ["tenant", "tipo", "vigencia_inicio"],
            },
        ),
        migrations.CreateModel(
            name="SerieDocumento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("os", "os"),
                            ("orcamento", "orcamento"),
                            ("fatura", "fatura"),
                            ("certificado", "certificado"),
                            ("recibo", "recibo"),
                            ("interno", "interno"),
                        ],
                        help_text="os/orcamento/fatura/certificado/recibo/interno (nf/nfse NÃO — ADV-04).",
                        max_length=20,
                    ),
                ),
                ("prefixo", models.CharField(max_length=16)),
                (
                    "proximo_numero",
                    models.IntegerField(
                        default=1,
                        help_text="Próximo a alocar. Nunca diminui (INV-028), exceto reset anual.",
                    ),
                ),
                (
                    "regime_numeracao",
                    models.CharField(
                        choices=[("gap_less", "gap_less"), ("buracos_aceitos", "buracos_aceitos")],
                        help_text="DERIVADO do tipo (ADR-0080) — imutável (trigger 0003).",
                        max_length=20,
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        default="{prefixo}-{seq}",
                        help_text="Placeholders: {prefixo}, {seq} (com padding), {ano}.",
                        max_length=60,
                    ),
                ),
                ("padding", models.IntegerField(default=6)),
                (
                    "reset_anual",
                    models.BooleanField(
                        default=False,
                        help_text="Contador por (série, ano) quando formato usa {ano} (TL-07).",
                    ),
                ),
                (
                    "ano_corrente",
                    models.IntegerField(
                        blank=True,
                        help_text="Ano do contador atual (só com reset_anual).",
                        null=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "filial",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = série global do tenant.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="series_documento",
                        to="configuracoes_sistema.filial",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="series_documento",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Série de documento",
                "verbose_name_plural": "Séries de documento",
                "db_table": "serie_documento",
            },
        ),
        migrations.CreateModel(
            name="NumeroDocumentoReservado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "ano",
                    models.IntegerField(
                        help_text="Dimensão do contador (TL-07). 0 = série sem reset anual."
                    ),
                ),
                (
                    "sequencial",
                    models.IntegerField(help_text="Número denso ≥1 (sem buracos confirmados)."),
                ),
                ("reservado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "ttl_expira_em",
                    models.DateTimeField(
                        help_text="Reserva não-confirmada expira aqui (TTL 5min — motor M8)."
                    ),
                ),
                (
                    "confirmado",
                    models.BooleanField(
                        default=False,
                        help_text="True na confirmação one-shot (transação do emissor).",
                    ),
                ),
                ("correlation_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="numeros_documento_reservados",
                        to="tenant.tenant",
                    ),
                ),
                (
                    "serie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="numeros_reservados",
                        to="configuracoes_sistema.seriedocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Número de documento reservado",
                "verbose_name_plural": "Números de documento reservados",
                "db_table": "numero_documento_reservado",
                "ordering": ["tenant", "serie", "ano", "sequencial"],
            },
        ),
        migrations.AddConstraint(
            model_name="empresa",
            constraint=models.UniqueConstraint(
                fields=("tenant", "cnpj"), name="uq_cfg_empresa_cnpj"
            ),
        ),
        migrations.AddConstraint(
            model_name="filial",
            constraint=models.UniqueConstraint(
                fields=("tenant", "cnpj"), name="uq_cfg_filial_cnpj"
            ),
        ),
        migrations.AddConstraint(
            model_name="filial",
            constraint=models.UniqueConstraint(
                condition=models.Q(("eh_matriz", True)),
                fields=("tenant", "empresa"),
                name="uq_cfg_filial_uma_matriz",
            ),
        ),
        migrations.AddIndex(
            model_name="imposto",
            index=models.Index(fields=["tenant", "tipo"], name="imposto_tenant_tipo_idx"),
        ),
        migrations.AddConstraint(
            model_name="seriedocumento",
            constraint=models.UniqueConstraint(
                condition=models.Q(("filial__isnull", False)),
                fields=("tenant", "filial", "tipo", "prefixo"),
                name="uq_cfg_serie_chave_filial",
            ),
        ),
        migrations.AddConstraint(
            model_name="seriedocumento",
            constraint=models.UniqueConstraint(
                condition=models.Q(("filial__isnull", True)),
                fields=("tenant", "tipo", "prefixo"),
                name="uq_cfg_serie_chave_global",
            ),
        ),
        migrations.AddIndex(
            model_name="numerodocumentoreservado",
            index=models.Index(
                fields=["tenant", "serie", "ano"], name="ix_num_doc_reservado_chave"
            ),
        ),
        migrations.AddConstraint(
            model_name="numerodocumentoreservado",
            constraint=models.UniqueConstraint(
                fields=("tenant", "serie", "ano", "sequencial"), name="uq_num_doc_reservado"
            ),
        ),
    ]
