# Generated by Django 5.2.15 on 2026-06-17 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0007_seed_feriados"),
        ("tenant", "0012_aplicar_evento_cgcre_vigencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capacidadetecnico",
            name="colaborador_id",
            field=models.UUIDField(
                help_text="Colaborador técnico (FK lógica — colaboradores FECHADO)."
            ),
        ),
        migrations.AlterField(
            model_name="capacidadetecnico",
            name="dias_trabalho",
            field=models.IntegerField(
                default=31,
                help_text="Bitmask: bit 0=seg, ..., bit 6=dom. Default seg-sex (31 = 0b0011111).",
            ),
        ),
        migrations.AlterField(
            model_name="capacidadetecnico",
            name="hora_fim",
            field=models.IntegerField(
                default=17, help_text="Hora de fim do expediente (0-23). Default 17."
            ),
        ),
        migrations.AlterField(
            model_name="capacidadetecnico",
            name="hora_inicio",
            field=models.IntegerField(
                default=8, help_text="Hora de início do expediente (0-23). Default 8."
            ),
        ),
        migrations.AlterField(
            model_name="capacidadetecnico",
            name="horas_uteis_dia",
            field=models.IntegerField(
                default=8, help_text="Horas úteis por dia de trabalho (default 8)."
            ),
        ),
        migrations.AlterField(
            model_name="capacidadetecnico",
            name="vigencia_fim",
            field=models.DateField(
                blank=True, help_text="Fim da vigência (None = vigente indefinidamente).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="capacidadetecnico",
            name="vigencia_inicio",
            field=models.DateField(help_text="Início da vigência desta configuração."),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="aloca_em_umc",
            field=models.BooleanField(
                default=False,
                help_text="Técnico sendo alocado em campo/UMC (ativa validação de jornada UMC — D-AGE-4).",
            ),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="atividade_id",
            field=models.UUIDField(
                blank=True,
                help_text="FK lógica à AtividadeDaOS (ADR-0023/0051). NOT NULL quando tipo='os' (CHECK — INV-AG-ATIVIDADE-001).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="confirmar_feriado",
            field=models.BooleanField(
                default=False,
                help_text="Confirmação explícita de agendamento em feriado (D-AGE-10).",
            ),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="criado_por_usuario_id",
            field=models.UUIDField(help_text="Usuário que criou o evento."),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="descricao_publica",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Descrição pública do evento (visível ao cliente em Wave B).",
            ),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="estado",
            field=models.CharField(
                choices=[
                    ("agendado", "agendado"),
                    ("em_execucao", "em_execucao"),
                    ("concluido", "concluido"),
                    ("cancelado", "cancelado"),
                    ("no_show", "no_show"),
                ],
                help_text="Estado da máquina de estados (D-AGE-3 Padrão A).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="inicia_at",
            field=models.DateTimeField(
                help_text="Início do evento (timezone-aware). Componente do EXCLUDE GIST."
            ),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="motivo_bloqueio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ferias", "ferias"),
                    ("treinamento", "treinamento"),
                    ("atestado", "atestado"),
                    ("outro", "outro"),
                ],
                default="",
                help_text="Motivo do bloqueio (só quando tipo='bloqueio' — US-AG-004).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="ocorrencia_dt",
            field=models.DateTimeField(
                blank=True,
                help_text="Data-âncora da ocorrência na série de recorrência. UNIQUE com recorrencia_id (INV-AG-RECORRENCIA-001 / R10).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="os_id",
            field=models.UUIDField(
                blank=True, help_text="OS de origem (desnormalizado derivado — D-AGE-2).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="recorrencia_id",
            field=models.UUIDField(
                blank=True,
                help_text="FK à Recorrencia originadora (None = evento avulso).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="revision",
            field=models.IntegerField(
                default=0,
                help_text="Contador de transições de estado (OCC / observabilidade). Bumpa por F('revision')+1.",
            ),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="tecnico_id",
            field=models.UUIDField(
                help_text="Colaborador alocado (FK lógica — não FK hard para colaboradores FECHADO)."
            ),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="termina_at",
            field=models.DateTimeField(
                help_text="Fim do evento (timezone-aware). Componente do EXCLUDE GIST (half-open)."
            ),
        ),
        migrations.AlterField(
            model_name="eventoagenda",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("os", "os"),
                    ("bloqueio", "bloqueio"),
                    ("descanso_legal", "descanso_legal"),
                    ("deslocamento", "deslocamento"),
                    ("almoco", "almoco"),
                    ("manutencao_interna", "manutencao_interna"),
                    ("feriado", "feriado"),
                ],
                help_text="Tipo do evento (D-AGE-2/3).",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="eventoauditoriaagenda",
            name="acao",
            field=models.CharField(
                choices=[
                    ("criado", "criado"),
                    ("movido", "movido"),
                    ("reagendado", "reagendado"),
                    ("bloqueado", "bloqueado"),
                    ("cancelado", "cancelado"),
                    ("aprovado", "aprovado"),
                    ("no_show", "no_show"),
                    ("regime_indeterminado", "regime_indeterminado"),
                ],
                help_text="Ação auditada (INV-AG-AUDIT-WORM-001).",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="eventoauditoriaagenda",
            name="actor_usuario_id",
            field=models.UUIDField(
                blank=True,
                help_text="Usuário que executou a ação (None = sistema/consumer).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventoauditoriaagenda",
            name="evento_id",
            field=models.UUIDField(db_index=True, help_text="FK lógica ao EventoAgenda auditado."),
        ),
        migrations.AlterField(
            model_name="eventoauditoriaagenda",
            name="occurred_at",
            field=models.DateTimeField(help_text="Momento em que a ação ocorreu (timezone-aware)."),
        ),
        migrations.AlterField(
            model_name="eventoauditoriaagenda",
            name="payload_resumo",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Resumo não-PII da mudança (diff de campos relevantes).",
            ),
        ),
        migrations.AlterField(
            model_name="feriado",
            name="ativo",
            field=models.BooleanField(
                default=True,
                help_text="False = feriado removido do calendário (soft-delete para custom).",
            ),
        ),
        migrations.AlterField(
            model_name="feriado",
            name="data",
            field=models.DateField(help_text="Data do feriado."),
        ),
        migrations.AlterField(
            model_name="feriado",
            name="descricao",
            field=models.CharField(help_text="Nome do feriado.", max_length=200),
        ),
        migrations.AlterField(
            model_name="feriado",
            name="nacional",
            field=models.BooleanField(
                default=True,
                help_text="True = feriado nacional (seed); False = estadual/municipal/empresa.",
            ),
        ),
        migrations.AlterField(
            model_name="feriado",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="None = feriado nacional (seed); UUID = custom por tenant.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feriados_custom",
                to="tenant.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="recorrenciaagenda",
            name="ativo",
            field=models.BooleanField(
                default=True, help_text="Se False, o job de materialização para de expandir."
            ),
        ),
        migrations.AlterField(
            model_name="recorrenciaagenda",
            name="duracao_minutos",
            field=models.IntegerField(
                help_text="Duração de cada ocorrência materializada em minutos."
            ),
        ),
        migrations.AlterField(
            model_name="recorrenciaagenda",
            name="inicia_em",
            field=models.DateTimeField(help_text="Âncora de início da série recorrente."),
        ),
        migrations.AlterField(
            model_name="recorrenciaagenda",
            name="rrule_str",
            field=models.TextField(help_text="Regra RRULE RFC 5545 serializada como string."),
        ),
        migrations.AlterField(
            model_name="recorrenciaagenda",
            name="tecnico_id",
            field=models.UUIDField(help_text="Colaborador da série recorrente."),
        ),
        migrations.AlterField(
            model_name="recorrenciaagenda",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("os", "os"),
                    ("bloqueio", "bloqueio"),
                    ("descanso_legal", "descanso_legal"),
                    ("deslocamento", "deslocamento"),
                    ("almoco", "almoco"),
                    ("manutencao_interna", "manutencao_interna"),
                    ("feriado", "feriado"),
                ],
                help_text="Tipo do evento materializado.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="regimejornadacolaborador",
            name="colaborador_id",
            field=models.UUIDField(
                help_text="Colaborador com enquadramento de regime (FK lógica — colaboradores FECHADO)."
            ),
        ),
        migrations.AlterField(
            model_name="regimejornadacolaborador",
            name="definido_por_usuario_id",
            field=models.UUIDField(
                help_text="Usuário humano (RH/advogado) que fez o override (INV-AG-REGIME-001)."
            ),
        ),
        migrations.AlterField(
            model_name="regimejornadacolaborador",
            name="fonte",
            field=models.CharField(
                choices=[
                    ("override_humano", "override_humano"),
                    ("derivado_papel", "derivado_papel"),
                    ("indeterminado", "indeterminado"),
                ],
                default="override_humano",
                help_text="Fonte do enquadramento — SEMPRE override_humano nesta tabela (INV-AG-REGIME-001).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="regimejornadacolaborador",
            name="justificativa",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Justificativa do enquadramento (recomendado ≥50 chars para rastreabilidade).",
            ),
        ),
        migrations.AlterField(
            model_name="regimejornadacolaborador",
            name="regime",
            field=models.CharField(
                choices=[
                    ("motorista_profissional", "motorista_profissional"),
                    ("clt_geral", "clt_geral"),
                    ("nao_aplica", "nao_aplica"),
                ],
                help_text="Regime de jornada enquadrado (D-AGE-15).",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="regimejornadacolaborador",
            name="vigencia_fim",
            field=models.DateField(
                blank=True, help_text="Fim da vigência (None = vigente indefinidamente).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="regimejornadacolaborador",
            name="vigencia_inicio",
            field=models.DateField(help_text="Início da vigência do enquadramento."),
        ),
        migrations.AlterField(
            model_name="registronoshow",
            name="cobrar_cliente",
            field=models.BooleanField(
                default=False,
                help_text="Se True, o use case dispara AReceberPort (INV-AG-NOSHOW-AR-001).",
            ),
        ),
        migrations.AlterField(
            model_name="registronoshow",
            name="custo_estimado",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Custo estimado da visita frustrada (R$, 2 casas decimais).",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="registronoshow",
            name="evento_id",
            field=models.UUIDField(help_text="FK lógica ao EventoAgenda que originou o no-show."),
        ),
        migrations.AlterField(
            model_name="registronoshow",
            name="observacao",
            field=models.TextField(
                blank=True, default="", help_text="Observação livre (sem PII do cliente)."
            ),
        ),
        migrations.AlterField(
            model_name="registronoshow",
            name="ocorrido_em",
            field=models.DateTimeField(help_text="Momento em que o no-show foi constatado."),
        ),
        migrations.AlterField(
            model_name="registronoshow",
            name="registrado_por_usuario_id",
            field=models.UUIDField(help_text="Usuário que registrou o no-show."),
        ),
        migrations.AlterField(
            model_name="registronoshow",
            name="tecnico_id",
            field=models.UUIDField(help_text="Técnico que não compareceu."),
        ),
    ]
