# Generated by Django 5.2.15 on 2026-06-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_alter_capacidadetecnico_colaborador_id_and_more'),
        ('tenant', '0012_aplicar_evento_cgcre_vigencia'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='registronoshow',
            name='ag_nsh_tenant_evento_idx',
        ),
        migrations.AddConstraint(
            model_name='registronoshow',
            constraint=models.UniqueConstraint(fields=('tenant', 'evento_id'), name='uq_no_show_evento'),
        ),
    ]
