# Generated by Django 5.2.15 on 2026-06-13 01:49
# rls-policy: external 0002_rls_policies (AlterField metadados -- nao cria tabela)
# audit-immutability: skip -- AlterField de metadados nao toca triggers de auditoria

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0006_seed_authz_precificacao'),
        ('produtos_pecas_servicos', '0011_p9_consertos_imutabilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faixaaprovacaodesconto',
            name='hash_conjunto',
            field=models.CharField(help_text='Hash canônico ADR-0029 do conjunto completo de faixas (fingerprint).', max_length=200),
        ),
        migrations.AlterField(
            model_name='justificativadecisaodesconto',
            name='pedido',
            field=models.OneToOneField(help_text='1:1 com PedidoAprovacaoDesconto.', on_delete=django.db.models.deletion.PROTECT, related_name='justificativa', to='precificacao.pedidoaprovacaodesconto'),
        ),
        migrations.AlterField(
            model_name='justificativadecisaodesconto',
            name='texto',
            field=models.TextField(help_text='Texto cru da justificativa (AC-PRC-004-3 — exposição ao vendedor).'),
        ),
        migrations.AlterField(
            model_name='parametrosprecificacaotenant',
            name='custo_km',
            field=models.DecimalField(decimal_places=4, help_text='Custo por km de deslocamento (R$/km — US-PRC-006 simulação).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrosprecificacaotenant',
            name='margem_alvo_default',
            field=models.DecimalField(decimal_places=2, help_text='Margem alvo default % (para regras sem margem_alvo_pct explícita).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='parametrosprecificacaotenant',
            name='margem_piso_default',
            field=models.DecimalField(decimal_places=2, help_text='Margem piso default % (para regras sem margem_piso_pct explícita).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='parametrosprecificacaotenant',
            name='pct_comissao_prevista',
            field=models.DecimalField(decimal_places=2, help_text='Comissão prevista % sobre preço de venda (PREVISTA — GATE-PRC-COMISSAO-REAL).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='parametrosprecificacaotenant',
            name='taxa_parcelamento_mensal',
            field=models.DecimalField(decimal_places=2, help_text='Taxa mensal de parcelamento % (US-PRC-006).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pedidoaprovacaodesconto',
            name='contexto_id',
            field=models.UUIDField(blank=True, help_text='ID do documento consumidor (NULL = AVULSO; FK aditiva quando módulo existir).', null=True),
        ),
        migrations.AlterField(
            model_name='pedidoaprovacaodesconto',
            name='decidido_em',
            field=models.DateTimeField(blank=True, help_text='Timestamp da decisão (preenchido junto com decisor_id).', null=True),
        ),
        migrations.AlterField(
            model_name='pedidoaprovacaodesconto',
            name='decisor_id',
            field=models.UUIDField(blank=True, help_text='Quem decidiu (preenchido na decisão; DEVE ser != solicitante — CHECK).', null=True),
        ),
        migrations.AlterField(
            model_name='pedidoaprovacaodesconto',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'solicitado'), ('aprovado', 'aprovado'), ('negado', 'negado')], default='solicitado', help_text='solicitado|aprovado|negado — one-shot via trigger (INV-PRC-APROVACAO-ONE-SHOT).', max_length=12),
        ),
        migrations.AlterField(
            model_name='pedidoaprovacaodesconto',
            name='fingerprint_calculo',
            field=models.CharField(help_text='Hash canônico ADR-0029 de (entradas+refs+pct) — binding aprovação↔cálculo.', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedidoaprovacaodesconto',
            name='snapshot_probatorio',
            field=models.TextField(help_text='JSON canônico ADR-0029 das entradas do cálculo (replay — AC-PRC-002-3).'),
        ),
        migrations.AlterField(
            model_name='perfilcomposicaopreco',
            name='item_servico',
            field=models.ForeignKey(help_text='Item-serviço ao qual este perfil se aplica.', on_delete=django.db.models.deletion.PROTECT, related_name='perfis_composicao', to='produtos_pecas_servicos.itemcatalogo'),
        ),
        migrations.AlterField(
            model_name='regraformacaopreco',
            name='item',
            field=models.ForeignKey(help_text='Item do catálogo para o qual esta regra define formação de preço.', on_delete=django.db.models.deletion.PROTECT, related_name='regras_preco', to='produtos_pecas_servicos.itemcatalogo'),
        ),
        migrations.AlterField(
            model_name='regraformacaopreco',
            name='revogado_em',
            field=models.DateTimeField(blank=True, help_text='One-shot — regra errada sai da exclusion e nunca resolve.', null=True),
        ),
        migrations.AlterField(
            model_name='regraformacaopreco',
            name='vigencia_fim',
            field=models.DateTimeField(blank=True, help_text='One-shot NULL→data (encerramento pela regra sucessora — trigger 0003).', null=True),
        ),
        migrations.AlterField(
            model_name='vinculotabelaprecocliente',
            name='cliente_id',
            field=models.UUIDField(help_text='Pseudônimo art. 12 LGPD; revogado quando Cliente.Anonimizado (ADR-0032).'),
        ),
        migrations.AlterField(
            model_name='vinculotabelaprecocliente',
            name='revogado_em',
            field=models.DateTimeField(blank=True, help_text='Revogado quando Cliente.Anonimizado (ADR-0032).', null=True),
        ),
        migrations.AlterField(
            model_name='vinculotabelaprecocliente',
            name='tabela_id',
            field=models.UUIDField(help_text='FK→tabela_preco.id (PPS); sem FK Django pra evitar cross-app (ADR-0007).'),
        ),
        migrations.AlterField(
            model_name='vinculotabelaprecocliente',
            name='vigencia_fim',
            field=models.DateTimeField(blank=True, help_text='One-shot NULL→data (encerramento).', null=True),
        ),
    ]
