# Generated by Django 5.2.15 on 2026-06-14 22:26
#
# rls-policy: external 0002_rls_policies (RLS v2 FORCE + 4 policies/tabela nas 7 tabelas)
# As 7 tabelas tem tenant_id NOT NULL; o enforcement RLS (INV-TENANT-001/002/003) vive na
# 0002_rls_policies (ENABLE+FORCE + policies) + 0005_grants_app_user (GRANT app_user).

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenant", "0012_aplicar_evento_cgcre_vigencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "cliente_atual_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID do cliente. NULL apos anonimizacao (SET_NULL logico via consumer Cliente.Anonimizado). Sem FK fisica cross-modulo — molde aceite_atividade.",
                        null=True,
                    ),
                ),
                (
                    "cliente_referencia_hash",
                    models.CharField(
                        help_text="HMAC-SHA256 do cliente_id original (ADR-0032). NOT NULL — preservado pos-anonimizacao.",
                        max_length=128,
                    ),
                ),
                (
                    "cliente_key_id",
                    models.CharField(
                        help_text="Versao da chave KMS (rotacao) — formato vN.", max_length=40
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        help_text="Sequencial gap-less por tenant (D-ORC-18 / SerieDocumento). UNIQUE(tenant, numero) na 0004."
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("rascunho", "rascunho"),
                            ("enviado", "enviado"),
                            ("aprovado", "aprovado"),
                            ("aprovado_pendente_os", "aprovado_pendente_os"),
                            ("convertido", "convertido"),
                            ("recusado", "recusado"),
                            ("expirado", "expirado"),
                            ("cancelado", "cancelado"),
                        ],
                        db_index=True,
                        default="rascunho",
                        help_text="Maquina D-ORC-3. `convertido` terminal (INV-ORC-CONVERTIDO-TERMINAL — CHECK na 0004).",
                        max_length=30,
                    ),
                ),
                (
                    "validade_inicio",
                    models.DateTimeField(
                        help_text="Inicio da vigencia da proposta (normalmente = criado_em)."
                    ),
                ),
                (
                    "validade_fim",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fim da vigencia (validade_ate). NULL = sem expiracao automatica.",
                        null=True,
                    ),
                ),
                (
                    "moeda",
                    models.CharField(
                        default="BRL", help_text="ISO 4217. MVP-1: BRL only.", max_length=3
                    ),
                ),
                ("total_bruto_centavos", models.BigIntegerField(default=0)),
                ("descontos_centavos", models.BigIntegerField(default=0)),
                ("impostos_centavos", models.BigIntegerField(default=0)),
                ("liquido_centavos", models.BigIntegerField(default=0)),
                (
                    "comissao_prevista_centavos",
                    models.BigIntegerField(
                        default=0,
                        help_text="Visivel SO com `orcamento.ver_margem` (choke-point server-side — INV-ORC-MARGEM-OFF).",
                    ),
                ),
                (
                    "condicoes_pagamento",
                    models.JSONField(
                        default=dict,
                        help_text="Serializacao do VO CondicoesPagamento (parcelas/forma/dias).",
                    ),
                ),
                ("template_id", models.UUIDField(blank=True, null=True)),
                ("tabela_preco_id", models.UUIDField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "responsavel_id",
                    models.UUIDField(
                        blank=True, help_text="user_id do responsavel comercial.", null=True
                    ),
                ),
                ("chamado_origem_id", models.UUIDField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("criado_por", models.UUIDField(help_text="user_id de quem criou.")),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orcamentos",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orcamento",
                "verbose_name_plural": "Orcamentos",
                "db_table": "orcamento",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="LinkPublico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Opaco urlsafe >=128 bits. UNIQUE global (lookup rapido + colisao impossivel).",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "expira_em",
                    models.DateTimeField(
                        help_text="Expiracao checada no GET e no POST (D-ORC-19)."
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("revogado_em", models.DateTimeField(blank=True, null=True)),
                ("motivo_revogacao", models.CharField(blank=True, max_length=200)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orcamento_links",
                        to="tenant.tenant",
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="orcamentos.orcamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link publico de orcamento",
                "verbose_name_plural": "Links publicos de orcamento",
                "db_table": "orcamento_link_publico",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("tipo", models.CharField(help_text='Ex.: "calibracao_balanca".', max_length=60)),
                (
                    "itens_default",
                    models.JSONField(
                        default=list, help_text="[{catalogo_item_id, quantidade, ...}]"
                    ),
                ),
                (
                    "condicoes_default",
                    models.JSONField(default=dict, help_text="Serializacao de CondicoesPagamento."),
                ),
                (
                    "selo_rbc",
                    models.BooleanField(
                        default=False, help_text="True so em perfil A (gate D-ORC-13)."
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("criado_por", models.UUIDField()),
                ("deletado_em", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("deletado_por", models.UUIDField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orcamento_templates",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de orcamento",
                "verbose_name_plural": "Templates de orcamento",
                "db_table": "template_orcamento",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="VersaoOrcamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("numero_versao", models.PositiveIntegerField(help_text="Comeca em 1.")),
                (
                    "snapshot",
                    models.JSONField(
                        help_text="Foto congelada (itens+condicoes+totais). Imutavel pos-INSERT (trigger WORM)."
                    ),
                ),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("criada_por", models.UUIDField()),
                ("revogado_em", models.DateTimeField(blank=True, null=True)),
                ("motivo_revogacao", models.CharField(blank=True, max_length=200)),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versoes",
                        to="orcamentos.orcamento",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orcamento_versoes",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versao do orcamento",
                "verbose_name_plural": "Versoes do orcamento",
                "db_table": "versao_orcamento",
                "ordering": ["orcamento", "numero_versao"],
            },
        ),
        migrations.CreateModel(
            name="ItemOrcamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "catalogo_item_id",
                    models.UUIDField(
                        db_index=True, help_text="FK logica ao catalogo (produtos_pecas_servicos)."
                    ),
                ),
                (
                    "sequencia",
                    models.PositiveIntegerField(
                        help_text="1-based; rastro item<->atividade (D-ORC-11)."
                    ),
                ),
                (
                    "preco_resolvido",
                    models.JSONField(
                        help_text="Snapshot do PrecoResolvido (item_versao_n, linha_tabela_id, tabela_id, preco, data_referencia, origem_preco). NUNCA margem/custo (INV-ORC-MARGEM-OFF)."
                    ),
                ),
                ("moeda", models.CharField(default="BRL", max_length=3)),
                (
                    "preco_final_centavos",
                    models.BigIntegerField(
                        help_text="Preco unitario final apos desconto (centavos)."
                    ),
                ),
                (
                    "desconto_pct",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Percentual 0..100.", max_digits=5
                    ),
                ),
                ("desconto_valor_centavos", models.BigIntegerField(default=0)),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        help_text="Pode ser fracionaria.",
                        max_digits=12,
                    ),
                ),
                (
                    "total_centavos",
                    models.BigIntegerField(help_text="preco_final * quantidade (centavos)."),
                ),
                (
                    "semaforo",
                    models.CharField(
                        help_text="verde | amarelo | vermelho (precificacao).", max_length=10
                    ),
                ),
                (
                    "descricao_snapshot",
                    models.CharField(help_text="Descricao do item congelada.", max_length=300),
                ),
                (
                    "equipamento_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Preenchido em itens tecnicos (calibracao/manutencao/...). NULL em itens comerciais.",
                        null=True,
                    ),
                ),
                (
                    "tipo_atividade_alvo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("calibracao", "calibracao"),
                            ("manutencao", "manutencao"),
                            ("instalacao", "instalacao"),
                            ("verificacao", "verificacao"),
                            ("vistoria", "vistoria"),
                        ],
                        help_text="Tipo de atividade (itens tecnicos). Vazio em itens comerciais.",
                        max_length=20,
                    ),
                ),
                (
                    "tipo_item_comercial",
                    models.CharField(
                        blank=True,
                        help_text="Tipo do item comercial (deslocamento/taxa/outro) quando equipamento_id is NULL.",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orcamento_itens",
                        to="tenant.tenant",
                    ),
                ),
                (
                    "versao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens",
                        to="orcamentos.versaoorcamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do orcamento",
                "verbose_name_plural": "Itens do orcamento",
                "db_table": "item_orcamento",
                "ordering": ["versao", "sequencia"],
            },
        ),
        migrations.CreateModel(
            name="Aprovacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "aprovado_em",
                    models.DateTimeField(help_text="Timestamp server-side da aprovacao."),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[("interno", "interno"), ("link_publico", "link_publico")],
                        max_length=20,
                    ),
                ),
                (
                    "nome_aprovador_hash",
                    models.CharField(help_text="HMAC(nome, chave_tenant).", max_length=128),
                ),
                (
                    "email_aprovador_hash",
                    models.CharField(help_text="HMAC(email, chave_tenant).", max_length=128),
                ),
                (
                    "lgpd_aceite_versao_termo",
                    models.CharField(help_text='Ex.: "v2026-01".', max_length=40),
                ),
                (
                    "lgpd_aceite_texto_hash",
                    models.CharField(
                        help_text="Hash do texto exibido (prova do consentido).", max_length=128
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(help_text="HMAC(ip_real, chave_servidor).", max_length=128),
                ),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                (
                    "ressalvas_aceitas",
                    models.BooleanField(
                        default=False,
                        help_text="True quando analise=com_ressalva e aprovador confirmou (cl. 7.1.1-d).",
                    ),
                ),
                (
                    "aprovado_por",
                    models.UUIDField(
                        blank=True,
                        help_text="user_id do aprovador interno; NULL em aprovacao publica.",
                        null=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orcamento_aprovacoes",
                        to="tenant.tenant",
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aprovacoes",
                        to="orcamentos.orcamento",
                    ),
                ),
                (
                    "versao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aprovacoes",
                        to="orcamentos.versaoorcamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aprovacao de orcamento",
                "verbose_name_plural": "Aprovacoes de orcamento",
                "db_table": "orcamento_aprovacao",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="AnaliseCriticaOrcamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "perfil_no_evento",
                    models.CharField(
                        help_text="Snapshot do perfil no momento: A|B|C|D.", max_length=1
                    ),
                ),
                (
                    "veredito",
                    models.CharField(
                        choices=[
                            ("aprovada", "aprovada"),
                            ("reprovada", "reprovada"),
                            ("com_ressalva", "com_ressalva"),
                            ("desabilitada", "desabilitada"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "norma_referencia",
                    models.CharField(
                        help_text='Ex.: "ISO/IEC 17025:2017 cl. 7.1.1" (C6).', max_length=60
                    ),
                ),
                (
                    "itens_avaliados",
                    models.JSONField(
                        help_text="Registro probatorio por item (C1): equipamento_id/grandeza/faixa/cmc/procedimento/ressalvas."
                    ),
                ),
                (
                    "snapshot_hash",
                    models.CharField(
                        help_text="Canonicalizacao ADR-0029 — carimbado no envelope.", max_length=64
                    ),
                ),
                (
                    "avaliada_em",
                    models.DateTimeField(help_text="Server-side (nunca client-supplied)."),
                ),
                (
                    "avaliada_por",
                    models.CharField(
                        help_text='user_id str OU "SISTEMA/AUTO:<aprovacao_id>" (C5).',
                        max_length=80,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orcamento_analises",
                        to="tenant.tenant",
                    ),
                ),
                (
                    "orcamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analises_criticas",
                        to="orcamentos.orcamento",
                    ),
                ),
                (
                    "versao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analises_criticas",
                        to="orcamentos.versaoorcamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analise critica de orcamento",
                "verbose_name_plural": "Analises criticas de orcamento",
                "db_table": "analise_critica_orcamento",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddIndex(
            model_name="orcamento",
            index=models.Index(fields=["tenant", "estado"], name="ix_orc_tenant_estado"),
        ),
        migrations.AddIndex(
            model_name="orcamento",
            index=models.Index(fields=["tenant", "cliente_atual_id"], name="ix_orc_tenant_cliente"),
        ),
        migrations.AddIndex(
            model_name="orcamento",
            index=models.Index(fields=["tenant", "-criado_em"], name="ix_orc_tenant_criado"),
        ),
        migrations.AddIndex(
            model_name="linkpublico",
            index=models.Index(fields=["tenant", "orcamento"], name="ix_link_tenant_orc"),
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(fields=["tenant", "nome"], name="ix_template_tenant_nome"),
        ),
        migrations.AddIndex(
            model_name="versaoorcamento",
            index=models.Index(fields=["tenant", "orcamento"], name="ix_versao_tenant_orc"),
        ),
        migrations.AddConstraint(
            model_name="versaoorcamento",
            constraint=models.UniqueConstraint(
                fields=("orcamento", "numero_versao"), name="uq_versao_orc_numero"
            ),
        ),
        migrations.AddIndex(
            model_name="itemorcamento",
            index=models.Index(fields=["tenant", "versao"], name="ix_item_tenant_versao"),
        ),
        migrations.AddIndex(
            model_name="itemorcamento",
            index=models.Index(fields=["versao", "sequencia"], name="ix_item_versao_seq"),
        ),
        migrations.AddIndex(
            model_name="aprovacao",
            index=models.Index(fields=["tenant", "orcamento"], name="ix_aprov_tenant_orc"),
        ),
        migrations.AddIndex(
            model_name="analisecriticaorcamento",
            index=models.Index(fields=["tenant", "orcamento"], name="ix_analise_tenant_orc"),
        ),
    ]
