# Generated by Django 5.2.15 on 2026-06-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caixa_tecnico", "0006_seed_authz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adiantamentocaixa",
            name="aprovado_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento da aprovação (None se ainda não aprovado).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="adiantamentocaixa",
            name="aprovado_por_id",
            field=models.UUIDField(
                blank=True,
                help_text="ID concreto do usuário que aprovou (ato gerencial rastreável).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="adiantamentocaixa",
            name="entregue_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento da entrega (None se ainda não entregue — estado terminal).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="adiantamentocaixa",
            name="motivo_recusa",
            field=models.TextField(
                blank=True, default="", help_text="Motivo da recusa (obrigatório quando recusado)."
            ),
        ),
        migrations.AlterField(
            model_name="caixatecnico",
            name="revision",
            field=models.IntegerField(
                default=0,
                help_text="Contador de transições (observabilidade / OCC). Bumpa por F('revision')+1.",
            ),
        ),
        migrations.AlterField(
            model_name="consentimentogpscolaborador",
            name="colaborador_referencia_hash",
            field=models.CharField(
                help_text="HMAC do colaborador — pseudônimo na trilha (ADR-0032). Imutável, NOT NULL.",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="consentimentogpscolaborador",
            name="revogado_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento da revogação do consentimento (one-shot — sem re-ativação nesta linha). Vigência canônica ADR-0030.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="despesacaixa",
            name="acima_limite",
            field=models.BooleanField(
                default=False,
                help_text="Flag calculada: despesa acima do limite configurado (D-CT-9 — não bloqueia).",
            ),
        ),
        migrations.AlterField(
            model_name="despesacaixa",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("combustivel", "combustivel"),
                    ("alimentacao", "alimentacao"),
                    ("pedagio", "pedagio"),
                    ("hospedagem", "hospedagem"),
                    ("peca", "peca"),
                    ("deslocamento", "deslocamento"),
                ],
                help_text="Categoria da despesa (D-CT-9 / US-CT-005).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="despesacaixa",
            name="foto_hash",
            field=models.CharField(
                help_text="HMAC-SHA256 dos bytes pós-EXIF-strip (content-address por tenant — D-CT-4/ADR-0064).",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="despesacaixa",
            name="km_percorridos",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Km rodados (obrigatório quando categoria=deslocamento — D-CT-9).",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="despesacaixa",
            name="motivo_rejeicao",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Motivo da rejeição (obrigatório quando rejeitada).",
            ),
        ),
        migrations.AlterField(
            model_name="politicacaixa",
            name="alcada_aprovacao",
            field=models.BigIntegerField(
                blank=True,
                help_text="Centavos; adiantamentos acima disso exigem aprovação explícita (D-CT-7/D-CT-9).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="politicacaixa",
            name="exige_gps",
            field=models.BooleanField(
                default=False,
                help_text="Tenant exige GPS nas despesas de deslocamento (D-CT-6 / D-CT-9).",
            ),
        ),
        migrations.AlterField(
            model_name="politicacaixa",
            name="limite_por_categoria",
            field=models.JSONField(
                blank=True,
                help_text="Mapa {categoria: centavos} de limite por categoria. NULL = sem limite (D-CT-9).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="politicacaixa",
            name="tarifa_km",
            field=models.BigIntegerField(
                blank=True,
                help_text="Tarifa por km rodado em centavos (D-CT-9). NULL = km automático desabilitado.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="prestacaocontascaixa",
            name="saldo_final",
            field=models.BigIntegerField(
                help_text="Saldo final = total_adiantado - total_despesas_validadas (centavos). WORM."
            ),
        ),
    ]
