# Generated by Django 5.2.14 on 2026-05-18 03:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Identificador semantico (ex: 'usuario.criado', 'certificado.emitido').",
                        max_length=100,
                    ),
                ),
                (
                    "resource_summary",
                    models.CharField(
                        help_text="Resumo legivel do recurso afetado (ex: 'Certificado #123 / Tenant slug').",
                        max_length=255,
                    ),
                ),
                (
                    "payload_jsonb",
                    models.JSONField(
                        help_text="Payload completo da acao. Canonicalizado antes de calcular hash."
                    ),
                ),
                (
                    "hash_anterior",
                    models.CharField(
                        blank=True,
                        help_text="sha256 do hash_atual da linha imediatamente anterior. NULL = primeira linha.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "hash_atual",
                    models.CharField(
                        help_text="sha256(hash_anterior || payload_canonicalizado). Calculado no Marco 4.",
                        max_length=64,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = evento global (provisioning de tenant, manutencao).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auditoria",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linha de auditoria",
                "verbose_name_plural": "Auditoria (trilha imutavel)",
                "db_table": "auditoria",
                "ordering": ["-timestamp"],
            },
        ),
    ]
