# Generated by Django 5.2.14 on 2026-05-18 13:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0003_trigger_anti_mutation"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcessoDadosCliente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("usuario_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("cliente_id", models.UUIDField(db_index=True)),
                (
                    "finalidade",
                    models.CharField(
                        choices=[
                            ("atendimento_pos_venda", "Atendimento Pos Venda"),
                            ("preparar_orcamento", "Preparar Orcamento"),
                            ("executar_os", "Executar Os"),
                            ("emitir_documento_fiscal", "Emitir Documento Fiscal"),
                            ("cobranca_inadimplencia", "Cobranca Inadimplencia"),
                            ("auditoria_interna", "Auditoria Interna"),
                            ("atendimento_lgpd_titular", "Atendimento Lgpd Titular"),
                            ("investigacao_incidente", "Investigacao Incidente"),
                        ],
                        help_text="Enum cravado pelo advogado (R2). CHECK constraint na migration.",
                        max_length=40,
                    ),
                ),
                (
                    "categoria_dado_acessado",
                    models.CharField(
                        choices=[
                            ("pii_identificadora", "PII identificadora (nome, CPF/CNPJ, contato)"),
                            ("pii_sensivel", "PII sensivel (LGPD art. 5 II)"),
                            ("dado_fiscal", "Dado fiscal (NF-e, retencao)"),
                            ("dado_regulatorio", "Dado regulatorio (certificado ISO 17025)"),
                            ("metadado", "Metadado (sem PII — UUIDs, timestamps)"),
                        ],
                        default="pii_identificadora",
                        max_length=30,
                    ),
                ),
                (
                    "recurso",
                    models.JSONField(
                        default=dict, help_text="UUIDs + metadados (sem PII cru) — R1 advogado."
                    ),
                ),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Acesso a dados de cliente (INV-013)",
                "verbose_name_plural": "Acessos a dados de cliente",
                "db_table": "acessos_dados_cliente",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "cliente_id", "-timestamp"],
                        name="ix_acessos_tenant_cli_ts",
                    ),
                    models.Index(
                        fields=["tenant_id", "usuario_id", "-timestamp"],
                        name="ix_acessos_tenant_user_ts",
                    ),
                ],
            },
        ),
    ]
