# Generated by Django 5.2.14 on 2026-05-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0017_admin_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaccess',
            name='eh_break_glass',
            field=models.BooleanField(db_index=True, default=False, help_text='True quando login via conta admin-recovery (US-FC1-006).'),
        ),
        migrations.AlterField(
            model_name='adminaccess',
            name='motivo_negacao',
            field=models.CharField(blank=True, default='', help_text="Valores estaveis (sem oracle): 'anonimo', 'ip_fora_allowlist', 'mfa_nao_verificado', 'mfa_janela_expirada', 'rate_limit', 'session_rebind_mismatch'. Vazio = sucesso.", max_length=64),
        ),
        migrations.AlterField(
            model_name='adminaccess',
            name='tombstoned_em',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Soft-delete apos retencao 24m. Linha continua existindo (audit imutavel) mas user_agent_hash zerado.', null=True),
        ),
        migrations.AlterField(
            model_name='adminaccess',
            name='usuario_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='NULL quando request anonimo no /admin/* OU apos pseudonimizacao 90d.', null=True),
        ),
        migrations.AlterField(
            model_name='adminaccess',
            name='usuario_id_hash',
            field=models.CharField(blank=True, default='', help_text='HMAC do usuario_id apos 90d (LGPD art. 18 + audit imutavel).', max_length=64),
        ),
    ]
