# Generated by Django 5.2.14 on 2026-05-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0019_perfil_no_evento_san_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='perfil_no_evento',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Snapshot perfil regulatorio tenant no momento do INSERT (ADR-0067). NULLABLE durante backfill.', max_length=1, null=True),
        ),
    ]
