"""US-EQP-007 / T-EQP-061+062+065: ResponsavelTecnicoTenant + RTCompetencia.

Coverage:
- INV-TENANT-001/002/003: RLS pattern v2 (4 policies em cada tabela).
- INV-EQP-RT-001 (P-EQP-R10): EXCLUDE USING GIST em RTCompetencia
  (tenant_id WITH =, grandeza WITH =, daterange(declarado_em,
  vigente_ate, '[)') WITH &&) — apenas 1 competencia por (tenant,
  grandeza) em qualquer janela temporal. Requer extensao btree_gist.
- AC-EQP-007-5: trigger `rt_imutavel_pos_insert` permite UPDATE
  EXCLUSIVAMENTE em encerrado_em/encerrado_por/motivo_encerramento/
  motivo_detalhe; demais campos imutaveis pos-INSERT. Apos
  encerrado_em NOT NULL a linha vira totalmente imutavel.

# tests-coverage: tests/test_responsavel_tecnico_us_eqp_007.py
"""

# Generated by Django 5.2.14 on 2026-05-21 13:54 (depois aumentada manualmente)

import uuid

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

FORWARD_RLS_TRIGGER_GIST = """
-- =============================================================
-- Extensao btree_gist (necessaria para EXCLUDE GIST combinando =
-- em colunas escalares + && em daterange). Idempotente.
-- =============================================================
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- =============================================================
-- RLS pattern v2 (ADR-0002 §6) — ResponsavelTecnicoTenant
-- =============================================================
ALTER TABLE responsavel_tecnico_tenant ENABLE ROW LEVEL SECURITY;
ALTER TABLE responsavel_tecnico_tenant FORCE ROW LEVEL SECURITY;

CREATE POLICY rt_tenant_isolation_select ON responsavel_tecnico_tenant
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY rt_tenant_isolation_update ON responsavel_tecnico_tenant
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY rt_tenant_isolation_delete ON responsavel_tecnico_tenant
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY rt_tenant_isolation_insert ON responsavel_tecnico_tenant
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- =============================================================
-- RLS pattern v2 — RTCompetencia
-- =============================================================
ALTER TABLE responsavel_tecnico_competencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE responsavel_tecnico_competencia FORCE ROW LEVEL SECURITY;

CREATE POLICY rt_comp_tenant_isolation_select ON responsavel_tecnico_competencia
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY rt_comp_tenant_isolation_update ON responsavel_tecnico_competencia
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY rt_comp_tenant_isolation_delete ON responsavel_tecnico_competencia
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY rt_comp_tenant_isolation_insert ON responsavel_tecnico_competencia
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- =============================================================
-- INV-EQP-RT-001 (P-EQP-R10): EXCLUDE GIST — sem sobreposicao
-- temporal por (tenant, grandeza).
--
-- daterange com vigente_ate=NULL torna-se [declarado_em, infinity) —
-- coalesce explicito mantem semantica de "vigencia indefinida".
-- =============================================================
ALTER TABLE responsavel_tecnico_competencia
    ADD CONSTRAINT rt_competencia_sem_sobreposicao_temporal
    EXCLUDE USING GIST (
        tenant_id WITH =,
        grandeza WITH =,
        daterange(declarado_em, COALESCE(vigente_ate, 'infinity'::date), '[)') WITH &&
    );

-- =============================================================
-- AC-EQP-007-5: trigger `rt_imutavel_pos_insert`
--
-- 1) Apos encerrado_em NOT NULL, qualquer UPDATE e bloqueado
--    (linha totalmente imutavel).
-- 2) Enquanto encerrado_em IS NULL, somente os 4 campos de
--    encerramento podem mudar (transicao unica ativo -> encerrado).
-- =============================================================
CREATE OR REPLACE FUNCTION rt_imutavel_pos_insert_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF OLD.encerrado_em IS NOT NULL THEN
        RAISE EXCEPTION 'AC-EQP-007-5: RT % ja encerrado em %, linha imutavel',
            OLD.id, OLD.encerrado_em;
    END IF;
    IF OLD.tenant_id IS DISTINCT FROM NEW.tenant_id THEN
        RAISE EXCEPTION 'INV-TENANT-001: tenant_id do RT imutavel';
    END IF;
    IF OLD.usuario_id IS DISTINCT FROM NEW.usuario_id THEN
        RAISE EXCEPTION 'AC-EQP-007-5: usuario_id do RT imutavel';
    END IF;
    IF OLD.nome_completo_snapshot IS DISTINCT FROM NEW.nome_completo_snapshot THEN
        RAISE EXCEPTION 'AC-EQP-007-5: nome_completo_snapshot imutavel';
    END IF;
    IF OLD.cpf_hash IS DISTINCT FROM NEW.cpf_hash THEN
        RAISE EXCEPTION 'AC-EQP-007-5: cpf_hash imutavel';
    END IF;
    IF OLD.formacao_academica IS DISTINCT FROM NEW.formacao_academica THEN
        RAISE EXCEPTION 'AC-EQP-007-5: formacao_academica imutavel';
    END IF;
    IF OLD.registro_profissional_tipo IS DISTINCT FROM NEW.registro_profissional_tipo THEN
        RAISE EXCEPTION 'AC-EQP-007-5: registro_profissional_tipo imutavel';
    END IF;
    IF OLD.registro_profissional_numero IS DISTINCT FROM NEW.registro_profissional_numero THEN
        RAISE EXCEPTION 'AC-EQP-007-5: registro_profissional_numero imutavel';
    END IF;
    IF OLD.registro_profissional_descricao_outro IS DISTINCT FROM NEW.registro_profissional_descricao_outro THEN
        RAISE EXCEPTION 'AC-EQP-007-5: registro_profissional_descricao_outro imutavel';
    END IF;
    IF OLD.data_inicio_vigencia IS DISTINCT FROM NEW.data_inicio_vigencia THEN
        RAISE EXCEPTION 'AC-EQP-007-5: data_inicio_vigencia imutavel';
    END IF;
    IF OLD.data_fim_vigencia IS DISTINCT FROM NEW.data_fim_vigencia THEN
        RAISE EXCEPTION 'AC-EQP-007-5: data_fim_vigencia imutavel';
    END IF;
    IF OLD.criado_em IS DISTINCT FROM NEW.criado_em THEN
        RAISE EXCEPTION 'AUDIT: criado_em imutavel';
    END IF;
    IF OLD.criado_por_id IS DISTINCT FROM NEW.criado_por_id THEN
        RAISE EXCEPTION 'AC-EQP-007-5: criado_por imutavel';
    END IF;
    -- Garante que encerramento e ATOMICO (todos os 4 campos juntos).
    IF NEW.encerrado_em IS NOT NULL THEN
        IF NEW.encerrado_por_id IS NULL THEN
            RAISE EXCEPTION 'AC-EQP-007-5: encerrado_por obrigatorio quando encerrado_em definido';
        END IF;
        IF NEW.motivo_encerramento = '' THEN
            RAISE EXCEPTION 'AC-EQP-007-5: motivo_encerramento obrigatorio quando encerrado_em definido';
        END IF;
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER rt_imutavel_pos_insert_trg
    BEFORE UPDATE ON responsavel_tecnico_tenant
    FOR EACH ROW
    EXECUTE FUNCTION rt_imutavel_pos_insert_check();
"""

REVERSE_RLS_TRIGGER_GIST = """
DROP TRIGGER IF EXISTS rt_imutavel_pos_insert_trg ON responsavel_tecnico_tenant;
DROP FUNCTION IF EXISTS rt_imutavel_pos_insert_check();
ALTER TABLE responsavel_tecnico_competencia
    DROP CONSTRAINT IF EXISTS rt_competencia_sem_sobreposicao_temporal;
DROP POLICY IF EXISTS rt_comp_tenant_isolation_insert ON responsavel_tecnico_competencia;
DROP POLICY IF EXISTS rt_comp_tenant_isolation_delete ON responsavel_tecnico_competencia;
DROP POLICY IF EXISTS rt_comp_tenant_isolation_update ON responsavel_tecnico_competencia;
DROP POLICY IF EXISTS rt_comp_tenant_isolation_select ON responsavel_tecnico_competencia;
ALTER TABLE responsavel_tecnico_competencia DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rt_tenant_isolation_insert ON responsavel_tecnico_tenant;
DROP POLICY IF EXISTS rt_tenant_isolation_delete ON responsavel_tecnico_tenant;
DROP POLICY IF EXISTS rt_tenant_isolation_update ON responsavel_tecnico_tenant;
DROP POLICY IF EXISTS rt_tenant_isolation_select ON responsavel_tecnico_tenant;
ALTER TABLE responsavel_tecnico_tenant DISABLE ROW LEVEL SECURITY;
-- btree_gist nao removida (compartilhada com outras tabelas potenciais).
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsavelTecnicoTenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo_snapshot', models.CharField(help_text='Nome do RT no momento do cadastro (CGCRE — escopo de acreditacao tem o nome PUBLICO). Snapshot imutavel.', max_length=200)),
                ('cpf_hash', models.CharField(help_text='HMAC-SHA256(cpf, salt_tenant) — pseudonimizacao. CPF cru NUNCA persiste; comparacao via hash.', max_length=64)),
                ('formacao_academica', models.CharField(help_text="Ex: 'Engenharia Mecanica - UFMG - 2010'.", max_length=200)),
                ('registro_profissional_tipo', models.CharField(choices=[('CREA', 'CREA — Engenharia'), ('CRQ', 'CRQ — Quimica'), ('CRF', 'CRF — Farmacia'), ('OUTRO', 'Outro conselho profissional')], max_length=10)),
                ('registro_profissional_numero', models.CharField(help_text="Numero do registro (ex: 'CREA-MG 123.456/D').", max_length=40)),
                ('registro_profissional_descricao_outro', models.CharField(blank=True, default='', help_text="Quando tipo=OUTRO, descrever o conselho (ex: 'CFB - Biologia'). Vazio quando tipo != OUTRO.", max_length=80)),
                ('data_inicio_vigencia', models.DateField(help_text='Data efetiva em que o RT assumiu.')),
                ('data_fim_vigencia', models.DateField(blank=True, help_text='Data planejada de fim (NULL = vigencia indeterminada). NAO e o mesmo que `encerrado_em` (encerramento real do vinculo).', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('encerrado_em', models.DateTimeField(blank=True, help_text='Timestamp de encerramento (UNICA mutacao permitida).', null=True)),
                ('motivo_encerramento', models.CharField(blank=True, choices=[('desligamento', 'Desligamento do profissional'), ('substituicao', 'Substituicao por novo RT'), ('aposentadoria', 'Aposentadoria'), ('cessacao_operacoes', 'Cessacao de operacoes do tenant'), ('outro', 'Outro (vide motivo_detalhe)')], default='', help_text='Vazio enquanto vigente; obrigatorio ao encerrar.', max_length=30)),
                ('motivo_detalhe', models.CharField(blank=True, default='', help_text='Texto livre quando motivo=OUTRO. Anti-PII (regex valida).', max_length=500)),
                ('criado_por', models.ForeignKey(help_text='Quem cadastrou o RT (autoria).', on_delete=django.db.models.deletion.PROTECT, related_name='rt_cadastrou', to=settings.AUTH_USER_MODEL)),
                ('encerrado_por', models.ForeignKey(blank=True, help_text='Quem efetuou o encerramento.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rt_encerrou', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Denormalizado pra RLS (mesmo padrao Marco 1).', on_delete=django.db.models.deletion.PROTECT, related_name='responsaveis_tecnicos', to='tenant.tenant')),
                ('usuario', models.ForeignKey(help_text='Usuario do tenant que e o RT. Vinculacao logica — o usuario pode logar como qualquer perfil; RT e papel separado.', on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_rt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsavel Tecnico do tenant',
                'verbose_name_plural': 'Responsaveis Tecnicos do tenant',
                'db_table': 'responsavel_tecnico_tenant',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RTCompetencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grandeza', models.CharField(help_text="Grandeza acreditada (massa, volume, temperatura, dimensional, etc.). Texto livre — NIT-DICLA-016 lista grandezas; whitelist Wave A. Lowercase + underscore (ex: 'massa', 'temperatura_ar').", max_length=80)),
                ('carta_competencia_anexo_id', models.UUIDField(blank=True, help_text='Anexo com carta de competencia formal. Opcional aqui; alguns escopos exigem (validacao na camada de servico/Wave A).', null=True)),
                ('declarado_em', models.DateField(help_text='Data de inicio da vigencia da competencia.')),
                ('vigente_ate', models.DateField(blank=True, help_text='Fim da vigencia (NULL = indefinido).', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rt_competencia_declarou', to=settings.AUTH_USER_MODEL)),
                ('rt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competencias', to='responsavel_tecnico.responsaveltecnicotenant')),
                ('tenant', models.ForeignKey(help_text='Denormalizado pra RLS + EXCLUDE GIST.', on_delete=django.db.models.deletion.PROTECT, related_name='rt_competencias', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Competencia declarada de RT',
                'verbose_name_plural': 'Competencias declaradas de RT',
                'db_table': 'responsavel_tecnico_competencia',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='responsaveltecnicotenant',
            index=models.Index(fields=['tenant', 'encerrado_em'], name='responsavel_tenant__499a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='responsaveltecnicotenant',
            index=models.Index(fields=['usuario'], name='responsavel_usuario_7a8e95_idx'),
        ),
        migrations.AddIndex(
            model_name='rtcompetencia',
            index=models.Index(fields=['tenant', 'grandeza', 'vigente_ate'], name='responsavel_tenant__2ec18b_idx'),
        ),
        migrations.AddIndex(
            model_name='rtcompetencia',
            index=models.Index(fields=['rt'], name='responsavel_rt_id_ec8a8c_idx'),
        ),
        migrations.RunSQL(sql=FORWARD_RLS_TRIGGER_GIST, reverse_sql=REVERSE_RLS_TRIGGER_GIST),
    ]
