# Generated by Django 5.2.14 on 2026-05-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsavel_tecnico', '0002_seed_authz_acoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsaveltecnicotenant',
            name='cpf_hash',
            field=models.CharField(help_text='HMAC-SHA256(cpf, salt_tenant) prefixado por key_id (formato `vN:64hex`). CPF cru NUNCA persiste; comparacao via hash.', max_length=80),
        ),
    ]
