# Generated by Django 5.2.14 on 2026-05-18 03:33

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador url-safe (ex: 'balancas-solution').", unique=True
                    ),
                ),
                ("nome_fantasia", models.CharField(max_length=200)),
                (
                    "plano",
                    models.CharField(
                        default="placeholder",
                        help_text="Plano comercial. Modelo composicional real entra Wave B (ADR-0013).",
                        max_length=50,
                    ),
                ),
                (
                    "status_lifecycle",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("suspenso", "Suspenso (inadimplencia ou desativacao temporaria)"),
                            ("cancelado", "Cancelado (encerrado pelo cliente)"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenants",
                "ordering": ["nome_fantasia"],
            },
        ),
    ]
