# Generated by Django 5.2.14 on 2026-05-27 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_rebaixar_voluntario_function'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tenantperfilhistorico',
            name='tph_tenant_recente_idx',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='acreditacao_cgcre_numero',
            field=models.CharField(blank=True, help_text="Numero RBC formato 'CRL NNNN' ou 'CRL NNNN-NN'. Preenchido apenas quando perfil_regulatorio='A'. Validacao regex em Tenant.clean().", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='acreditacao_suspensa_ate',
            field=models.DateField(blank=True, help_text='Data prevista de fim da suspensao temporaria CGCRE. Cancelamento definitivo usa direcao=CANCELAMENTO_CGCRE.', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='acreditacao_suspensa_em',
            field=models.DateField(blank=True, help_text="Data inicio da suspensao temporaria CGCRE (NIT-DICLA-005 §7.4). Preserva perfil='A' mas predicate tenant_perfil_e({'A'}) retorna False enquanto today < acreditacao_suspensa_ate.", null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='ilac_mra_aderido',
            field=models.BooleanField(default=False, help_text='Se True, lab esta no ILAC-MRA (reconhecimento internacional). Template de certificado A com selo ILAC-MRA so e permitido se True (hook template-ilac-mra-coerencia em Sprint 5 Wave A). R9 plan.md.'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='perfil_regulatorio',
            field=models.CharField(choices=[('A', 'A — Acreditado RBC/CGCRE'), ('B', 'B — Rastreavel nao-acreditado'), ('C', 'C — Em preparacao para acreditar'), ('D', 'D — Comercial puro (sem ISO 17025)')], help_text='Perfil regulatorio do tenant (ADR-0067 — INV-TENANT-PERFIL-002). NOT NULL pos-migration 0005. Mutavel apenas via funcoes SECURITY DEFINER. Hook `tenant-perfil-imutavel-check` bloqueia qualquer migration que tente UPDATE direto.', max_length=1),
        ),
        migrations.AlterField(
            model_name='tenantperfilhistorico',
            name='assinatura_a3_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantperfilhistorico',
            name='auditor_cgcre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tenantperfilhistorico',
            name='certificado_acreditacao_documento_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantperfilhistorico',
            name='evento_origem_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantperfilhistorico',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenantperfilhistorico',
            name='motivo',
            field=models.TextField(help_text='Justificativa textual. Min 100 chars (CHECK constraint). Sanitizada via sanitizar_payload_audit antes do INSERT (A8 plan.md).'),
        ),
        migrations.AlterField(
            model_name='tenantperfilhistorico',
            name='perfil_anterior',
            field=models.CharField(blank=True, choices=[('A', 'A — Acreditado RBC/CGCRE'), ('B', 'B — Rastreavel nao-acreditado'), ('C', 'C — Em preparacao para acreditar'), ('D', 'D — Comercial puro (sem ISO 17025)')], help_text='Perfil antes. NULL apenas em direcao=provisionamento_inicial.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tenantperfilhistorico',
            name='perfil_novo',
            field=models.CharField(choices=[('A', 'A — Acreditado RBC/CGCRE'), ('B', 'B — Rastreavel nao-acreditado'), ('C', 'C — Em preparacao para acreditar'), ('D', 'D — Comercial puro (sem ISO 17025)')], help_text='Perfil apos a mudanca. NOT NULL.', max_length=1),
        ),
        migrations.AlterField(
            model_name='tenantperfilhistorico',
            name='registrado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tenantperfilhistorico',
            name='registrado_por_usuario_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
