# Generated by Django 5.2.14 on 2026-06-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_remove_tenantperfilhistorico_tph_tenant_recente_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='acreditacao_vigencia_fim',
            field=models.DateField(blank=True, help_text='Data de validade da acreditacao CGCRE (INV-CER-CGCRE-VIG-001). Preenchida apenas em perfil A. A emissao so classifica ponto como RBC quando a acreditacao esta vigente nesta data (> data_de_emissao). NULL = fail-open lazy (campo novo; GATE-CER-CGCRE-VIG-DATA-POPULAR Wave A torna o bloqueio por vencimento efetivo quando populado).', null=True),
        ),
    ]
