# Generated by Django 5.2.14 on 2026-05-18 03:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        help_text="Modulo dono da flag (ex: 'calibracao', 'fiscal', 'app-tecnico').",
                        max_length=50,
                    ),
                ),
                (
                    "feature_key",
                    models.CharField(
                        help_text="Identificador da feature (ex: 'NFS-e-automatico', 'assinatura-a3').",
                        max_length=100,
                    ),
                ),
                ("ativo", models.BooleanField(default=False)),
                (
                    "fonte",
                    models.CharField(
                        choices=[
                            ("plano", "Plano comercial (deriva do plano do tenant)"),
                            ("override_manual", "Override manual (suporte habilitou pontualmente)"),
                            ("a_b_test", "Experimento A/B"),
                            ("global", "Flag global do produto (tenant_id NULL)"),
                        ],
                        default="plano",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL = flag global (todos os tenants).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flags",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature flag",
                "verbose_name_plural": "Feature flags",
                "db_table": "feature_flags",
                "ordering": ["modulo", "feature_key"],
                "indexes": [
                    models.Index(fields=["tenant", "modulo"], name="ix_flag_tenant_modulo")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "modulo", "feature_key"),
                        name="uq_feature_flag_tenant_modulo_key",
                    )
                ],
            },
        ),
    ]
