# Generated by Django 5.2.14 on 2026-05-21 08:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0023_us_cli_003_pii_regularizacao"),
        ("tenant", "0002_tenant_bloqueio_automatico_inadimplencia_habilitado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        help_text="TAG operacional do equipamento. Unica por tenant (INV-049).",
                        max_length=50,
                    ),
                ),
                (
                    "numero_serie",
                    models.CharField(
                        help_text="Numero de serie do fabricante. Imutavel pos-emissao de cert (INV-025).",
                        max_length=100,
                    ),
                ),
                (
                    "fabricante",
                    models.CharField(
                        help_text="Imutavel pos-emissao de cert (INV-025).", max_length=100
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        help_text="Versionavel pos-cert (US-EQP-002 motivo_mudanca).",
                        max_length=100,
                    ),
                ),
                (
                    "faixa",
                    models.CharField(blank=True, help_text="Versionavel pos-cert.", max_length=100),
                ),
                (
                    "classe",
                    models.CharField(blank=True, help_text="Versionavel pos-cert.", max_length=100),
                ),
                (
                    "localizacao_fisica",
                    models.CharField(
                        blank=True,
                        help_text="Onde o equipamento esta fisicamente. Anti-PII (INV-EQP-LOC-001) via validator no serializer/clean — proibido CPF/email/nomes.",
                        max_length=200,
                    ),
                ),
                (
                    "perfil_tenant_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot do perfil do tenant no momento do cadastro. Imutavel via trigger PG BEFORE UPDATE. Excecao unica via funcao SECURITY DEFINER `promover_perfil_equipamento_snapshot` (D->A only).",
                    ),
                ),
                (
                    "snapshot_schema_version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Versao semantica do schema do snapshot. Imutavel junto com o snapshot. Permite parser evoluir sem quebrar snapshots antigos.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("inativo_temporario", "Inativo temporario (manutencao)"),
                            ("aposentado", "Aposentado (fim de vida util)"),
                            ("em_calibracao_lab", "Em calibracao no laboratorio"),
                            ("sucata", "Sucata (terminal)"),
                            ("orfao_pendente_decisao", "Orfao pendente de decisao"),
                            ("extraviado", "Extraviado"),
                        ],
                        default="ativo",
                        help_text="Estado operacional. Maquina de transicao via trigger PG `bloquear_transicao_status_equipamento_invalida` (AC-EQP-006-3a).",
                        max_length=30,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "deletado_em",
                    models.DateTimeField(
                        blank=True,
                        help_text="Soft-delete; UNIQUE INV-049 parcial WHERE deletado_em IS NULL.",
                        null=True,
                    ),
                ),
                (
                    "cliente_atual",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Cliente atual proprietario. db_constraint=False (RLS); ON DELETE SET NULL via trigger PG; status=orfao_pendente_decisao se eliminado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipamentos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipamentos",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipamento",
                "verbose_name_plural": "Equipamentos",
                "db_table": "equipamentos",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"], name="equipamento_tenant__814a59_idx"
                    ),
                    models.Index(
                        fields=["tenant", "cliente_atual"], name="equipamento_tenant__632970_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deletado_em__isnull", True)),
                        fields=("tenant", "tag"),
                        name="uq_equipamentos_tag_por_tenant_ativos",
                    )
                ],
            },
        ),
    ]
