"""Tabela `equipamentos_qrcode` + RLS + trigger imutabilidade (T-EQP-006c / SEC-QR-001).

Coverage:
- INV-TENANT-001/002/003: RLS policies SELECT/UPDATE/DELETE/INSERT (pattern v2).
- INV-EQP-QR-NUNCA-RECOMPUTA (P-EQP-T1): tabela e a fonte de verdade pra
  verificacao; trigger `qrcode_imutavel_pos_insert` bloqueia UPDATE em
  todos os campos exceto `revogado_em`.
- INV-051 + SEC-QR-001: hash UNIQUE garante deteccao de bug de colisao
  (cripto-impossivel com HMAC-SHA256 com chave de servidor — mas
  defesa em profundidade nunca custa).

# tests-coverage: tests/regressao/test_sec_qr_001_hmac_versionado.py
"""

# Generated by Django 5.2.14 on 2026-05-21 09:09

import uuid

import django.db.models.deletion
from django.db import migrations, models

FORWARD_RLS_TRIGGER = """
-- =============================================================
-- RLS pattern v2 (ADR-0002 §6) - igual equipamentos
-- =============================================================
ALTER TABLE equipamentos_qrcode ENABLE ROW LEVEL SECURITY;
ALTER TABLE equipamentos_qrcode FORCE ROW LEVEL SECURITY;

CREATE POLICY qrcode_tenant_isolation_select ON equipamentos_qrcode
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY qrcode_tenant_isolation_update ON equipamentos_qrcode
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY qrcode_tenant_isolation_delete ON equipamentos_qrcode
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY qrcode_tenant_isolation_insert ON equipamentos_qrcode
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- =============================================================
-- INV-EQP-QR-NUNCA-RECOMPUTA - trigger imutabilidade pos-INSERT
--
-- Apenas `revogado_em` pode mudar pos-criacao (soft-revoke por
-- re-emissao). Bloqueia UPDATE em hash/equipamento/tenant/emitido_em/
-- criado_em - tentativas de "recomputar" o hash via UPDATE silencioso
-- ficam impossiveis.
-- =============================================================
CREATE OR REPLACE FUNCTION qrcode_imutavel_pos_insert_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF OLD.hash IS DISTINCT FROM NEW.hash THEN
        RAISE EXCEPTION 'INV-EQP-QR-NUNCA-RECOMPUTA: hash do QRCode imutavel pos-INSERT';
    END IF;
    IF OLD.equipamento_id IS DISTINCT FROM NEW.equipamento_id THEN
        RAISE EXCEPTION 'SEC-QR-001: equipamento_id do QRCode imutavel pos-INSERT';
    END IF;
    IF OLD.tenant_id IS DISTINCT FROM NEW.tenant_id THEN
        RAISE EXCEPTION 'INV-TENANT-001: tenant_id do QRCode imutavel pos-INSERT';
    END IF;
    IF OLD.emitido_em IS DISTINCT FROM NEW.emitido_em THEN
        RAISE EXCEPTION 'SEC-QR-001: emitido_em do QRCode imutavel pos-INSERT (compoe payload HMAC)';
    END IF;
    IF OLD.criado_em IS DISTINCT FROM NEW.criado_em THEN
        RAISE EXCEPTION 'AUDIT: criado_em do QRCode imutavel pos-INSERT';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER qrcode_imutavel_pos_insert_trg
    BEFORE UPDATE ON equipamentos_qrcode
    FOR EACH ROW
    EXECUTE FUNCTION qrcode_imutavel_pos_insert_check();
"""

REVERSE_RLS_TRIGGER = """
DROP TRIGGER IF EXISTS qrcode_imutavel_pos_insert_trg ON equipamentos_qrcode;
DROP FUNCTION IF EXISTS qrcode_imutavel_pos_insert_check();
DROP POLICY IF EXISTS qrcode_tenant_isolation_insert ON equipamentos_qrcode;
DROP POLICY IF EXISTS qrcode_tenant_isolation_delete ON equipamentos_qrcode;
DROP POLICY IF EXISTS qrcode_tenant_isolation_update ON equipamentos_qrcode;
DROP POLICY IF EXISTS qrcode_tenant_isolation_select ON equipamentos_qrcode;
ALTER TABLE equipamentos_qrcode DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("equipamentos", "0002_rls_policies_e_triggers"),
        ("tenant", "0002_tenant_bloqueio_automatico_inadimplencia_habilitado"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "hash",
                    models.CharField(
                        help_text="Digest completo `qrN:base64url(...)`. UNIQUE global — colisao entre tenants e cripto-impossivel com HMAC-SHA256 com chave de servidor; UNIQUE detecta bug em vez de degradar silenciosamente.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "emitido_em",
                    models.DateTimeField(
                        help_text="Timestamp usado no payload do HMAC. Imutavel pos-INSERT. Necessario pra reconstruir a evidencia (nao pra recomputar)."
                    ),
                ),
                (
                    "revogado_em",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando o hash foi invalidado (re-emissao por mudanca de TAG, perda fisica). UNICO campo mutavel apos INSERT.",
                        null=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "equipamento",
                    models.ForeignKey(
                        help_text="Equipamento ao qual este QR pertence.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qrcodes",
                        to="equipamentos.equipamento",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Denormalizado pra RLS (mesmo padrao Marco 1).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qrcodes",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Code de equipamento",
                "verbose_name_plural": "QR Codes de equipamentos",
                "db_table": "equipamentos_qrcode",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "equipamento"], name="equipamento_tenant__481f98_idx"
                    ),
                    models.Index(
                        fields=["equipamento", "revogado_em"], name="equipamento_equipam_d0883b_idx"
                    ),
                ],
            },
        ),
        migrations.RunSQL(sql=FORWARD_RLS_TRIGGER, reverse_sql=REVERSE_RLS_TRIGGER),
    ]
