"""T-EQP-012 (AC-EQP-002-1) - tabela `equipamentos_versao` + RLS pattern v2.

Versao auditada de mudanca em campo descritivo do Equipamento. Enum
`motivo_mudanca` com 9 valores (P-EQP-R2). Anti-PII em `motivo_detalhe`
via clean() do modelo (T-EQP-016 / INV-EQP-VERSAO-001) - reforco de
banco com CHECK seria custoso (regex unicode em PG); defesa em
profundidade fica em Python no clean + serializer Wave A.

Coverage:
- INV-TENANT-001/002/003: RLS pattern v2 (mesmo padrao Marco 1 e
  equipamentos.0002, ADR-0002 sec.6).
- INV-EQP-VERSAO-002: lista negativa de campos em payload de evento
  (`equipamento.versao_criada`) - cravada em service Wave A
  (T-EQP-017).
- INV-025: trigger PG imutabilidade pos-cert sera adicionada em
  T-EQP-013 (depende do modulo certificados).

# tests-coverage: tests/test_equipamentos_versao_t_eqp_012.py
"""

# Generated by Django 5.2.14 on 2026-05-22 00:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

RLS_FORWARD = """
-- =============================================================
-- RLS pattern v2 (ADR-0002 sec.6) - igual equipamentos.0002
-- =============================================================
ALTER TABLE equipamentos_versao ENABLE ROW LEVEL SECURITY;
ALTER TABLE equipamentos_versao FORCE ROW LEVEL SECURITY;

CREATE POLICY equipamentos_versao_tenant_isolation_select ON equipamentos_versao
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY equipamentos_versao_tenant_isolation_update ON equipamentos_versao
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY equipamentos_versao_tenant_isolation_delete ON equipamentos_versao
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY equipamentos_versao_tenant_isolation_insert ON equipamentos_versao
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);
"""

RLS_REVERSE = """
DROP POLICY IF EXISTS equipamentos_versao_tenant_isolation_insert ON equipamentos_versao;
DROP POLICY IF EXISTS equipamentos_versao_tenant_isolation_delete ON equipamentos_versao;
DROP POLICY IF EXISTS equipamentos_versao_tenant_isolation_update ON equipamentos_versao;
DROP POLICY IF EXISTS equipamentos_versao_tenant_isolation_select ON equipamentos_versao;
ALTER TABLE equipamentos_versao DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0006_promover_perfil_funcao'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoVersao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campo', models.CharField(help_text='Nome do campo do Equipamento que mudou (`modelo`, `faixa`, `classe`, `localizacao_fisica`, `perfil_tenant_snapshot`).', max_length=50)),
                ('valor_anterior_hash', models.CharField(help_text='HMAC-SHA256 do valor anterior em claro, salt do tenant. Nunca o valor cru (INV-EQP-VERSAO-002).', max_length=128)),
                ('valor_novo_hash', models.CharField(help_text='HMAC-SHA256 do valor novo em claro, salt do tenant. Nunca o valor cru (INV-EQP-VERSAO-002).', max_length=128)),
                ('motivo_mudanca', models.CharField(choices=[('correcao_cadastral', 'Correcao cadastral'), ('mudanca_local', 'Mudanca de local fisico'), ('troca_acessorio', 'Troca de acessorio'), ('recalibracao_diferente_faixa', 'Recalibracao em faixa diferente'), ('mudanca_classe_metrologica', 'Mudanca de classe metrologica (D->A via funcao SECURITY DEFINER)'), ('ajuste_pos_calibracao', 'Ajuste pos-calibracao (ISO 17025 cl. 6.4.10 — rotina)'), ('substituicao_componente_critico', 'Substituicao de componente critico (afeta rastreabilidade)'), ('atualizacao_firmware', 'Atualizacao de firmware (OIML D 31)'), ('outros', 'Outros (motivo_detalhe obrigatorio + aprovacao)')], help_text='Enum fechado RBC B7 + P-EQP-R2 (9 valores).', max_length=40)),
                ('motivo_detalhe', models.TextField(blank=True, default='', help_text='Texto livre obrigatorio (>=100 chars) quando motivo_mudanca obriga aprovacao (outros/substituicao_componente_critico/atualizacao_firmware). Anti-PII via clean (INV-EQP-VERSAO-001).')),
                ('snapshot_jsonb', models.JSONField(blank=True, default=dict, help_text='Dump dos campos versionaveis do Equipamento no momento da criacao desta versao. Permite reconstruir estado historico sem depender de joins. `{}` aceito (versoes minimas em Marco 2; populado pelo service Wave A).')),
                ('cliente_atual_id_no_momento', models.UUIDField(blank=True, help_text='Snapshot opaco do cliente_atual_id no momento. db_constraint = n/a (UUID puro) - cliente pode ser eliminado por LGPD.', null=True)),
                ('assinatura_a3_referencia', models.UUIDField(blank=True, help_text='UUID opaco emitido pelo Lacuna cliente-side (GATE-EQP-1 Wave A). NULL para motivos que nao exigem A3. Proibido hash truncado (INV-EQP-VERSAO-002).', null=True)),
                ('assinatura_a3_assinada_em', models.DateTimeField(blank=True, help_text='Timestamp do A3 (obrigatorio quando referencia presente).', null=True)),
                ('assinatura_a3_certificado_emissor_hash', models.CharField(blank=True, default='', help_text='HMAC do thumbprint do certificado emissor (AC do A3) com salt tenant. Obrigatorio quando referencia presente.', max_length=128)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('criado_por', models.ForeignKey(help_text='Usuario que solicitou a versao.', on_delete=django.db.models.deletion.PROTECT, related_name='equipamento_versoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes', to='equipamentos.equipamento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipamento_versoes', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Versao de equipamento',
                'verbose_name_plural': 'Versoes de equipamentos',
                'db_table': 'equipamentos_versao',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', 'equipamento', '-criado_em'], name='equipamento_tenant__c36088_idx'), models.Index(fields=['equipamento', 'campo', '-criado_em'], name='equipamento_equipam_cb38d4_idx'), models.Index(fields=['tenant', 'motivo_mudanca'], name='equipamento_tenant__84197e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('assinatura_a3_referencia__isnull', True), models.Q(('assinatura_a3_referencia__isnull', False), ('assinatura_a3_assinada_em__isnull', False), models.Q(('assinatura_a3_certificado_emissor_hash', ''), _negated=True)), _connector='OR'), name='ck_eqp_versao_a3_all_or_nothing')],
            },
        ),
        migrations.RunSQL(sql=RLS_FORWARD, reverse_sql=RLS_REVERSE),
    ]
