"""T-EQP-018+020 (US-EQP-002b AC-EQP-002b-1+3) — tabela
`equipamentos_aprovacao_versao` + RLS pattern v2 + trigger PG
anti-mutation pos-terminal.

CHECK `ck_aprovacao_solicitante_neq_decisor` (INV-EQP-002 ISO 17025
cl. 6.2 segregacao) ja vai como Django CheckConstraint no
`AprovacaoPendenteEquipamentoVersao.Meta.constraints`.

Trigger PG `aprovacao_versao_anti_mutacao_terminal` (T-EQP-018 trigger
parte do AC-EQP-002b-1): bloqueia qualquer UPDATE saindo de estados
terminais (`aprovada`/`rejeitada`/`expirada`). Defesa em profundidade
alem do service.

# tests-coverage: tests/test_equipamentos_aprovacao_t_eqp_018.py
"""

# Generated by Django 5.2.14 on 2026-05-22 01:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

RLS_FORWARD = """
-- =============================================================
-- RLS pattern v2 (ADR-0002 sec.6) - igual equipamentos.0002
-- =============================================================
ALTER TABLE equipamentos_aprovacao_versao ENABLE ROW LEVEL SECURITY;
ALTER TABLE equipamentos_aprovacao_versao FORCE ROW LEVEL SECURITY;

CREATE POLICY equipamentos_aprovacao_versao_tenant_isolation_select ON equipamentos_aprovacao_versao
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY equipamentos_aprovacao_versao_tenant_isolation_update ON equipamentos_aprovacao_versao
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY equipamentos_aprovacao_versao_tenant_isolation_delete ON equipamentos_aprovacao_versao
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY equipamentos_aprovacao_versao_tenant_isolation_insert ON equipamentos_aprovacao_versao
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- =============================================================
-- T-EQP-018 (AC-EQP-002b-1) - trigger anti-mutation pos-terminal
-- Bloqueia qualquer UPDATE saindo de `aprovada`/`rejeitada`/`expirada`.
-- =============================================================
CREATE OR REPLACE FUNCTION aprovacao_versao_anti_mutacao_terminal_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF OLD.status IN ('aprovada', 'rejeitada', 'expirada')
       AND (
           NEW.status IS DISTINCT FROM OLD.status
           OR NEW.decisor_id IS DISTINCT FROM OLD.decisor_id
           OR NEW.parecer_gestor_texto IS DISTINCT FROM OLD.parecer_gestor_texto
           OR NEW.decidida_em IS DISTINCT FROM OLD.decidida_em
           OR NEW.evidencia_documental_id IS DISTINCT FROM OLD.evidencia_documental_id
           OR NEW.motivo_detalhe IS DISTINCT FROM OLD.motivo_detalhe
           OR NEW.campo IS DISTINCT FROM OLD.campo
           OR NEW.valor_anterior_hash IS DISTINCT FROM OLD.valor_anterior_hash
           OR NEW.valor_novo_hash IS DISTINCT FROM OLD.valor_novo_hash
           OR NEW.solicitante_id IS DISTINCT FROM OLD.solicitante_id
           OR NEW.motivo_mudanca IS DISTINCT FROM OLD.motivo_mudanca
           OR NEW.sla_vencimento IS DISTINCT FROM OLD.sla_vencimento
       ) THEN
        RAISE EXCEPTION
            'AC-EQP-002b-1: aprovacao em estado terminal (%) e imutavel.',
            OLD.status;
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER aprovacao_versao_anti_mutacao_terminal_trg
    BEFORE UPDATE ON equipamentos_aprovacao_versao
    FOR EACH ROW
    EXECUTE FUNCTION aprovacao_versao_anti_mutacao_terminal_check();
"""

RLS_REVERSE = """
DROP TRIGGER IF EXISTS aprovacao_versao_anti_mutacao_terminal_trg ON equipamentos_aprovacao_versao;
DROP FUNCTION IF EXISTS aprovacao_versao_anti_mutacao_terminal_check();
DROP POLICY IF EXISTS equipamentos_aprovacao_versao_tenant_isolation_insert ON equipamentos_aprovacao_versao;
DROP POLICY IF EXISTS equipamentos_aprovacao_versao_tenant_isolation_delete ON equipamentos_aprovacao_versao;
DROP POLICY IF EXISTS equipamentos_aprovacao_versao_tenant_isolation_update ON equipamentos_aprovacao_versao;
DROP POLICY IF EXISTS equipamentos_aprovacao_versao_tenant_isolation_select ON equipamentos_aprovacao_versao;
ALTER TABLE equipamentos_aprovacao_versao DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0007_equipamentoversao'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AprovacaoPendenteEquipamentoVersao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campo', models.CharField(max_length=50)),
                ('valor_anterior_hash', models.CharField(max_length=128)),
                ('valor_novo_hash', models.CharField(max_length=128)),
                ('motivo_mudanca', models.CharField(choices=[('correcao_cadastral', 'Correcao cadastral'), ('mudanca_local', 'Mudanca de local fisico'), ('troca_acessorio', 'Troca de acessorio'), ('recalibracao_diferente_faixa', 'Recalibracao em faixa diferente'), ('mudanca_classe_metrologica', 'Mudanca de classe metrologica (D->A via funcao SECURITY DEFINER)'), ('ajuste_pos_calibracao', 'Ajuste pos-calibracao (ISO 17025 cl. 6.4.10 — rotina)'), ('substituicao_componente_critico', 'Substituicao de componente critico (afeta rastreabilidade)'), ('atualizacao_firmware', 'Atualizacao de firmware (OIML D 31)'), ('outros', 'Outros (motivo_detalhe obrigatorio + aprovacao)')], help_text='Deve estar em MOTIVOS_QUE_OBRIGAM_APROVACAO.', max_length=40)),
                ('motivo_detalhe', models.TextField(help_text='>=100 chars + anti-PII (INV-EQP-VERSAO-001). Reuso do mesmo validator do EquipamentoVersao.')),
                ('solicitado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sla_vencimento', models.DateTimeField(help_text='T-EQP-019: D+3 dias uteis se equipamento SEM cert vigente; D+7 com cert vigente. Calculado por workalendar.america.Brazil.')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de decisao do gestor'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada'), ('expirada', 'Expirada por SLA')], default='pendente', help_text='Trigger PG bloqueia UPDATE saindo de estados terminais.', max_length=20)),
                ('parecer_gestor_texto', models.TextField(blank=True, default='', help_text='>=30 chars quando decidida (aprovada ou rejeitada). Anti-PII via validator (regex INV-EQP-VERSAO-001).')),
                ('decidida_em', models.DateTimeField(blank=True, null=True)),
                ('evidencia_documental_id', models.UUIDField(blank=True, help_text='Opcional: anexo de dossie tecnico que sustenta a decisao.', null=True)),
                ('decisor', models.ForeignKey(blank=True, help_text='gestor_qualidade que aprovou/rejeitou. NULL ate decidir.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aprovacoes_versao_decididas', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprovacoes_versao', to='equipamentos.equipamento')),
                ('solicitante', models.ForeignKey(help_text='Quem propos a mudanca (geralmente metrologista).', on_delete=django.db.models.deletion.PROTECT, related_name='aprovacoes_versao_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprovacoes_versao_equipamento', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Aprovacao de versao de equipamento',
                'verbose_name_plural': 'Aprovacoes de versao de equipamentos',
                'db_table': 'equipamentos_aprovacao_versao',
                'ordering': ['-solicitado_em'],
                'indexes': [models.Index(fields=['tenant', 'status', '-solicitado_em'], name='equipamento_tenant__9b688c_idx'), models.Index(fields=['tenant', 'sla_vencimento'], name='equipamento_tenant__ec8d37_idx'), models.Index(fields=['equipamento', '-solicitado_em'], name='equipamento_equipam_fce30b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('solicitante', models.F('decisor')), _negated=True), name='ck_aprovacao_solicitante_neq_decisor')],
            },
        ),
        migrations.RunSQL(sql=RLS_FORWARD, reverse_sql=RLS_REVERSE),
    ]
