"""T-EQP-034 (US-EQP-004 AC-EQP-004-1) — tabela
`equipamentos_transferencia` + RLS pattern v2.

INV-050 (AC-EQP-004-2): defesa em camadas — cessionario_cliente.tenant_id
deve = Equipamento.tenant_id. db_constraint=False evita FK validation
sob RLS (igual ClienteIdentidadeHistorico Marco 1); service valida +
RLS isola.

INV-INT-010 (AC-EQP-004-3): cessionario e cedente nao podem estar
bloqueados (predicate `cliente_nao_bloqueado` Marco 1). Validacao em
service — 412 no endpoint.

# tests-coverage: tests/test_equipamentos_transferir_t_eqp_034.py
"""

# Generated by Django 5.2.14 on 2026-05-22 10:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

RLS_FORWARD = """
ALTER TABLE equipamentos_transferencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE equipamentos_transferencia FORCE ROW LEVEL SECURITY;

CREATE POLICY equipamentos_transferencia_tenant_isolation_select ON equipamentos_transferencia
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY equipamentos_transferencia_tenant_isolation_update ON equipamentos_transferencia
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY equipamentos_transferencia_tenant_isolation_delete ON equipamentos_transferencia
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY equipamentos_transferencia_tenant_isolation_insert ON equipamentos_transferencia
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);
"""

RLS_REVERSE = """
DROP POLICY IF EXISTS equipamentos_transferencia_tenant_isolation_insert ON equipamentos_transferencia;
DROP POLICY IF EXISTS equipamentos_transferencia_tenant_isolation_delete ON equipamentos_transferencia;
DROP POLICY IF EXISTS equipamentos_transferencia_tenant_isolation_update ON equipamentos_transferencia;
DROP POLICY IF EXISTS equipamentos_transferencia_tenant_isolation_select ON equipamentos_transferencia;
ALTER TABLE equipamentos_transferencia DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_us_cli_003_pii_regularizacao'),
        ('equipamentos', '0011_resolver_qr_publico_bypass'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaEquipamentoAceite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo_categoria', models.CharField(choices=[('venda', 'Venda'), ('comodato', 'Comodato'), ('doacao', 'Doacao'), ('correcao_cadastral', 'Correcao cadastral'), ('outro', 'Outro (motivo_detalhe obrigatorio)')], max_length=30)),
                ('motivo_detalhe', models.TextField(blank=True, default='', help_text="Obrigatorio quando motivo_categoria='outro'. Anti-PII Wave A.")),
                ('aceite_cedente', models.JSONField(blank=True, default=dict, help_text='Schema: {tipo: ViaAceiteTransferencia, usuario_id_atendente: UUID, observacao: str, consentimento_historico_expresso: bool}. {} antes do aceite ser registrado.')),
                ('aceite_cessionario', models.JSONField(blank=True, default=dict, help_text='Mesmo schema do aceite_cedente.')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('efetivada', 'Efetivada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('solicitado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('efetivada_em', models.DateTimeField(blank=True, null=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('texto_termo_versao_id', models.CharField(default='v1.0-2026-05-22', help_text='Versao do termo de transferencia (3 clausulas advogado). Marco 2 default v1.0; Wave A trara `transferencia-termo.md` com bump explicito.', max_length=20)),
                ('cedente_cliente', models.ForeignKey(blank=True, db_constraint=False, help_text='Cliente cedente — snapshot do `Equipamento.cliente_atual_id` no momento da solicitacao. NULL quando equipamento orfao.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_como_cedente', to='clientes.cliente')),
                ('cessionario_cliente', models.ForeignKey(db_constraint=False, help_text='Cliente cessionario. INV-050 cravado: tenant_id deve ser igual ao Equipamento.tenant_id (validado em servico + RLS).', on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_como_cessionario', to='clientes.cliente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='equipamentos.equipamento')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_equipamento', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Transferencia de equipamento',
                'verbose_name_plural': 'Transferencias de equipamentos',
                'db_table': 'equipamentos_transferencia',
                'ordering': ['-solicitado_em'],
                'indexes': [models.Index(fields=['tenant', 'status', '-solicitado_em'], name='equipamento_tenant__f19b66_idx'), models.Index(fields=['equipamento', '-solicitado_em'], name='equipamento_equipam_0c7ef7_idx')],
            },
        ),
        migrations.RunSQL(sql=RLS_FORWARD, reverse_sql=RLS_REVERSE),
    ]
