# Generated by Django 5.2.14 on 2026-05-18 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Fisica'), ('PJ', 'Pessoa Juridica')], help_text='PF (CPF) ou PJ (CNPJ alfanumerico IN RFB 2.229/2024).', max_length=2)),
                ('documento', models.CharField(help_text='CPF (11 digitos) OU CNPJ (12 alfanumericos + 2 DV digitos). Armazenado normalizado: sem pontuacao, UPPER para CNPJ.', max_length=14)),
                ('nome', models.CharField(help_text='Nome completo (PF) ou razao social (PJ).', max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, help_text='Formato livre nesta fase; normalizacao entra com modulo comunicacao.', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['tenant', 'documento'], name='ix_cliente_tenant_doc'), models.Index(fields=['tenant', 'nome'], name='ix_cliente_tenant_nome')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'tipo_pessoa', 'documento'), name='uq_cliente_tenant_documento')],
            },
        ),
    ]
