# Generated by Django 5.2.14 on 2026-05-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_seed_authz_acoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='aceite_lgpd_dispensa_motivo',
            field=models.CharField(blank=True, help_text="Preenchido em PJ sem PF associada (R3 advogado). Valor padrao: 'pj_sem_pf_associada'. Ver lgpd.py DISPENSAS_VALIDAS.", max_length=60),
        ),
        migrations.AddField(
            model_name='cliente',
            name='aceite_lgpd_em',
            field=models.DateTimeField(blank=True, help_text='Datetime do aceite. Obrigatorio em PF. Pode ser NULL em PJ se aceite_lgpd_dispensa_motivo informado (R3 advogado — PJ sem PF associada).', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='aceite_lgpd_ip_hash',
            field=models.CharField(blank=True, help_text='SHA-256 do IP do request (LGPD art. 6 V — qualidade + INV-013 rastreabilidade). Vazio se origem=balcao (titular nao presente).', max_length=64),
        ),
        migrations.AddField(
            model_name='cliente',
            name='aceite_lgpd_origem',
            field=models.CharField(blank=True, help_text='balcao | portal | importacao | api_terceiro. Ver lgpd.py ORIGENS_VALIDAS.', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='aceite_lgpd_versao',
            field=models.CharField(blank=True, help_text='Snapshot da versao vigente do texto no momento do aceite. Ver src/infrastructure/clientes/lgpd.py TEXTOS_HISTORICOS pra recuperar o texto exato que o titular aceitou. Imutavel apos gravacao.', max_length=40),
        ),
    ]
