# Generated by Django 5.2.14 on 2026-05-18 13:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0007_seed_authz_mesclar"),
        ("tenant", "0002_tenant_bloqueio_automatico_inadimplencia_habilitado"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClienteBloqueio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "motivo_categoria",
                    models.CharField(
                        help_text="Enum (ver bloqueio.py): manual_inadimplencia, manual_quebra_confianca, manual_solicitacao_juridico, manual_outro, automatico_inadimplencia_90d.",
                        max_length=40,
                    ),
                ),
                (
                    "motivo_observacao",
                    models.CharField(
                        blank=True,
                        help_text="Texto livre limitado; rejeita CPF/CNPJ/email/telefone (R2 advogado).",
                        max_length=200,
                    ),
                ),
                (
                    "justificativa_bruta",
                    models.TextField(
                        help_text="Texto da justificativa (>=30 chars). Confidencial — INV-013 estendida. Audit grava apenas SHA-256 (R1 advogado)."
                    ),
                ),
                (
                    "causation_type",
                    models.CharField(
                        blank=True,
                        help_text="Enum (TL4): titulo_vencido | importacao_batch | politica_inadimplencia | manual_decisao_admin. CHECK constraint na migration.",
                        max_length=40,
                    ),
                ),
                (
                    "causation_id",
                    models.UUIDField(
                        blank=True,
                        help_text="FK opcional para entidade que originou (ex: TituloVencido em Wave A).",
                        null=True,
                    ),
                ),
                (
                    "confirmacao_comunicacao_previa",
                    models.BooleanField(
                        default=False,
                        help_text="R3 advogado (CDC art. 6 III/IV + Lei 14.181/2021): bloqueio manual exige checkbox 'confirmo que comuniquei o cliente previamente'.",
                    ),
                ),
                ("bloqueado_em", models.DateTimeField(auto_now_add=True)),
                ("bloqueado_por_usuario_id", models.UUIDField(blank=True, null=True)),
                ("desbloqueado_em", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("desbloqueado_por_usuario_id", models.UUIDField(blank=True, null=True)),
                ("desbloqueado_motivo", models.CharField(blank=True, max_length=200)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bloqueios",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cliente_bloqueios",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloqueio de cliente",
                "verbose_name_plural": "Bloqueios de cliente",
                "db_table": "cliente_bloqueios",
                "ordering": ["-bloqueado_em"],
                "indexes": [
                    models.Index(fields=["tenant", "cliente"], name="ix_cli_bloq_tenant_cli"),
                    models.Index(fields=["tenant", "bloqueado_em"], name="ix_cli_bloq_tenant_data"),
                ],
            },
        ),
    ]
