# Generated by Django 5.2.14 on 2026-05-25 + edicao manual para acrescentar
# CREATE SEQUENCE + ALTER COLUMN SET DEFAULT.
#
# T-CAL-001 — Marco 4 schema inicial (Calibracao raiz agregado).
#
# Cria sequence global calibracao_numero_seq_global (paralelo ADR-0056 OS +
# INV-CAL-NUM-001) + tabela calibracao com TODOS os campos do spec.md §3.2 +
# §16.4 (P3 ritual Spec Kit absorveu 10 BLOQUEANTE + 23 MEDIO dos 4 reviews).
#
# RLS policies + numero_exibido GENERATED + trigger anti-mutation pos
# `aprovada` = T-CAL-002 (migration-irma na sequencia —
# `0002_rls_policies.py`).
#
# rls-policy: external 0002_rls_policies

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0023_us_cli_003_pii_regularizacao'),
        ('equipamentos', '0027_seed_authz_versionar'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        # Sequence global para numeracao calibracao (paralelo ADR-0056 OS +
        # INV-CAL-NUM-001). Buracos por rollback aceitos; UNIQUE(tenant,
        # numero_interno) garante unicidade per-tenant. DEFAULT
        # nextval(calibracao_numero_seq_global) e aplicado mais abaixo
        # (Django ORM nao suporta DEFAULT vindo de sequence).
        migrations.RunSQL(
            sql='CREATE SEQUENCE IF NOT EXISTS calibracao_numero_seq_global;',
            reverse_sql='DROP SEQUENCE IF EXISTS calibracao_numero_seq_global;',
        ),
        migrations.CreateModel(
            name='Calibracao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_interno', models.BigIntegerField(help_text='Gerado por sequence global calibracao_numero_seq_global no DEFAULT da migration (paralelo ADR-0056 + INV-CAL-NUM-001). UNIQUE(tenant, numero_interno). Buracos por rollback aceitos.')),
                ('numero_exibido', models.CharField(blank=True, default='', help_text='GENERATED STORED via SQL em migration 0002 — formato CAL-YYYY-NNNNNN.', max_length=20)),
                ('atividade_os_id', models.UUIDField(blank=True, help_text='FK AtividadeDaOS (db_constraint=False — modulo ordens_servico). NULL em recepcao avulsa (US-CAL-001). ADR-0023.', null=True)),
                ('cliente_referencia_hash', models.CharField(help_text='HashVersionado canonico v<NN>$<base64> (ADR-0064 + INV-HMAC-001). Preserva audit pos-anonimizacao (ADR-0032).', max_length=80)),
                ('cliente_key_id', models.CharField(help_text='KMS key id ADR-0064 (HMAC_KEY_<tenant>).', max_length=40)),
                ('snapshot_equipamento_json', models.JSONField(default=dict, help_text='Snapshot imutavel capturado em recepcionarInstrumento (cl. 7.4): nome, tag, NS, fabricante, modelo, perfil_tenant_snapshot (ADR-0022). INV-CAL-WORM-001.')),
                ('procedimento_id', models.UUIDField(blank=True, help_text='FK ProcedimentoCalibracao (db_constraint=False — modulo procedimentos a criar). NOT NULL apos configurarCalibracao (US-CAL-016). ADR-0030 vigencia.', null=True)),
                ('procedimento_versao_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot capturado em configurarCalibracao (US-CAL-016): codigo + versao_semver + hash_anexo_pdf. INV-CAL-WORM-001.')),
                ('tipo_acreditacao', models.CharField(choices=[('RBC', 'RBC (laboratorio acreditado CGCRE)'), ('NAO_RBC', 'Nao RBC')], default='NAO_RBC', help_text='RBC requer escopo + CMC + acordo regra decisao + vinculacao SI (INV-CAL-RAST-002).', max_length=10)),
                ('escopo_id', models.UUIDField(blank=True, help_text='FK Escopo CMC (db_constraint=False). NULL se NAO_RBC.', null=True)),
                ('configuracao_id', models.UUIDField(blank=True, help_text='FK ConfiguracaoCalibracao (a criar T-CAL-NNN). Preenchido em configurarCalibracao.', null=True)),
                ('status', models.CharField(choices=[('recepcionada', 'Recepcionada'), ('configurada', 'Configurada'), ('em_execucao', 'Em execucao'), ('em_revisao_1', 'Em revisao 1 (RT 1a conferencia)'), ('aguardando_2a_conferencia', 'Aguardando 2a conferencia'), ('aprovada', 'Aprovada (imutavel)'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada'), ('nao_conforme', 'Nao conforme'), ('pendente_resolucao_nc', 'Pendente resolucao NC'), ('aguardando_subcontratado', 'Aguardando subcontratado'), ('recebida_do_subcontratado', 'Recebida do subcontratado')], default='recepcionada', help_text='Maquina estados §4.1 spec. Trigger PG em migration 0002 bloqueia UPDATE pos `aprovada`.', max_length=30)),
                ('revision', models.IntegerField(default=0, help_text='Optimistic lock CAS — ADR-0065 + INV-CAL-CONC-003. UPDATE com WHERE revision = :expected RETURNING revision+1; 0 rows -> 409 ConflitoVersao. 11 transicoes de estado fazem CAS.')),
                ('executor_id', models.UUIDField(blank=True, help_text='Metrologista que registra leituras (INV-CAL-FRAUDE-EXEC-001). NULLABLE quando subcontratado_id NOT NULL (P-CAL-T9 tech-lead).', null=True)),
                ('revisor_id', models.UUIDField(blank=True, help_text='RT 1a conferencia (INV-CAL-FRAUDE-REV-001). cl. 6.2.', null=True)),
                ('conferente_id', models.UUIDField(blank=True, help_text='RT 2a conferencia (INV-CAL-FRAUDE-CONF-001 + ADR-0026). Default conferente_id != revisor_id; excecao via Excecao2aConferencia (4 condicoes).', null=True)),
                ('recebedor_user_id', models.UUIDField(blank=True, help_text='Quem recebe cert externo do subcontratado (INV-CAL-FRAUDE-RECEB-001). NOT NULL quando subcontratado_id NOT NULL. P-CAL-T9 tech-lead.', null=True)),
                ('excecao_2a_conf_id', models.UUIDField(blank=True, help_text='FK Excecao2aConferencia (ADR-0026 4 condicoes objetivas + 5%/mes).', null=True)),
                ('decisao', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CONDICIONAL', 'Condicional'), ('NA', 'Nao aplicavel')], default='NA', help_text='Decisao agregada. zona_ilac_g8 carrega zona granular (INV-CAL-DEC-005).', max_length=15)),
                ('zona_ilac_g8', models.CharField(choices=[('PASS', 'Pass (valor + U dentro de [LSL, USL])'), ('CONDITIONAL_PASS', 'Conditional pass (valor dentro, U cruza limite)'), ('PASS_COM_RESSALVA', 'Pass com ressalva (banda de guarda 30%)'), ('CONDITIONAL_FAIL', 'Conditional fail (valor fora, U cruza limite)'), ('FAIL_COM_RESSALVA', 'Fail com ressalva'), ('FAIL', 'Fail (valor + U totalmente fora)'), ('NA', 'Nao aplicavel (calibracao descritiva)')], default='NA', help_text='6 zonas ILAC G8:09/2019 §4 tabela 1 + NA. INV-CAL-DEC-005 (CHECK constraint em migration 0002). Calculado por motor §3.3.', max_length=20)),
                ('regra_decisao', models.CharField(choices=[('ACEITACAO_SIMPLES', 'Aceitacao simples (ILAC G8 §4.2)'), ('BANDA_GUARDA_30', 'Banda de guarda 30% (ILAC G8 §4.4)'), ('RISCO_COMPARTILHADO', 'Risco compartilhado (ILAC G8 §4.3 + JCGM 106)')], default='ACEITACAO_SIMPLES', help_text='Snapshot da regra acordada (ADR-0024 + INV-CAL-DEC-001). Lock pos APROVADA via trigger PG (INV-CAL-DEC-003).', max_length=25)),
                ('regra_decisao_override_cliente', models.BooleanField(default=False, help_text='True se cliente requisitou override (INV-CAL-DEC-002). Exige clausula contratual + assinatura A3 (AC-CAL-002-3 + P-CAL-A3).')),
                ('pfa_calculada', models.DecimalField(blank=True, decimal_places=4, help_text='Probabilidade de aceitacao falsa (ILAC G8 §4.4 + JCGM 106 §9). NOT NULL quando regra_decisao=BANDA_GUARDA_30 (INV-CAL-DEC-004).', max_digits=6, null=True)),
                ('pra_calculada', models.DecimalField(blank=True, decimal_places=4, help_text='Probabilidade de rejeicao falsa. NOT NULL quando regra_decisao=RISCO_COMPARTILHADO (INV-CAL-DEC-004).', max_digits=6, null=True)),
                ('nivel_confianca', models.DecimalField(decimal_places=4, default='0.9545', help_text='k=2 -> 95.45%. Usado no calculo PFA/PRA.', max_digits=6)),
                ('regra_decisao_acordada_em', models.DateTimeField(blank=True, help_text='Quando cliente acordou a regra (cl. 7.1.3). NOT NULL antes de em_revisao_1 quando tipo_acreditacao=RBC (INV-CAL-DEC-006).', null=True)),
                ('regra_decisao_acordada_documento_id', models.UUIDField(blank=True, help_text='FK AceiteRegraDecisao (db_constraint=False — entidade a criar T-CAL-016). Predicate regra_decisao_acordada_cobre valida vigencia.', null=True)),
                ('regra_decisao_acordada_hash', models.CharField(blank=True, default='', help_text='HashVersionado v<NN>$<base64> do texto acordado (ADR-0064 + INV-DOC-CANON-001).', max_length=80)),
                ('analise_critica_pedido_id', models.UUIDField(blank=True, help_text='FK orcamento.analise_critica quando atividade_os_id NOT NULL. cl. 7.1.1. (db_constraint=False).', null=True)),
                ('analise_critica_pedido_inline_hash', models.CharField(blank=True, default='', help_text='Hash canonicalizado quando recepcao avulsa (atividade_os_id IS NULL). INV-CAL-ANAL-001 + AC-CAL-001-3. CHECK composta em migration 0002.', max_length=80)),
                ('analise_critica_pedido_inline_canonicalizada', models.TextField(blank=True, default='', help_text='Texto >=100 chars + anti-PII INV-CAL-TXT-001 + INV-DOC-CANON-001. Pre-hash. Usado em recepcao avulsa.')),
                ('capacidade_tecnica_confirmada_por_user_id', models.UUIDField(blank=True, help_text='Quem confirmou capacidade tecnica em recepcao avulsa (cl. 7.1.1). Use case bloqueia INSERT sem este campo.', null=True)),
                ('snapshot_competencia_revisor_json', models.JSONField(blank=True, help_text='Capturado em aprovarRevisao (US-CAL-007 + AC-CAL-007-5 + INV-CAL-RT-002). Imutavel — preserva grandeza+faixa+vigencia da RTCompetencia na DATA da aprovacao.', null=True)),
                ('snapshot_competencia_conferente_json', models.JSONField(blank=True, help_text='Capturado em aprovar2aConferencia (US-CAL-008 + AC-CAL-008-4). Imutavel. INV-CAL-RT-002 + ADR-0026.', null=True)),
                ('versao_motor_calculo', models.CharField(blank=True, default='', help_text='Semver + commit-hash do motor (§3.3 spec + INV-CAL-VERSAO-001). Snapshot por calibracao pra replay deterministico em CGCRE 2050.', max_length=50)),
                ('subcontratado_id', models.UUIDField(blank=True, help_text='FK LaboratorioSubcontratado (db_constraint=False — T-CAL-014). NOT NULL quando fluxo subcontratacao ativo.', null=True)),
                ('aceite_subcontratacao_id', models.UUIDField(blank=True, help_text='FK AceiteSubcontratacao (T-CAL-015). NOT NULL quando subcontratado_id NOT NULL (INV-CAL-SUBC-001).', null=True)),
                ('certificado_subcontratado_snapshot_json', models.JSONField(blank=True, help_text='Snapshot cert externo recebido (INV-CAL-SUBC-003). Imutavel apos registrarRecebimentoSubcontratado.', null=True)),
                ('declaracao_subcontratacao_texto_id', models.UUIDField(blank=True, help_text='FK declaracao-subcontratacao-certificado-v1.0.md (ILAC G18 §6.3 + INV-CAL-SUBC-006). REQUER OAB+CGCRE.', null=True)),
                ('observacoes_gerais', models.TextField(blank=True, default='', help_text='<=500 chars + anti-PII INV-CAL-TXT-001 (regex saude estendida P-CAL-A2).')),
                ('motivo_cancelamento_hash', models.CharField(blank=True, default='', help_text='HashVersionado v<NN>$<base64> (ADR-0064) — quando status=cancelada.', max_length=80)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, help_text='Cadeia forense (NOVO-ALTO-1 Onda 7B retrofit M3 paralelo M4).')),
                ('causation_id', models.UUIDField(blank=True, help_text='FK calibracao_id que originou esta calibracao (reprocessamento). Estado APROVADA e imutavel — nova calibracao com causation_id.', null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('criada_por_user_id', models.UUIDField(blank=True, help_text='Quem recepcionou (auditoria + cl. 7.1).', null=True)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, help_text='Pode ficar NULL pos-anonimizacao (ADR-0032 + INV-CAL-ANON-001). Hash preservado em cliente_referencia_hash.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibracoes', to='clientes.cliente')),
                ('instrumento', models.ForeignKey(help_text='Equipamento do cliente em calibracao (M2).', on_delete=django.db.models.deletion.PROTECT, related_name='calibracoes', to='equipamentos.equipamento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibracoes', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Calibracao',
                'verbose_name_plural': 'Calibracoes',
                'db_table': 'calibracao',
                'ordering': ['-criada_em'],
                'indexes': [models.Index(fields=['tenant', 'status', 'criada_em'], name='cal_tenant_st_cri_idx'), models.Index(fields=['tenant', 'cliente'], name='cal_tenant_cliente_idx'), models.Index(fields=['tenant', 'instrumento'], name='cal_tenant_instrum_idx'), models.Index(condition=models.Q(('status', 'aprovada')), fields=['tenant', 'instrumento', 'criada_em'], name='cal_historico_inst_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'numero_interno'), name='uq_calibracao_numero_por_tenant')],
            },
        ),
        # Aplica DEFAULT nextval('calibracao_numero_seq_global') ao campo
        # numero_interno (Django ORM nao suporta DEFAULT vindo de sequence
        # — paralelo ADR-0056 OS + INV-CAL-NUM-001).
        migrations.RunSQL(
            sql=(
                "ALTER TABLE calibracao ALTER COLUMN numero_interno "
                "SET DEFAULT nextval('calibracao_numero_seq_global');"
            ),
            reverse_sql=(
                "ALTER TABLE calibracao ALTER COLUMN numero_interno DROP DEFAULT;"
            ),
        ),
    ]
