# Generated by Django 5.2.14 on 2026-05-25 + edicao manual para acrescentar
# RLS + trigger imutabilidade WORM (cl. 7.5 ISO 17025).
#
# T-CAL-004 — Marco 4 entidade Leitura (cl. 7.5 ISO 17025 — registro
# tecnico imutavel pos-INSERT). Concorrencia: UNIQUE composto
# (tenant, calibracao, ponto, repeticao) impede duplicacao
# (ADR-0065 + INV-CAL-CONC-001). UNIQUE parcial client_event_id
# garante idempotencia sync mobile (ADR-0027).
#
# Correcao pre-revisao via `LeituraCorrecao` (rasura digital — T-CAL-005).
#
# # audit-immutability: Leitura WORM cl. 7.5
# # tests-coverage: tests/regressao/test_inv_cal_conc_001_leitura.py (T-CAL-145)

import django.db.models.deletion
import uuid
from django.db import migrations, models


RLS_AND_TRIGGER_FORWARD = """
-- =============================================================
-- leitura - RLS pattern v2 (ADR-0002 §6)
-- =============================================================
ALTER TABLE leitura ENABLE ROW LEVEL SECURITY;
ALTER TABLE leitura FORCE ROW LEVEL SECURITY;

CREATE POLICY leitura_tenant_isolation_select ON leitura
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY leitura_tenant_isolation_update ON leitura
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY leitura_tenant_isolation_delete ON leitura
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY leitura_tenant_isolation_insert ON leitura
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- =============================================================
-- INV-CAL-WORM-001 — Leitura imutavel pos-INSERT (cl. 7.5)
-- =============================================================
CREATE OR REPLACE FUNCTION leitura_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: Leitura eh imutavel pos-INSERT (ISO 17025 cl. 7.5). Correcoes via LeituraCorrecao (rasura digital).';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: Leitura nao pode ser deletada (audit imutavel — retencao 25a cl. 8.4).';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER leitura_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON leitura
    FOR EACH ROW
    EXECUTE FUNCTION leitura_anti_mutation_check();
"""

RLS_AND_TRIGGER_REVERSE = """
DROP TRIGGER IF EXISTS leitura_anti_mutation_trg ON leitura;
DROP FUNCTION IF EXISTS leitura_anti_mutation_check();
DROP POLICY IF EXISTS leitura_tenant_isolation_insert ON leitura;
DROP POLICY IF EXISTS leitura_tenant_isolation_delete ON leitura;
DROP POLICY IF EXISTS leitura_tenant_isolation_update ON leitura;
DROP POLICY IF EXISTS leitura_tenant_isolation_select ON leitura;
ALTER TABLE leitura DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0003_triggers_numero_exibido_e_imutabilidade'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ponto_calibracao', models.DecimalField(decimal_places=8, help_text='Valor do ponto da calibracao (ex: 10.000 kg).', max_digits=20)),
                ('numero_repeticao', models.IntegerField(help_text='1, 2, 3, ... Tipicamente 3-10 repeticoes por ponto. UNIQUE composto (tenant, calibracao, ponto, repeticao) — INV-CAL-CONC-001 + ADR-0065.')),
                ('valor_lido', models.DecimalField(decimal_places=8, help_text='Valor lido do instrumento sob calibracao.', max_digits=20)),
                ('unidade', models.CharField(help_text='Unidade SI ou derivada (kg, g, mL, °C, ...).', max_length=20)),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual (operador digita)'), ('INTEGRACAO_SERIAL', 'Integracao serial (cabo serial)'), ('INTEGRACAO_USB', 'Integracao USB')], default='MANUAL', help_text='Origem da leitura.', max_length=20)),
                ('timestamp', models.DateTimeField(help_text='Momento da leitura no instrumento (relogio do PC do operador).')),
                ('executor_id_hash', models.CharField(help_text='HashVersionado v<NN>$<base64> do executor (ADR-0064 + INV-CAL-FRAUDE-EXEC-001). UUID cru NAO persistido aqui — anti-stalking pos 25a.', max_length=80)),
                ('client_event_id', models.UUIDField(blank=True, help_text='ID idempotente client-generated para sync de calibracao de campo (ADR-0027). UNIQUE parcial WHERE NOT NULL. NULL em laboratorio.', null=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, help_text='Cadeia forense (paralelo M3).')),
                ('calibracao', models.ForeignKey(help_text='Calibracao raiz agregado.', on_delete=django.db.models.deletion.PROTECT, related_name='leituras', to='calibracao.calibracao')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leituras', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Leitura',
                'verbose_name_plural': 'Leituras',
                'db_table': 'leitura',
                'ordering': ['calibracao', 'ponto_calibracao', 'numero_repeticao'],
                'indexes': [models.Index(fields=['tenant', 'calibracao', 'ponto_calibracao'], name='leit_cal_ponto_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'calibracao', 'ponto_calibracao', 'numero_repeticao'), name='uq_leitura_ponto_repeticao'), models.UniqueConstraint(condition=models.Q(('client_event_id__isnull', False)), fields=('tenant', 'calibracao', 'client_event_id'), name='uq_leitura_client_event')],
            },
        ),
        migrations.RunSQL(sql=RLS_AND_TRIGGER_FORWARD, reverse_sql=RLS_AND_TRIGGER_REVERSE),
    ]
