# Generated by Django 5.2.14 on 2026-05-25 + edicao manual para acrescentar
# RLS pattern v2 + triggers WORM + GENERATED dentro_tolerancia.
#
# T-CAL-005 + T-CAL-006:
# - LeituraCorrecao (cl. 7.5 rasura digital — WORM append-only +
#   INV-CAL-FRAUDE-COR-001 validado no use case).
# - CondicoesAmbientais (cl. 6.3.1 snapshot — WORM + GENERATED
#   dentro_tolerancia via ABS+CASE IMMUTABLE).
#
# # audit-immutability: LeituraCorrecao + CondicoesAmbientais WORM
# # tests-coverage: tests/regressao/test_inv_cal_amb_001.py (T-CAL-150)

import django.db.models.deletion
import uuid
from django.db import migrations, models


RLS_TRIGGERS_FORWARD = """
-- =============================================================
-- leitura_correcao - RLS pattern v2 + WORM (cl. 7.5)
-- =============================================================
ALTER TABLE leitura_correcao ENABLE ROW LEVEL SECURITY;
ALTER TABLE leitura_correcao FORCE ROW LEVEL SECURITY;

CREATE POLICY leitura_correcao_tenant_isolation_select ON leitura_correcao
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY leitura_correcao_tenant_isolation_update ON leitura_correcao
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY leitura_correcao_tenant_isolation_delete ON leitura_correcao
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY leitura_correcao_tenant_isolation_insert ON leitura_correcao
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

CREATE OR REPLACE FUNCTION leitura_correcao_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: LeituraCorrecao eh imutavel pos-INSERT (cl. 7.5 rasura digital).';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: LeituraCorrecao nao pode ser deletada (audit imutavel — retencao 25a cl. 8.4).';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER leitura_correcao_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON leitura_correcao
    FOR EACH ROW
    EXECUTE FUNCTION leitura_correcao_anti_mutation_check();

-- =============================================================
-- condicoes_ambientais - RLS pattern v2 + WORM + GENERATED
-- =============================================================
ALTER TABLE condicoes_ambientais ENABLE ROW LEVEL SECURITY;
ALTER TABLE condicoes_ambientais FORCE ROW LEVEL SECURITY;

CREATE POLICY condicoes_ambientais_tenant_isolation_select ON condicoes_ambientais
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY condicoes_ambientais_tenant_isolation_update ON condicoes_ambientais
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY condicoes_ambientais_tenant_isolation_delete ON condicoes_ambientais
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY condicoes_ambientais_tenant_isolation_insert ON condicoes_ambientais
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

CREATE OR REPLACE FUNCTION condicoes_ambientais_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: CondicoesAmbientais eh imutavel pos-INSERT (snapshot WORM).';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: CondicoesAmbientais nao pode ser deletada (audit imutavel).';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER condicoes_ambientais_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON condicoes_ambientais
    FOR EACH ROW
    EXECUTE FUNCTION condicoes_ambientais_anti_mutation_check();

-- =============================================================
-- dentro_tolerancia GENERATED COLUMN (ABS + CASE = IMMUTABLE)
-- =============================================================
-- INV-CAL-AMB-001 — registrarLeitura bloqueia 412 quando false.
-- ABS e operadores aritmeticos basicos sao IMMUTABLE no PG.
ALTER TABLE condicoes_ambientais DROP COLUMN dentro_tolerancia;
ALTER TABLE condicoes_ambientais ADD COLUMN dentro_tolerancia BOOLEAN
    GENERATED ALWAYS AS (
        (temperatura_alvo_celsius IS NULL
         OR temperatura_tolerancia_celsius IS NULL
         OR ABS(temperatura_lida_celsius - temperatura_alvo_celsius)
            <= temperatura_tolerancia_celsius)
        AND
        (umidade_alvo_pct IS NULL
         OR umidade_tolerancia_pct IS NULL
         OR ABS(umidade_lida_pct - umidade_alvo_pct)
            <= umidade_tolerancia_pct)
    ) STORED;
"""

RLS_TRIGGERS_REVERSE = """
-- Reverte GENERATED dentro_tolerancia
ALTER TABLE condicoes_ambientais DROP COLUMN dentro_tolerancia;
ALTER TABLE condicoes_ambientais ADD COLUMN dentro_tolerancia BOOLEAN DEFAULT TRUE NOT NULL;

DROP TRIGGER IF EXISTS condicoes_ambientais_anti_mutation_trg ON condicoes_ambientais;
DROP FUNCTION IF EXISTS condicoes_ambientais_anti_mutation_check();
DROP POLICY IF EXISTS condicoes_ambientais_tenant_isolation_insert ON condicoes_ambientais;
DROP POLICY IF EXISTS condicoes_ambientais_tenant_isolation_delete ON condicoes_ambientais;
DROP POLICY IF EXISTS condicoes_ambientais_tenant_isolation_update ON condicoes_ambientais;
DROP POLICY IF EXISTS condicoes_ambientais_tenant_isolation_select ON condicoes_ambientais;
ALTER TABLE condicoes_ambientais DISABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS leitura_correcao_anti_mutation_trg ON leitura_correcao;
DROP FUNCTION IF EXISTS leitura_correcao_anti_mutation_check();
DROP POLICY IF EXISTS leitura_correcao_tenant_isolation_insert ON leitura_correcao;
DROP POLICY IF EXISTS leitura_correcao_tenant_isolation_delete ON leitura_correcao;
DROP POLICY IF EXISTS leitura_correcao_tenant_isolation_update ON leitura_correcao;
DROP POLICY IF EXISTS leitura_correcao_tenant_isolation_select ON leitura_correcao;
ALTER TABLE leitura_correcao DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0004_leitura'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicoesAmbientais',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperatura_lida_celsius', models.DecimalField(decimal_places=3, help_text='Temperatura medida na bancada/ambiente.', max_digits=6)),
                ('umidade_lida_pct', models.DecimalField(decimal_places=2, help_text='Umidade relativa medida (0..100).', max_digits=5)),
                ('pressao_lida_kpa', models.DecimalField(blank=True, decimal_places=2, help_text='Pressao barometrica (opcional por grandeza).', max_digits=6, null=True)),
                ('temperatura_alvo_celsius', models.DecimalField(blank=True, decimal_places=3, help_text='Temperatura alvo do ProcedimentoCalibracao.', max_digits=6, null=True)),
                ('temperatura_tolerancia_celsius', models.DecimalField(blank=True, decimal_places=3, help_text='Tolerancia +/- em torno da temperatura_alvo.', max_digits=5, null=True)),
                ('umidade_alvo_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Umidade alvo do ProcedimentoCalibracao.', max_digits=5, null=True)),
                ('umidade_tolerancia_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Tolerancia +/- em torno da umidade_alvo.', max_digits=5, null=True)),
                ('dentro_tolerancia', models.BooleanField(default=True, help_text='GENERATED em migration via ABS + CASE NULL-safe. INV-CAL-AMB-001 — registrarLeitura bloqueia 412 quando false.')),
                ('executor_id_hash', models.CharField(help_text='HashVersionado executor (ADR-0064).', max_length=80)),
                ('medido_em', models.DateTimeField(help_text='Momento da medicao.')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condicoes_ambientais', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Condicoes Ambientais',
                'verbose_name_plural': 'Condicoes Ambientais',
                'db_table': 'condicoes_ambientais',
                'ordering': ['-medido_em'],
                'indexes': [models.Index(fields=['tenant', 'medido_em'], name='condamb_tenant_med_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeituraCorrecao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_original', models.DecimalField(decimal_places=8, help_text='Snapshot do valor_lido da Leitura ANTES da correcao.', max_digits=20)),
                ('valor_corrigido', models.DecimalField(decimal_places=8, help_text='Valor depois da correcao.', max_digits=20)),
                ('razao_correcao_canonicalizada', models.TextField(help_text='>=30 chars + anti-PII INV-CAL-TXT-001 + INV-DOC-CANON-001 (UTF-8 + LF + NFC + marcadores <<<CORPO INICIO/FIM>>>).')),
                ('razao_correcao_hash', models.CharField(help_text='HashVersionado v<NN>$<base64> do texto canonicalizado (ADR-0064).', max_length=80)),
                ('corretor_id_hash', models.CharField(help_text='HashVersionado do corretor (ADR-0064). UUID cru NAO persistido aqui — anti-stalking. Validacao INV-CAL-FRAUDE-COR-001 feita no use case (corretor_user_id == request.user.id).', max_length=80)),
                ('corrigido_em', models.DateTimeField(auto_now_add=True, help_text='Momento da correcao.')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, help_text='Cadeia forense.')),
                ('leitura', models.ForeignKey(help_text='Leitura corrigida (NAO muta — INV-CAL-WORM-001).', on_delete=django.db.models.deletion.PROTECT, related_name='correcoes', to='calibracao.leitura')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leituras_correcao', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Leitura — Correcao',
                'verbose_name_plural': 'Leituras — Correcoes',
                'db_table': 'leitura_correcao',
                'ordering': ['-corrigido_em'],
                'indexes': [models.Index(fields=['tenant', 'leitura'], name='leitcorr_tenant_leit_idx')],
            },
        ),
        migrations.RunSQL(sql=RLS_TRIGGERS_FORWARD, reverse_sql=RLS_TRIGGERS_REVERSE),
    ]
