# Generated by Django 5.2.14 on 2026-05-25 + edicao manual para acrescentar
# RLS pattern v2 + triggers WORM + CHECK Tipo A n>=6.
#
# T-CAL-007 — agregado de orcamento de incerteza (cl. 7.6 ISO 17025 +
# NIT-DICLA-030 rev. 15 §6.3 + GUM JCGM 100 + ILAC G8 §4.4):
# - OrcamentoIncerteza (raiz do orcamento; algoritmo_1 + algoritmo_2 +
#   divergencia + replay_determinismo_hash + bias). Lock pos
#   EM_REVISAO_1 (parte do trigger Calibracao.status).
# - ComponenteIncerteza (1:N) — Tipo A exige n>=6 (CHECK constraint).
# - OrcamentoPorPonto (1:N) — UNIQUE (orcamento, ponto).
#
# Triggers WORM em todas as 3 entidades (audit-immutability cl. 7.5).
#
# # audit-immutability: OrcamentoIncerteza + ComponenteIncerteza + OrcamentoPorPonto
# # tests-coverage: tests/regressao/test_inv_cal_inc_002_003_004.py (T-CAL-147)

import django.db.models.deletion
import uuid
from django.db import migrations, models


RLS_TRIGGERS_FORWARD = """
-- =============================================================
-- orcamento_incerteza - RLS pattern v2 + WORM
-- =============================================================
ALTER TABLE orcamento_incerteza ENABLE ROW LEVEL SECURITY;
ALTER TABLE orcamento_incerteza FORCE ROW LEVEL SECURITY;

CREATE POLICY orcamento_incerteza_tenant_isolation_select ON orcamento_incerteza
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY orcamento_incerteza_tenant_isolation_update ON orcamento_incerteza
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY orcamento_incerteza_tenant_isolation_delete ON orcamento_incerteza
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY orcamento_incerteza_tenant_isolation_insert ON orcamento_incerteza
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

CREATE OR REPLACE FUNCTION orcamento_incerteza_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: OrcamentoIncerteza eh imutavel pos-INSERT (lock pos EM_REVISAO_1 — cl. 7.6).';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: OrcamentoIncerteza nao pode ser deletado (audit imutavel — retencao 25a).';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER orcamento_incerteza_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON orcamento_incerteza
    FOR EACH ROW
    EXECUTE FUNCTION orcamento_incerteza_anti_mutation_check();

-- =============================================================
-- componente_incerteza - RLS pattern v2 + WORM + CHECK Tipo A n>=6
-- =============================================================
ALTER TABLE componente_incerteza ENABLE ROW LEVEL SECURITY;
ALTER TABLE componente_incerteza FORCE ROW LEVEL SECURITY;

CREATE POLICY componente_incerteza_tenant_isolation_select ON componente_incerteza
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY componente_incerteza_tenant_isolation_update ON componente_incerteza
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY componente_incerteza_tenant_isolation_delete ON componente_incerteza
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY componente_incerteza_tenant_isolation_insert ON componente_incerteza
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

CREATE OR REPLACE FUNCTION componente_incerteza_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: ComponenteIncerteza eh imutavel pos-INSERT.';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: ComponenteIncerteza nao pode ser deletado.';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER componente_incerteza_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON componente_incerteza
    FOR EACH ROW
    EXECUTE FUNCTION componente_incerteza_anti_mutation_check();

-- INV-CAL-INC-003 — Tipo A exige n>=6 + s_x NOT NULL (NIT-DICLA-030 §7.4)
ALTER TABLE componente_incerteza ADD CONSTRAINT ck_componente_tipo_a_n_min
    CHECK (
        tipo_componente <> 'A'
        OR (n_amostras IS NOT NULL AND n_amostras >= 6 AND s_x IS NOT NULL)
    );

-- INV-CAL-INC-004 — correlacao_com_componente_id NOT NULL exige coeficiente
ALTER TABLE componente_incerteza ADD CONSTRAINT ck_componente_correlacao_coef
    CHECK (
        correlacao_com_componente_id_id IS NULL
        OR coeficiente_correlacao IS NOT NULL
    );

-- =============================================================
-- orcamento_por_ponto - RLS pattern v2 + WORM
-- =============================================================
ALTER TABLE orcamento_por_ponto ENABLE ROW LEVEL SECURITY;
ALTER TABLE orcamento_por_ponto FORCE ROW LEVEL SECURITY;

CREATE POLICY orcamento_por_ponto_tenant_isolation_select ON orcamento_por_ponto
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY orcamento_por_ponto_tenant_isolation_update ON orcamento_por_ponto
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY orcamento_por_ponto_tenant_isolation_delete ON orcamento_por_ponto
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY orcamento_por_ponto_tenant_isolation_insert ON orcamento_por_ponto
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

CREATE OR REPLACE FUNCTION orcamento_por_ponto_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: OrcamentoPorPonto eh imutavel pos-INSERT.';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: OrcamentoPorPonto nao pode ser deletado.';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER orcamento_por_ponto_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON orcamento_por_ponto
    FOR EACH ROW
    EXECUTE FUNCTION orcamento_por_ponto_anti_mutation_check();
"""

RLS_TRIGGERS_REVERSE = """
DROP TRIGGER IF EXISTS orcamento_por_ponto_anti_mutation_trg ON orcamento_por_ponto;
DROP FUNCTION IF EXISTS orcamento_por_ponto_anti_mutation_check();
DROP POLICY IF EXISTS orcamento_por_ponto_tenant_isolation_insert ON orcamento_por_ponto;
DROP POLICY IF EXISTS orcamento_por_ponto_tenant_isolation_delete ON orcamento_por_ponto;
DROP POLICY IF EXISTS orcamento_por_ponto_tenant_isolation_update ON orcamento_por_ponto;
DROP POLICY IF EXISTS orcamento_por_ponto_tenant_isolation_select ON orcamento_por_ponto;
ALTER TABLE orcamento_por_ponto DISABLE ROW LEVEL SECURITY;

ALTER TABLE componente_incerteza DROP CONSTRAINT IF EXISTS ck_componente_correlacao_coef;
ALTER TABLE componente_incerteza DROP CONSTRAINT IF EXISTS ck_componente_tipo_a_n_min;
DROP TRIGGER IF EXISTS componente_incerteza_anti_mutation_trg ON componente_incerteza;
DROP FUNCTION IF EXISTS componente_incerteza_anti_mutation_check();
DROP POLICY IF EXISTS componente_incerteza_tenant_isolation_insert ON componente_incerteza;
DROP POLICY IF EXISTS componente_incerteza_tenant_isolation_delete ON componente_incerteza;
DROP POLICY IF EXISTS componente_incerteza_tenant_isolation_update ON componente_incerteza;
DROP POLICY IF EXISTS componente_incerteza_tenant_isolation_select ON componente_incerteza;
ALTER TABLE componente_incerteza DISABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS orcamento_incerteza_anti_mutation_trg ON orcamento_incerteza;
DROP FUNCTION IF EXISTS orcamento_incerteza_anti_mutation_check();
DROP POLICY IF EXISTS orcamento_incerteza_tenant_isolation_insert ON orcamento_incerteza;
DROP POLICY IF EXISTS orcamento_incerteza_tenant_isolation_delete ON orcamento_incerteza;
DROP POLICY IF EXISTS orcamento_incerteza_tenant_isolation_update ON orcamento_incerteza;
DROP POLICY IF EXISTS orcamento_incerteza_tenant_isolation_select ON orcamento_incerteza;
ALTER TABLE orcamento_incerteza DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0005_leituracorrecao_e_condicoesambientais'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoIncerteza',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('u_combinada', models.DecimalField(decimal_places=8, help_text='Snapshot do algoritmo 1 (GUM classico — pior caso quando OrcamentoPorPonto[]).', max_digits=20)),
                ('grau_liberdade_efetivo', models.DecimalField(decimal_places=2, help_text='Welch-Satterthwaite (GUM §G.4).', max_digits=10)),
                ('k', models.DecimalField(decimal_places=2, default='2.0', help_text='Fator de abrangencia (default k=2 -> 95.45%).', max_digits=5)),
                ('U_expandida', models.DecimalField(decimal_places=8, help_text='U = u_combinada * k.', max_digits=20)),
                ('nivel_confianca', models.DecimalField(decimal_places=3, default='0.9545', help_text='k=2 -> 95.45%.', max_digits=5)),
                ('documentacao_agregacao', models.TextField(help_text='>=50 chars (INV-CAL-INC-001) declarando como u_combinada agrega quando OrcamentoPorPonto[] existe (NIT-DICLA-030 rev. 15 NOVO-3 RBC R2).')),
                ('versao_motor_calculo', models.CharField(help_text='Semver + commit-hash do motor (ADR-0025 + INV-CAL-VERSAO-001).', max_length=50)),
                ('algoritmo_1_resultado', models.JSONField(help_text='Resultado completo do algoritmo 1 (GUM classico Decimal): u_combinada, U_expandida, k, grau_liberdade_efetivo, etc.')),
                ('algoritmo_2_resultado', models.JSONField(blank=True, help_text='Resultado completo do algoritmo 2 (Monte Carlo NumPy + seed em Calibracao.id). NULL se 2o caminho nao aplicavel pra grandeza.', null=True)),
                ('divergencia_pct', models.DecimalField(blank=True, decimal_places=3, help_text='Divergencia entre algoritmo 1 e 2 em porcentagem. <=0.1% silencioso; 0.1-1% alerta P3; >1% bloqueia DivergenciaCalculoInaceitavel (NC automatica).', max_digits=5, null=True)),
                ('replay_determinismo_hash', models.CharField(help_text='HashVersionado v<NN>$<base64> (ADR-0064) de inputs ordenados canonicamente + outputs separados. Regressao de calculo (mesmo input, output diferente) detectada em CI replay.', max_length=80)),
                ('bias_orcado', models.DecimalField(blank=True, decimal_places=8, help_text='Bias conhecido (GUM §4.3 + NIT-DICLA-030 — quando aplicavel).', max_digits=20, null=True)),
                ('bias_origem', models.CharField(blank=True, default='', help_text='Origem do bias (ex: calibracao_externa_padrao_referencia).', max_length=80)),
                ('arredondamento_aplicado_regra', models.CharField(default='NIT_DICLA_030_2_DIGITOS_SIG', help_text='Regra de arredondamento (NIT-DICLA-030 §7.5).', max_length=20)),
                ('calculado_em', models.DateTimeField(auto_now_add=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('calibracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_incerteza', to='calibracao.calibracao')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_incerteza', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Orcamento de Incerteza',
                'verbose_name_plural': 'Orcamentos de Incerteza',
                'db_table': 'orcamento_incerteza',
                'ordering': ['-calculado_em'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteIncerteza',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_componente', models.CharField(help_text="Ex: 'Resolucao do indicador', 'Deriva do padrao'.", max_length=80)),
                ('tipo_componente', models.CharField(choices=[('A', 'Tipo A (estatistica — repetibilidade)'), ('B', 'Tipo B (avaliacao por outros meios)')], help_text='A=estatistico (repetibilidade); B=outros meios.', max_length=1)),
                ('tipo_origem_componente', models.CharField(choices=[('REPETIBILIDADE', 'Repetibilidade (Tipo A)'), ('RESOLUCAO_INSTRUMENTO', 'Resolucao do instrumento'), ('INCERTEZA_PADRAO_REF', 'Incerteza herdada do padrao de referencia'), ('DERIVA_PADRAO', 'Deriva do padrao'), ('CONDICOES_AMBIENTAIS', 'Condicoes ambientais (temp/umidade/pressao)'), ('EXCENTRICIDADE', 'Excentricidade (balanca)'), ('POLARIZACAO_BIAS', 'Polarizacao / bias conhecido (GUM §4.3)'), ('OUTRO', 'Outro (justificavel)')], help_text='8 origens (§16.6). INV-CAL-INC-002 valida obrigatorias por grandeza+padrao (matriz componentes-obrigatorios-por-grandeza).', max_length=30)),
                ('distribuicao', models.CharField(choices=[('NORMAL', 'Normal'), ('RETANGULAR', 'Retangular (uniforme)'), ('TRIANGULAR', 'Triangular'), ('U', 'U (arcoseno)'), ('OUTRA', 'Outra')], max_length=20)),
                ('divisor', models.DecimalField(decimal_places=5, help_text='Ex: sqrt(3) p/ retangular, sqrt(6) p/ triangular.', max_digits=15)),
                ('valor_estimativa', models.DecimalField(decimal_places=8, max_digits=20)),
                ('contribuicao', models.DecimalField(decimal_places=8, max_digits=20)),
                ('grau_liberdade', models.DecimalField(decimal_places=2, default='50.0', max_digits=10)),
                ('fonte_default_padrao_id', models.UUIDField(blank=True, help_text='FK PadraoMetrologico (db_constraint=False — modulo padroes).', null=True)),
                ('formula_calculo', models.CharField(choices=[('REPETIBILIDADE_STD_MEDIA', 'Repetibilidade — s(x)/sqrt(n) Tipo A'), ('RESOLUCAO_RETANGULAR', 'Resolucao — d/(2*sqrt(3))'), ('PADRAO_CERTIFICADO', 'Padrao certificado — U_pdr/k_pdr'), ('DERIVA_LINEAR', 'Deriva linear historica do padrao'), ('TEMPERATURA_QUADRATICA', 'Temperatura — coef * deltaT^2'), ('BIAS_CONHECIDO', 'Bias conhecido (GUM §4.3)'), ('OUTRO', 'Outro (justificavel)')], help_text='§16.6 — formula declarada (matriz formula-calculo-por-grandeza).', max_length=40)),
                ('coeficiente_correlacao', models.DecimalField(blank=True, decimal_places=4, help_text='-1 a 1; NOT NULL quando correlacao_com_componente_id NOT NULL.', max_digits=5, null=True)),
                ('n_amostras', models.IntegerField(blank=True, help_text="NOT NULL quando tipo='A' (CHECK constraint na migration). INV-CAL-INC-003: n>=6 (NIT-DICLA-030 §7.4).", null=True)),
                ('s_x', models.DecimalField(blank=True, decimal_places=8, help_text="Desvio-padrao amostral. NOT NULL quando tipo='A'.", max_digits=20, null=True)),
                ('correlacao_com_componente_id', models.ForeignKey(blank=True, help_text='Self-FK GUM §5.2.2 — quando 2+ componentes vem do mesmo padrao.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correlacionados', to='calibracao.componenteincerteza')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes_incerteza', to='tenant.tenant')),
                ('orcamento_incerteza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='calibracao.orcamentoincerteza')),
            ],
            options={
                'verbose_name': 'Componente de Incerteza',
                'verbose_name_plural': 'Componentes de Incerteza',
                'db_table': 'componente_incerteza',
                'ordering': ['orcamento_incerteza', 'nome_componente'],
            },
        ),
        migrations.CreateModel(
            name='OrcamentoPorPonto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ponto_calibracao', models.DecimalField(decimal_places=8, max_digits=20)),
                ('u_combinada_no_ponto', models.DecimalField(decimal_places=8, max_digits=20)),
                ('U_expandida_no_ponto', models.DecimalField(decimal_places=8, max_digits=20)),
                ('k_no_ponto', models.DecimalField(decimal_places=2, default='2.0', max_digits=5)),
                ('orcamento_incerteza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pontos', to='calibracao.orcamentoincerteza')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos_por_ponto', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Orcamento por Ponto',
                'verbose_name_plural': 'Orcamentos por Ponto',
                'db_table': 'orcamento_por_ponto',
                'ordering': ['orcamento_incerteza', 'ponto_calibracao'],
            },
        ),
        migrations.AddIndex(
            model_name='orcamentoincerteza',
            index=models.Index(fields=['tenant', 'calibracao'], name='orcinc_tenant_cal_idx'),
        ),
        migrations.AddIndex(
            model_name='componenteincerteza',
            index=models.Index(fields=['tenant', 'orcamento_incerteza'], name='cmpinc_tenant_orc_idx'),
        ),
        migrations.AddConstraint(
            model_name='orcamentoporponto',
            constraint=models.UniqueConstraint(fields=('tenant', 'orcamento_incerteza', 'ponto_calibracao'), name='uq_orcamento_ponto'),
        ),
        migrations.RunSQL(sql=RLS_TRIGGERS_FORWARD, reverse_sql=RLS_TRIGGERS_REVERSE),
    ]
