# Generated by Django 5.2.14 on 2026-05-25 + edicao manual para acrescentar
# RLS pattern v2 + trigger WORM + trigger INV-CAL-RT-COMP-001
# (snapshot nao retroativo: bloqueia INSERT quando calibracao.status
# NOT IN (recepcionada, configurada)).
#
# T-CAL-008 — PadraoUsado snapshot (ADR-0040 + cl. 6.5).
# UNIQUE parcial WHERE snapshot_lock=false (INV-CAL-CONC-002 + ADR-0065).
#
# # audit-immutability: PadraoUsado WORM
# # tests-coverage: tests/regressao/test_inv_cal_rt_comp_001_pad_usado.py (T-CAL-148)

import django.db.models.deletion
import uuid
from django.db import migrations, models


RLS_TRIGGERS_FORWARD = """
-- =============================================================
-- padrao_usado - RLS pattern v2
-- =============================================================
ALTER TABLE padrao_usado ENABLE ROW LEVEL SECURITY;
ALTER TABLE padrao_usado FORCE ROW LEVEL SECURITY;

CREATE POLICY padrao_usado_tenant_isolation_select ON padrao_usado
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY padrao_usado_tenant_isolation_update ON padrao_usado
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY padrao_usado_tenant_isolation_delete ON padrao_usado
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY padrao_usado_tenant_isolation_insert ON padrao_usado
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- =============================================================
-- INV-CAL-RT-COMP-001 — snapshot nao retroativo
-- =============================================================
-- BEFORE INSERT bloqueia quando calibracao.status NOT IN
-- (recepcionada, configurada). Garante que snapshot e sempre
-- contemporaneo da selecao do padrao.
CREATE OR REPLACE FUNCTION padrao_usado_anti_snapshot_retroativo_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
DECLARE
    cal_status TEXT;
BEGIN
    SELECT status INTO cal_status FROM calibracao WHERE id = NEW.calibracao_id;
    IF cal_status NOT IN ('recepcionada', 'configurada') THEN
        RAISE EXCEPTION
            'INV-CAL-RT-COMP-001: PadraoUsado snapshot nao pode ser feito quando calibracao.status = % (so em recepcionada|configurada — snapshot nao retroativo).',
            cal_status;
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER padrao_usado_anti_snapshot_retroativo_trg
    BEFORE INSERT ON padrao_usado
    FOR EACH ROW
    EXECUTE FUNCTION padrao_usado_anti_snapshot_retroativo_check();

-- =============================================================
-- INV-CAL-WORM-001 — PadraoUsado imutavel pos-INSERT
-- =============================================================
-- Excecao: snapshot_lock pode ser UPDATEd de false -> true
-- (use case seta quando calibracao atinge em_revisao_1).
-- Demais campos imutaveis.
CREATE OR REPLACE FUNCTION padrao_usado_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        -- Permite apenas snapshot_lock = false -> true
        IF NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
           OR NEW.calibracao_id IS DISTINCT FROM OLD.calibracao_id
           OR NEW.padrao_id IS DISTINCT FROM OLD.padrao_id
           OR NEW.padrao_id_hash IS DISTINCT FROM OLD.padrao_id_hash
           OR NEW.snapshot_padrao_json IS DISTINCT FROM OLD.snapshot_padrao_json
           OR NEW.snapshot_capturado_at IS DISTINCT FROM OLD.snapshot_capturado_at
           OR NEW.vinculacao_si_tipo IS DISTINCT FROM OLD.vinculacao_si_tipo
           OR NEW.vinculacao_si_referencia_id IS DISTINCT FROM OLD.vinculacao_si_referencia_id
           OR NEW.cadeia_rastreabilidade_documento_id IS DISTINCT FROM OLD.cadeia_rastreabilidade_documento_id
        THEN
            RAISE EXCEPTION
                'INV-CAL-WORM-001: PadraoUsado eh imutavel pos-INSERT (so snapshot_lock pode mudar false->true).';
        END IF;
        IF OLD.snapshot_lock = true AND NEW.snapshot_lock = false THEN
            RAISE EXCEPTION
                'INV-CAL-WORM-001: snapshot_lock e one-way (false -> true).';
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: PadraoUsado nao pode ser deletado (audit imutavel — retencao 25a).';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER padrao_usado_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON padrao_usado
    FOR EACH ROW
    EXECUTE FUNCTION padrao_usado_anti_mutation_check();
"""

RLS_TRIGGERS_REVERSE = """
DROP TRIGGER IF EXISTS padrao_usado_anti_mutation_trg ON padrao_usado;
DROP FUNCTION IF EXISTS padrao_usado_anti_mutation_check();
DROP TRIGGER IF EXISTS padrao_usado_anti_snapshot_retroativo_trg ON padrao_usado;
DROP FUNCTION IF EXISTS padrao_usado_anti_snapshot_retroativo_check();
DROP POLICY IF EXISTS padrao_usado_tenant_isolation_insert ON padrao_usado;
DROP POLICY IF EXISTS padrao_usado_tenant_isolation_delete ON padrao_usado;
DROP POLICY IF EXISTS padrao_usado_tenant_isolation_update ON padrao_usado;
DROP POLICY IF EXISTS padrao_usado_tenant_isolation_select ON padrao_usado;
ALTER TABLE padrao_usado DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0006_orcamento_incerteza'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadraoUsado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('padrao_id', models.UUIDField(help_text='FK PadraoMetrologico (db_constraint=False — modulo padroes a criar separadamente conforme ADR-0040).')),
                ('padrao_id_hash', models.CharField(help_text='HashVersionado v<NN>$<base64> (ADR-0064) — protecao cross-tenant + preserva audit pos-baixa do padrao.', max_length=80)),
                ('snapshot_padrao_json', models.JSONField(help_text='Snapshot imutavel: cert externo, validade, classe, valor convencional, incertezas_certificado, vinculacao SI. INV-CAL-SNAP-001 + INV-CAL-RAST-001.')),
                ('snapshot_capturado_at', models.DateTimeField(help_text='Momento da captura — INV-CAL-RT-COMP-001 (snapshot nao retroativo). Trigger PG bloqueia INSERT quando calibracao.status NOT IN (recepcionada, configurada).')),
                ('snapshot_lock', models.BooleanField(default=False, help_text='True quando calibracao.status >= em_revisao_1 (use case seta via UPDATE). UNIQUE parcial WHERE snapshot_lock=false (INV-CAL-CONC-002).')),
                ('vinculacao_si_tipo', models.CharField(choices=[('BIPM_DIRETO', 'BIPM direto'), ('INMETRO', 'INMETRO (laboratorio nacional)'), ('RBC', 'RBC (laboratorio acreditado)'), ('NMI_ESTRANGEIRO', 'NMI estrangeiro (NIST, PTB, NPL, ...)'), ('MRC_NIST_PTB_NPL', 'Material de Referencia Certificado'), ('INTERNO_DECLARADO', 'Interno declarado (proibido em RBC — INV-CAL-RAST-002)')], help_text='INV-CAL-RAST-002: tenant RBC proibe INTERNO_DECLARADO (validado em use case + CHECK composta cross-table).', max_length=20)),
                ('vinculacao_si_referencia_id', models.CharField(help_text="Ex: 'INMETRO-LAB-METROL-MASSA-CERT-2024-456'.", max_length=80)),
                ('cadeia_rastreabilidade_documento_id', models.UUIDField(blank=True, help_text='FK arquivo do cert do lab emissor (db_constraint=False).', null=True)),
                ('calibracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='padroes_usados', to='calibracao.calibracao')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='padroes_usados', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Padrao Usado',
                'verbose_name_plural': 'Padroes Usados',
                'db_table': 'padrao_usado',
                'ordering': ['-snapshot_capturado_at'],
                'indexes': [models.Index(fields=['tenant', 'calibracao'], name='padusu_tenant_cal_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('snapshot_lock', False)), fields=('tenant', 'calibracao', 'padrao_id'), name='uq_padrao_usado_pre_lock')],
            },
        ),
        migrations.RunSQL(sql=RLS_TRIGGERS_FORWARD, reverse_sql=RLS_TRIGGERS_REVERSE),
    ]
