# Generated by Django 5.2.14 on 2026-05-25 + edicao manual para
# acrescentar RLS + triggers WORM + CHECK XOR foto/recusa + CHECK INAPTO motivo.
#
# T-CAL-009 + T-CAL-010:
# - RecepcaoItemCalibracao (cl. 7.4 ISO 17025 — recepcao do item).
# - MedicaoControle (cl. 7.7.1 — grafico de controle + Western Electric
#   P-CAL-R8 RBC).
#
# # audit-immutability: RecepcaoItemCalibracao + MedicaoControle WORM
# # tests-coverage: tests/regressao/test_medicao_controle_western_electric.py (T-CAL-150)

import django.db.models.deletion
import uuid
from django.db import migrations, models


RLS_TRIGGERS_FORWARD = """
-- =============================================================
-- recepcao_item_calibracao - RLS pattern v2 + WORM + CHECK XOR foto
-- =============================================================
ALTER TABLE recepcao_item_calibracao ENABLE ROW LEVEL SECURITY;
ALTER TABLE recepcao_item_calibracao FORCE ROW LEVEL SECURITY;

CREATE POLICY recepcao_tenant_isolation_select ON recepcao_item_calibracao
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY recepcao_tenant_isolation_update ON recepcao_item_calibracao
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY recepcao_tenant_isolation_delete ON recepcao_item_calibracao
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY recepcao_tenant_isolation_insert ON recepcao_item_calibracao
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

CREATE OR REPLACE FUNCTION recepcao_item_calibracao_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'INV-CAL-WORM-001: RecepcaoItemCalibracao eh imutavel pos-INSERT (cl. 7.4).';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'INV-CAL-WORM-001: RecepcaoItemCalibracao nao pode ser deletada.';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER recepcao_item_calibracao_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON recepcao_item_calibracao
    FOR EACH ROW
    EXECUTE FUNCTION recepcao_item_calibracao_anti_mutation_check();

-- P-CAL-A5 advogado: CHECK XOR — foto OU recusa, nunca os dois nem nenhum
ALTER TABLE recepcao_item_calibracao ADD CONSTRAINT ck_recepcao_foto_xor_recusa
    CHECK (
        (foto_evidencia_id IS NOT NULL AND foto_evidencia_recusa_id IS NULL)
        OR (foto_evidencia_id IS NULL AND foto_evidencia_recusa_id IS NOT NULL)
    );

-- INAPTO exige motivo
ALTER TABLE recepcao_item_calibracao ADD CONSTRAINT ck_recepcao_inapto_motivo
    CHECK (
        avaliacao_aptidao <> 'INAPTO'
        OR (motivo_inaptidao_hash <> '' AND motivo_inaptidao_canonicalizada <> '')
    );

-- =============================================================
-- medicao_controle - RLS pattern v2 + WORM (excecao: job atualiza WE)
-- =============================================================
ALTER TABLE medicao_controle ENABLE ROW LEVEL SECURITY;
ALTER TABLE medicao_controle FORCE ROW LEVEL SECURITY;

CREATE POLICY medicao_controle_tenant_isolation_select ON medicao_controle
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY medicao_controle_tenant_isolation_update ON medicao_controle
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY medicao_controle_tenant_isolation_delete ON medicao_controle
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY medicao_controle_tenant_isolation_insert ON medicao_controle
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

CREATE OR REPLACE FUNCTION medicao_controle_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        -- Excecao: job procrastinate atualiza regra_western_electric_violada
        -- apos analisar ultimas 30 medicoes. Demais campos imutaveis.
        IF NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
           OR NEW.padrao_id IS DISTINCT FROM OLD.padrao_id
           OR NEW.valor_medido IS DISTINCT FROM OLD.valor_medido
           OR NEW.valor_esperado IS DISTINCT FROM OLD.valor_esperado
           OR NEW.desvio IS DISTINCT FROM OLD.desvio
           OR NEW.escore_z IS DISTINCT FROM OLD.escore_z
           OR NEW.executor_id_hash IS DISTINCT FROM OLD.executor_id_hash
           OR NEW.executado_em IS DISTINCT FROM OLD.executado_em
        THEN
            RAISE EXCEPTION
                'INV-CAL-WORM-001: MedicaoControle eh imutavel pos-INSERT (so regra_western_electric_violada pode ser populado por job apos analise).';
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'INV-CAL-WORM-001: MedicaoControle nao pode ser deletada (audit cl. 7.7.1).';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER medicao_controle_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON medicao_controle
    FOR EACH ROW
    EXECUTE FUNCTION medicao_controle_anti_mutation_check();
"""

RLS_TRIGGERS_REVERSE = """
DROP TRIGGER IF EXISTS medicao_controle_anti_mutation_trg ON medicao_controle;
DROP FUNCTION IF EXISTS medicao_controle_anti_mutation_check();
DROP POLICY IF EXISTS medicao_controle_tenant_isolation_insert ON medicao_controle;
DROP POLICY IF EXISTS medicao_controle_tenant_isolation_delete ON medicao_controle;
DROP POLICY IF EXISTS medicao_controle_tenant_isolation_update ON medicao_controle;
DROP POLICY IF EXISTS medicao_controle_tenant_isolation_select ON medicao_controle;
ALTER TABLE medicao_controle DISABLE ROW LEVEL SECURITY;

ALTER TABLE recepcao_item_calibracao DROP CONSTRAINT IF EXISTS ck_recepcao_inapto_motivo;
ALTER TABLE recepcao_item_calibracao DROP CONSTRAINT IF EXISTS ck_recepcao_foto_xor_recusa;
DROP TRIGGER IF EXISTS recepcao_item_calibracao_anti_mutation_trg ON recepcao_item_calibracao;
DROP FUNCTION IF EXISTS recepcao_item_calibracao_anti_mutation_check();
DROP POLICY IF EXISTS recepcao_tenant_isolation_insert ON recepcao_item_calibracao;
DROP POLICY IF EXISTS recepcao_tenant_isolation_delete ON recepcao_item_calibracao;
DROP POLICY IF EXISTS recepcao_tenant_isolation_update ON recepcao_item_calibracao;
DROP POLICY IF EXISTS recepcao_tenant_isolation_select ON recepcao_item_calibracao;
ALTER TABLE recepcao_item_calibracao DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0007_padrao_usado'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicaoControle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('padrao_id', models.UUIDField(help_text='FK PadraoMetrologico (db_constraint=False).')),
                ('grandeza', models.CharField(max_length=50)),
                ('faixa_min', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('faixa_max', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('valor_medido', models.DecimalField(decimal_places=8, max_digits=20)),
                ('valor_esperado', models.DecimalField(decimal_places=8, max_digits=20)),
                ('desvio', models.DecimalField(decimal_places=8, help_text='valor_medido - valor_esperado.', max_digits=20)),
                ('dentro_2sigma', models.BooleanField()),
                ('dentro_3sigma', models.BooleanField()),
                ('escore_z', models.DecimalField(blank=True, decimal_places=3, help_text='(P-CAL-R8) Quando padrao tem incerteza_referencia conhecida.', max_digits=5, null=True)),
                ('regra_western_electric_violada', models.CharField(blank=True, choices=[('RULE_1_3SIGMA', 'Rule 1 — 1 ponto fora de 3 sigma'), ('RULE_2_SEVEN_SAME_SIDE', 'Rule 2 — 7 pontos seguidos mesmo lado da media'), ('RULE_3_TREND', 'Rule 3 — tendencia crescente/decrescente 6+ pontos'), ('RULE_5_TWO_OF_THREE', 'Rule 5 — 2 de 3 pontos > 2 sigma')], default='', help_text='Preenchido por job `analisar_padrao_medicoes_controle` apos INSERT. Job recalcula ultimas 30 medicoes.', max_length=30)),
                ('executor_id_hash', models.CharField(help_text='HashVersionado (ADR-0064).', max_length=80)),
                ('executado_em', models.DateTimeField()),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicoes_controle', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Medicao de Controle',
                'verbose_name_plural': 'Medicoes de Controle',
                'db_table': 'medicao_controle',
                'ordering': ['-executado_em'],
                'indexes': [models.Index(fields=['tenant', 'padrao_id', 'executado_em'], name='medctrl_pad_exec_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecepcaoItemCalibracao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_referencia_hash', models.CharField(help_text='HashVersionado (ADR-0064) — preservado pos-anonimizacao.', max_length=80)),
                ('instrumento_recebido_em', models.DateTimeField(help_text='Momento da recepcao fisica.')),
                ('condicoes_recebidas_canonicalizada', models.TextField(help_text='>=30 chars + anti-PII INV-CAL-TXT-001 + canonicalizacao INV-DOC-CANON-001 (UTF-8 + LF + NFC + marcadores).')),
                ('condicoes_recebidas_hash', models.CharField(help_text='HashVersionado do texto canonicalizado (ADR-0064).', max_length=80)),
                ('avaliacao_aptidao', models.CharField(choices=[('APTO', 'Apto (item em condicoes de calibracao)'), ('APTO_COM_RESSALVA', 'Apto com ressalva (condicoes especiais)'), ('INAPTO', 'Inapto (item recusado — cliente notificado)')], help_text='Avaliacao do item (cl. 7.4 — separada de analise critica de pedido cl. 7.1.1).', max_length=20)),
                ('motivo_inaptidao_canonicalizada', models.TextField(blank=True, default='', help_text='NOT NULL quando avaliacao_aptidao=INAPTO. Texto >=30 chars + anti-PII INV-CAL-TXT-001.')),
                ('motivo_inaptidao_hash', models.CharField(blank=True, default='', help_text='HashVersionado quando INAPTO.', max_length=80)),
                ('fluxo_subcontratacao_id', models.UUIDField(blank=True, help_text='FK quando recepcao decide subcontratar (US-CAL-017).', null=True)),
                ('foto_evidencia_id', models.UUIDField(blank=True, help_text='FK EvidenciaFotoAtividade (db_constraint=False). NULL quando cliente recusa (foto_evidencia_recusa_id NOT NULL). EXIF stripado obrigatorio (INV-CAL-FOTO-001 + hook M4 P9).', null=True)),
                ('foto_evidencia_recusa_id', models.UUIDField(blank=True, help_text='FK ConsentimentoFotoRecusado (T-CAL-NNN). XOR com foto_evidencia_id.', null=True)),
                ('aviso_foto_texto_canonico_id', models.UUIDField(help_text='FK aviso-foto-recepcao-v1.0.md (REQUER OAB — minuta preliminar pelo agente). Texto renderizado ao cliente antes da captura.')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('calibracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepcoes', to='calibracao.calibracao')),
                ('condicoes_ambientais_id', models.ForeignKey(help_text='Snapshot CondicoesAmbientais no momento da recepcao.', on_delete=django.db.models.deletion.PROTECT, related_name='recepcoes', to='calibracao.condicoesambientais')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepcoes_calibracao', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Recepcao Item Calibracao',
                'verbose_name_plural': 'Recepcoes Item Calibracao',
                'db_table': 'recepcao_item_calibracao',
                'ordering': ['-instrumento_recebido_em'],
                'indexes': [models.Index(fields=['tenant', 'calibracao'], name='recep_tenant_cal_idx')],
            },
        ),
        migrations.RunSQL(sql=RLS_TRIGGERS_FORWARD, reverse_sql=RLS_TRIGGERS_REVERSE),
    ]
