# Generated by Django 5.2.14 on 2026-05-25 + edicao manual para
# acrescentar RLS + trigger BEFORE INSERT sequencia_local + advisory
# lock helper + APPEND-ONLY (UPDATE/DELETE bloqueado).
#
# T-CAL-011 — EventoDeCalibracao audit WORM.
# Hash-chain por (tenant_id, calibracao_id) serializada via advisory
# lock no use case `append_evento_calibracao` (ADR-0065 INV-CAL-AUD-002).
# Trigger BEFORE INSERT seta sequencia_local = MAX+1 dentro da
# calibracao (1, 2, 3, ...).
#
# # audit-immutability: EventoDeCalibracao append-only WORM
# # tests-coverage: tests/regressao/test_hash_chain_calibracao_concorrente.py (T-CAL-152)

import django.db.models.deletion
import uuid
from django.db import migrations, models


RLS_TRIGGERS_FORWARD = """
-- =============================================================
-- evento_de_calibracao - RLS pattern v2
-- =============================================================
ALTER TABLE evento_de_calibracao ENABLE ROW LEVEL SECURITY;
ALTER TABLE evento_de_calibracao FORCE ROW LEVEL SECURITY;

CREATE POLICY evento_calibracao_tenant_isolation_select ON evento_de_calibracao
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY evento_calibracao_tenant_isolation_update ON evento_de_calibracao
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY evento_calibracao_tenant_isolation_delete ON evento_de_calibracao
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY evento_calibracao_tenant_isolation_insert ON evento_de_calibracao
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- =============================================================
-- sequencia_local populador (BEFORE INSERT) — ADR-0065 + INV-CAL-AUD-002
-- =============================================================
-- Calcula sequencia_local = MAX+1 por (tenant_id, calibracao_id).
-- Combinado com advisory lock no use case `append_evento_calibracao`
-- (SELECT pg_advisory_xact_lock(hashtext(tenant_id::text || calibracao_id::text)))
-- garante ordem total dentro da calibracao.
CREATE OR REPLACE FUNCTION evento_de_calibracao_seq_populator()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
DECLARE
    next_seq BIGINT;
BEGIN
    IF NEW.sequencia_local IS NULL OR NEW.sequencia_local = 0 THEN
        SELECT COALESCE(MAX(sequencia_local), 0) + 1
            INTO next_seq
            FROM evento_de_calibracao
            WHERE tenant_id = NEW.tenant_id
              AND calibracao_id = NEW.calibracao_id;
        NEW.sequencia_local := next_seq;
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER evento_de_calibracao_seq_trg
    BEFORE INSERT ON evento_de_calibracao
    FOR EACH ROW
    EXECUTE FUNCTION evento_de_calibracao_seq_populator();

-- =============================================================
-- INV-CAL-WORM-001 — APPEND-ONLY (UPDATE + DELETE bloqueados)
-- =============================================================
CREATE OR REPLACE FUNCTION evento_de_calibracao_append_only_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'INV-CAL-AUD-001: EventoDeCalibracao eh append-only WORM (cl. 7.5 + cl. 8.4 retencao 25a).';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-AUD-001: EventoDeCalibracao nao pode ser deletado (audit imutavel).';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER evento_de_calibracao_append_only_trg
    BEFORE UPDATE OR DELETE ON evento_de_calibracao
    FOR EACH ROW
    EXECUTE FUNCTION evento_de_calibracao_append_only_check();
"""

RLS_TRIGGERS_REVERSE = """
DROP TRIGGER IF EXISTS evento_de_calibracao_append_only_trg ON evento_de_calibracao;
DROP FUNCTION IF EXISTS evento_de_calibracao_append_only_check();
DROP TRIGGER IF EXISTS evento_de_calibracao_seq_trg ON evento_de_calibracao;
DROP FUNCTION IF EXISTS evento_de_calibracao_seq_populator();
DROP POLICY IF EXISTS evento_calibracao_tenant_isolation_insert ON evento_de_calibracao;
DROP POLICY IF EXISTS evento_calibracao_tenant_isolation_delete ON evento_de_calibracao;
DROP POLICY IF EXISTS evento_calibracao_tenant_isolation_update ON evento_de_calibracao;
DROP POLICY IF EXISTS evento_calibracao_tenant_isolation_select ON evento_de_calibracao;
ALTER TABLE evento_de_calibracao DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0008_recepcao_e_medicao_controle'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDeCalibracao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequencia_local', models.BigIntegerField(help_text='Sequencia 1, 2, 3 ... por (tenant_id, calibracao_id). Populado por trigger BEFORE INSERT (ADR-0065 INV-CAL-AUD-002). UNIQUE (tenant, calibracao, sequencia_local).')),
                ('tipo', models.CharField(choices=[('CalibracaoRecepcionada', 'Calibracao Recepcionada'), ('ConfiguracaoSalva', 'Configuracao Salva'), ('LeituraRegistrada', 'Leitura Registrada'), ('LeituraCorrigida', 'Leitura Corrigida'), ('IncertezaCalculada', 'Incerteza Calculada'), ('ConformidadeAvaliada', 'Conformidade Avaliada'), ('RevisaoAprovada', 'Revisao Aprovada'), ('RevisaoRejeitada', 'Revisao Rejeitada'), ('SegundaConferenciaAprovada', 'Segunda Conferencia Aprovada'), ('NCAberta', 'NC Aberta'), ('NCResolvida', 'NC Resolvida'), ('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada'), ('Cancelada', 'Cancelada'), ('SubcontratadaParaLab', 'Subcontratada para Lab'), ('RecebidaDoSubcontratado', 'Recebida do Subcontratado'), ('EpUnacceptableImpactoCriado', 'EP Unacceptable Impacto Criado'), ('CondicoesForaOverride', 'Condicoes Fora Override (P2 Qualidade)'), ('ReclamacaoAberta', 'Reclamacao Aberta'), ('ReclamacaoRespondida', 'Reclamacao Respondida'), ('AceiteRegraDecisaoConcedido', 'Aceite Regra Decisao Concedido'), ('OverrideRegraDecisaoCriado', 'Override Regra Decisao Criado'), ('BackupExecutado', 'Backup Metrologico Executado')], max_length=40)),
                ('payload_sanitizado', models.JSONField(help_text='Sanitizado via sanitizar_payload_evento_calibracao() — G2 dossie pre-M4 + SEC-SANITIZE-001 + INV-CAL-AUD-001.')),
                ('evento_anterior_hash', models.CharField(blank=True, default='', help_text='Hash do evento anterior na cadeia desta calibracao. Vazio no 1o evento. Calculado via advisory lock no append.', max_length=80)),
                ('evento_hash', models.CharField(help_text='HashVersionado v<NN>$<base64> (ADR-0064) — HMAC do payload + evento_anterior_hash + tenant_id + occurred_at.', max_length=80)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('actor_user_id', models.UUIDField(help_text='Quem disparou (auditoria — UUID cru aqui ok porque pareado com hash).')),
                ('actor_user_id_hash', models.CharField(help_text='HashVersionado do actor (ADR-0064).', max_length=80)),
                ('occurred_at', models.DateTimeField(help_text='Momento do evento (relogio NTP-sincronizado).')),
                ('calibracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='calibracao.calibracao')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_calibracao', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Evento de Calibracao',
                'verbose_name_plural': 'Eventos de Calibracao',
                'db_table': 'evento_de_calibracao',
                'ordering': ['calibracao', 'sequencia_local'],
                'indexes': [models.Index(fields=['tenant', 'calibracao', 'occurred_at'], name='evcal_tenant_cal_occ_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'calibracao', 'sequencia_local'), name='uq_evento_calibracao_seq')],
            },
        ),
        migrations.RunSQL(sql=RLS_TRIGGERS_FORWARD, reverse_sql=RLS_TRIGGERS_REVERSE),
    ]
