# Generated by Django 5.2.14 on 2026-05-25 + edicao manual para acrescentar
# RLS + triggers + CHECK XOR origem + INV-CAL-NC-002/003 transicao.
#
# T-CAL-012 NaoConformidade (cl. 7.10 + cl. 8.7 + P-CAL-R6 RBC + P-CAL-A2).
# T-CAL-013 AnaliseImpactoNCProficiencia (cl. 7.7.2 + P-CAL-T8 reescrito).
# T-CAL-014 PlanoAcaoProficienciaWarning (P-CAL-R8 RBC — |z| (2, 3]).
#
# # audit-immutability: as 3 entidades WORM/transitionais
# # tests-coverage: tests/regressao/test_inv_cal_nc_002_003.py (T-CAL-149)

import django.db.models.deletion
import uuid
from django.db import migrations, models


RLS_TRIGGERS_FORWARD = """
-- =============================================================
-- nao_conformidade - RLS + estado-maquina + CHECK XOR + INV-CAL-NC-002/003
-- =============================================================
ALTER TABLE nao_conformidade ENABLE ROW LEVEL SECURITY;
ALTER TABLE nao_conformidade FORCE ROW LEVEL SECURITY;

CREATE POLICY nao_conformidade_tenant_isolation_select ON nao_conformidade
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY nao_conformidade_tenant_isolation_update ON nao_conformidade
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY nao_conformidade_tenant_isolation_delete ON nao_conformidade
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY nao_conformidade_tenant_isolation_insert ON nao_conformidade
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- origem mutuamente exclusiva (XOR)
ALTER TABLE nao_conformidade ADD CONSTRAINT ck_nc_origem_xor
    CHECK (
        (calibracao_id IS NOT NULL AND origem_proficiencia_id IS NULL)
        OR (calibracao_id IS NULL AND origem_proficiencia_id IS NOT NULL)
    );

-- INV-CAL-NC-002 + INV-CAL-NC-003 + parcial WORM via trigger
CREATE OR REPLACE FUNCTION nao_conformidade_transicao_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
           OR NEW.descricao_hash IS DISTINCT FROM OLD.descricao_hash
           OR NEW.calibracao_id IS DISTINCT FROM OLD.calibracao_id
           OR NEW.origem_proficiencia_id IS DISTINCT FROM OLD.origem_proficiencia_id
           OR NEW.correlation_id IS DISTINCT FROM OLD.correlation_id
        THEN
            RAISE EXCEPTION
                'INV-CAL-NC-001: NaoConformidade campos forensicos imutaveis (tenant, descricao_hash, origem, correlation_id).';
        END IF;
        IF NEW.estado = 'ACAO_EXECUTADA' AND OLD.estado <> 'ACAO_EXECUTADA' THEN
            IF NEW.decisao_continuar_ou_parar = 'A_DEFINIR' THEN
                RAISE EXCEPTION
                    'INV-CAL-NC-002: transicao -> ACAO_EXECUTADA exige decisao_continuar_ou_parar definida (cl. 7.10.1).';
            END IF;
            IF NEW.decisao_continuar_ou_parar = 'PARAR_TRABALHO'
               AND NEW.cliente_notificado_em IS NULL THEN
                RAISE EXCEPTION
                    'INV-CAL-NC-003: decisao=PARAR_TRABALHO exige cliente_notificado_em NOT NULL antes de ACAO_EXECUTADA (cl. 7.10.2).';
            END IF;
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-NC-001: NaoConformidade nao pode ser deletada (audit imutavel — cl. 7.10/8.7).';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER nao_conformidade_transicao_trg
    BEFORE UPDATE OR DELETE ON nao_conformidade
    FOR EACH ROW
    EXECUTE FUNCTION nao_conformidade_transicao_check();

-- =============================================================
-- analise_impacto_nc_proficiencia - RLS + WORM parcial (M5 preenche depois)
-- =============================================================
ALTER TABLE analise_impacto_nc_proficiencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE analise_impacto_nc_proficiencia FORCE ROW LEVEL SECURITY;

CREATE POLICY analise_impacto_tenant_isolation_select ON analise_impacto_nc_proficiencia
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY analise_impacto_tenant_isolation_update ON analise_impacto_nc_proficiencia
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY analise_impacto_tenant_isolation_delete ON analise_impacto_nc_proficiencia
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY analise_impacto_tenant_isolation_insert ON analise_impacto_nc_proficiencia
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

CREATE OR REPLACE FUNCTION analise_impacto_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
           OR NEW.rodada_proficiencia_id IS DISTINCT FROM OLD.rodada_proficiencia_id
           OR NEW.janela_inicio IS DISTINCT FROM OLD.janela_inicio
           OR NEW.janela_fim IS DISTINCT FROM OLD.janela_fim
           OR NEW.criada_em IS DISTINCT FROM OLD.criada_em
           OR NEW.correlation_id IS DISTINCT FROM OLD.correlation_id
        THEN
            RAISE EXCEPTION
                'INV-CAL-WORM-001: AnaliseImpactoNCProficiencia campos forensicos imutaveis (so M5 preenche certificados_no_periodo + decisao + status).';
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: AnaliseImpactoNCProficiencia nao pode ser deletada.';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER analise_impacto_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON analise_impacto_nc_proficiencia
    FOR EACH ROW
    EXECUTE FUNCTION analise_impacto_anti_mutation_check();

-- =============================================================
-- plano_acao_proficiencia_warning - RLS + WORM full
-- =============================================================
ALTER TABLE plano_acao_proficiencia_warning ENABLE ROW LEVEL SECURITY;
ALTER TABLE plano_acao_proficiencia_warning FORCE ROW LEVEL SECURITY;

CREATE POLICY paw_tenant_isolation_select ON plano_acao_proficiencia_warning
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY paw_tenant_isolation_update ON plano_acao_proficiencia_warning
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY paw_tenant_isolation_delete ON plano_acao_proficiencia_warning
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY paw_tenant_isolation_insert ON plano_acao_proficiencia_warning
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

CREATE OR REPLACE FUNCTION plano_acao_pt_warning_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: PlanoAcaoProficienciaWarning eh imutavel pos-INSERT.';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: PlanoAcaoProficienciaWarning nao pode ser deletado.';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER plano_acao_pt_warning_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON plano_acao_proficiencia_warning
    FOR EACH ROW
    EXECUTE FUNCTION plano_acao_pt_warning_anti_mutation_check();
"""

RLS_TRIGGERS_REVERSE = """
DROP TRIGGER IF EXISTS plano_acao_pt_warning_anti_mutation_trg ON plano_acao_proficiencia_warning;
DROP FUNCTION IF EXISTS plano_acao_pt_warning_anti_mutation_check();
DROP POLICY IF EXISTS paw_tenant_isolation_insert ON plano_acao_proficiencia_warning;
DROP POLICY IF EXISTS paw_tenant_isolation_delete ON plano_acao_proficiencia_warning;
DROP POLICY IF EXISTS paw_tenant_isolation_update ON plano_acao_proficiencia_warning;
DROP POLICY IF EXISTS paw_tenant_isolation_select ON plano_acao_proficiencia_warning;
ALTER TABLE plano_acao_proficiencia_warning DISABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS analise_impacto_anti_mutation_trg ON analise_impacto_nc_proficiencia;
DROP FUNCTION IF EXISTS analise_impacto_anti_mutation_check();
DROP POLICY IF EXISTS analise_impacto_tenant_isolation_insert ON analise_impacto_nc_proficiencia;
DROP POLICY IF EXISTS analise_impacto_tenant_isolation_delete ON analise_impacto_nc_proficiencia;
DROP POLICY IF EXISTS analise_impacto_tenant_isolation_update ON analise_impacto_nc_proficiencia;
DROP POLICY IF EXISTS analise_impacto_tenant_isolation_select ON analise_impacto_nc_proficiencia;
ALTER TABLE analise_impacto_nc_proficiencia DISABLE ROW LEVEL SECURITY;

ALTER TABLE nao_conformidade DROP CONSTRAINT IF EXISTS ck_nc_origem_xor;
DROP TRIGGER IF EXISTS nao_conformidade_transicao_trg ON nao_conformidade;
DROP FUNCTION IF EXISTS nao_conformidade_transicao_check();
DROP POLICY IF EXISTS nao_conformidade_tenant_isolation_insert ON nao_conformidade;
DROP POLICY IF EXISTS nao_conformidade_tenant_isolation_delete ON nao_conformidade;
DROP POLICY IF EXISTS nao_conformidade_tenant_isolation_update ON nao_conformidade;
DROP POLICY IF EXISTS nao_conformidade_tenant_isolation_select ON nao_conformidade;
ALTER TABLE nao_conformidade DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0009_evento_de_calibracao'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseImpactoNCProficiencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rodada_proficiencia_id', models.UUIDField(help_text='FK RodadaProficiencia (db_constraint=False).')),
                ('janela_inicio', models.DateTimeField(help_text='Inicio da janela (ultima PT PASSED). Se nunca PT PASSED, default = tenant.created_at (documentado em INV-CAL-NC-PT-001).')),
                ('janela_fim', models.DateTimeField(help_text='Fim da janela (PT atual UNACCEPTABLE).')),
                ('certificados_no_periodo', models.JSONField(blank=True, help_text='Preenchido em batch pelo M5 quando consumir Calibracao.EpUnacceptableImpactoCriado. NULL ate M5 processar.', null=True)),
                ('gestor_qualidade_decisao', models.JSONField(blank=True, help_text='Array por cert: {cert_id, decisao: RECALL | SUSPENSAO | SEM_IMPACTO, justificativa_hash}. NULL ate gestor decidir.', null=True)),
                ('status', models.CharField(choices=[('RECALL_PENDENTE_M5', 'Recall pendente M5 (certificados_no_periodo NULL)'), ('PROCESSADO', 'Processado (M5 preencheu certs_no_periodo + decisao)'), ('ARQUIVADO', 'Arquivado')], default='RECALL_PENDENTE_M5', max_length=30)),
                ('decidida_em', models.DateTimeField(blank=True, null=True)),
                ('decidida_por_user_id', models.UUIDField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_impacto_nc', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Analise de Impacto NC Proficiencia',
                'verbose_name_plural': 'Analises de Impacto NC Proficiencia',
                'db_table': 'analise_impacto_nc_proficiencia',
                'ordering': ['-criada_em'],
                'indexes': [models.Index(fields=['tenant', 'rodada_proficiencia_id'], name='aimpnc_tenant_rod_idx')],
            },
        ),
        migrations.CreateModel(
            name='NaoConformidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origem_proficiencia_id', models.UUIDField(blank=True, help_text='FK AnaliseImpactoNCProficiencia (db_constraint=False).', null=True)),
                ('descricao_canonicalizada', models.TextField(help_text='>=30 chars + anti-PII INV-CAL-TXT-001 (regex saude P-CAL-A2) + INV-DOC-CANON-001.')),
                ('descricao_hash', models.CharField(help_text='HashVersionado v<NN>$<base64> (ADR-0064).', max_length=80)),
                ('estado', models.CharField(choices=[('CONTIDA', 'Contida'), ('ACAO_CORRETIVA_DEFINIDA', 'Acao corretiva definida'), ('ACAO_EXECUTADA', 'Acao executada'), ('EFICACIA_VERIFICADA', 'Eficacia verificada'), ('FECHADA', 'Fechada'), ('REABERTA', 'Reaberta (volta a CONTIDA — cl. 8.7.2)')], default='CONTIDA', max_length=30)),
                ('causa_raiz_canonicalizada', models.TextField(blank=True, default='', help_text='Preenchida em ACAO_CORRETIVA_DEFINIDA.')),
                ('causa_raiz_hash', models.CharField(blank=True, default='', max_length=80)),
                ('acao_corretiva_descricao_hash', models.CharField(blank=True, default='', max_length=80)),
                ('acao_corretiva_tipo', models.CharField(blank=True, choices=[('RE_EXECUTAR', 'Re-executar (calibracao do zero)'), ('AJUSTE_ADMINISTRATIVO', 'Ajuste administrativo')], default='', help_text='NOVO-2 RBC R2 — explicito sobre o tipo de acao.', max_length=30)),
                ('acao_executada_em', models.DateTimeField(blank=True, null=True)),
                ('eficacia_verificada_em', models.DateTimeField(blank=True, null=True)),
                ('eficacia_verificada_por_user_id', models.UUIDField(blank=True, null=True)),
                ('responsavel_acao_user_id', models.UUIDField(blank=True, help_text='Zona quente (≤90d). Job nc-responsavel-pseudonimizacao zera UUID apos prazo (anti-stalking pos retencao 25a).', null=True)),
                ('responsavel_acao_user_id_hash', models.CharField(help_text='HashVersionado (ADR-0064). Sempre presente.', max_length=80)),
                ('decisao_continuar_ou_parar', models.CharField(choices=[('PARAR_TRABALHO', 'Parar trabalho'), ('CONTINUAR_COM_CONTROLE', 'Continuar com controle'), ('A_DEFINIR', 'A definir')], default='A_DEFINIR', help_text='INV-CAL-NC-002: obrigatorio (!= A_DEFINIR) antes de transitar para ACAO_EXECUTADA.', max_length=30)),
                ('cliente_notificado_em', models.DateTimeField(blank=True, help_text='INV-CAL-NC-003: NOT NULL quando decisao_continuar_ou_parar = PARAR_TRABALHO.', null=True)),
                ('cliente_notificado_via', models.CharField(blank=True, choices=[('EMAIL_PORTAL', 'E-mail / portal cliente'), ('A3_ASSINATURA', 'A3 com assinatura'), ('TERMO_PRESENCIAL', 'Termo presencial')], default='', max_length=20)),
                ('cliente_notificado_documento_id', models.UUIDField(blank=True, null=True)),
                ('autorizacao_retomada_user_id', models.UUIDField(blank=True, null=True)),
                ('autorizacao_retomada_em', models.DateTimeField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('calibracao', models.ForeignKey(blank=True, help_text='NULL quando NC originada de Proficiencia via AnaliseImpactoNCProficiencia (mutuamente exclusivo).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='naoconformidades', to='calibracao.calibracao')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='naoconformidades', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Nao-Conformidade',
                'verbose_name_plural': 'Nao-Conformidades',
                'db_table': 'nao_conformidade',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['tenant', 'estado'], name='nc_tenant_estado_idx'), models.Index(fields=['tenant', 'calibracao'], name='nc_tenant_cal_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanoAcaoProficienciaWarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rodada_proficiencia_id', models.UUIDField(help_text='FK RodadaProficiencia.')),
                ('escore_z', models.DecimalField(decimal_places=3, help_text='|z|>2 e <=3 (WARNING). |z|>3 vai pra AnaliseImpactoNCProficiencia.', max_digits=5)),
                ('causa_investigada_canonicalizada', models.TextField(help_text='>=50 chars + anti-PII + INV-DOC-CANON-001.')),
                ('causa_investigada_hash', models.CharField(max_length=80)),
                ('acao_proporcional_canonicalizada', models.TextField()),
                ('acao_proporcional_hash', models.CharField(max_length=80)),
                ('eficacia_futura_em', models.DateTimeField(blank=True, help_text='Quando eficacia da acao sera verificada.', null=True)),
                ('responsavel_user_id_hash', models.CharField(max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_acao_pt_warning', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Plano Acao Proficiencia WARNING',
                'verbose_name_plural': 'Planos Acao Proficiencia WARNING',
                'db_table': 'plano_acao_proficiencia_warning',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tenant', 'rodada_proficiencia_id'], name='paw_tenant_rod_idx')],
            },
        ),
        migrations.RunSQL(sql=RLS_TRIGGERS_FORWARD, reverse_sql=RLS_TRIGGERS_REVERSE),
    ]
