# Generated by Django 5.2.14 on 2026-05-25 + edicao manual para
# acrescentar RLS + triggers + CHECK constraints (INV-CAL-SUBC-001/005/006
# + INV-CAL-DEC-006 + INV-CAL-WORM-001 + INV-CAL-CONT-001 + ADR-0030/0031).
#
# T-CAL-015 LaboratorioSubcontratado (cl. 6.6 + US-CAL-017 + P-CAL-R5 RBC).
# T-CAL-016 AceiteSubcontratacao (US-CAL-017 + P-CAL-A1/A6 advogado).
# T-CAL-017 AceiteRegraDecisao (ADR-0024 revisado + P-CAL-R3 RBC + P-CAL-A3).
# T-CAL-021 AvaliacaoPeriodicaSubcontratado (cl. 6.6.2 + P-CAL-R5 RBC).
#
# # audit-immutability: 4 entidades WORM/transitionais
# # rls-policy: inline (mesma migration)
# # tests-coverage: tests/regressao/test_inv_cal_subc.py (T-CAL-149+)

import django.db.models.deletion
import uuid
from django.db import migrations, models


RLS_TRIGGERS_FORWARD = """
-- =============================================================
-- laboratorio_subcontratado — RLS + CHECK pais/dpa + soft-delete Padrao C
-- =============================================================
ALTER TABLE laboratorio_subcontratado ENABLE ROW LEVEL SECURITY;
ALTER TABLE laboratorio_subcontratado FORCE ROW LEVEL SECURITY;

CREATE POLICY labsub_tenant_isolation_select ON laboratorio_subcontratado
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY labsub_tenant_isolation_update ON laboratorio_subcontratado
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY labsub_tenant_isolation_delete ON laboratorio_subcontratado
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY labsub_tenant_isolation_insert ON laboratorio_subcontratado
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- P-CAL-A1 advogado — transferencia internacional exige DPA clausulas SCC
ALTER TABLE laboratorio_subcontratado ADD CONSTRAINT ck_labsub_dpa_internacional
    CHECK (
        pais = 'BR'
        OR (pais <> 'BR' AND dpa_clausulas_internacionais_id IS NOT NULL)
    );

-- ADR-0030 — vigencia canonica coerente
ALTER TABLE laboratorio_subcontratado ADD CONSTRAINT ck_labsub_vigencia_coerente
    CHECK (vigencia_fim IS NULL OR vigencia_fim > vigencia_inicio);

-- =============================================================
-- aceite_subcontratacao — RLS + CHECK touch + WORM
-- =============================================================
ALTER TABLE aceite_subcontratacao ENABLE ROW LEVEL SECURITY;
ALTER TABLE aceite_subcontratacao FORCE ROW LEVEL SECURITY;

CREATE POLICY aceitesub_tenant_isolation_select ON aceite_subcontratacao
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY aceitesub_tenant_isolation_update ON aceite_subcontratacao
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY aceitesub_tenant_isolation_delete ON aceite_subcontratacao
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY aceitesub_tenant_isolation_insert ON aceite_subcontratacao
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- P-CAL-A6 advogado — TOUCH exige declaracao alto risco
ALTER TABLE aceite_subcontratacao ADD CONSTRAINT ck_aceitesub_touch_declaracao
    CHECK (
        assinatura_modo = 'A3'
        OR (assinatura_modo = 'TOUCH' AND declaracao_aceite_touch_alto_risco_id IS NOT NULL)
    );

CREATE OR REPLACE FUNCTION aceite_subcontratacao_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: AceiteSubcontratacao eh imutavel pos-INSERT (US-CAL-017).';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: AceiteSubcontratacao nao pode ser deletado (audit imutavel).';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER aceite_subcontratacao_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON aceite_subcontratacao
    FOR EACH ROW
    EXECUTE FUNCTION aceite_subcontratacao_anti_mutation_check();

-- =============================================================
-- aceite_regra_decisao — RLS + WORM (ADR-0024 revisado)
-- =============================================================
ALTER TABLE aceite_regra_decisao ENABLE ROW LEVEL SECURITY;
ALTER TABLE aceite_regra_decisao FORCE ROW LEVEL SECURITY;

CREATE POLICY aceiterd_tenant_isolation_select ON aceite_regra_decisao
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY aceiterd_tenant_isolation_update ON aceite_regra_decisao
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY aceiterd_tenant_isolation_delete ON aceite_regra_decisao
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY aceiterd_tenant_isolation_insert ON aceite_regra_decisao
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- nivel_confianca dentro de [0.80, 0.99]
ALTER TABLE aceite_regra_decisao ADD CONSTRAINT ck_aceiterd_nivel_confianca
    CHECK (nivel_confianca_acordado BETWEEN 0.80 AND 0.99);

CREATE OR REPLACE FUNCTION aceite_regra_decisao_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: AceiteRegraDecisao eh imutavel pos-INSERT (ADR-0024).';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: AceiteRegraDecisao nao pode ser deletado.';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER aceite_regra_decisao_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON aceite_regra_decisao
    FOR EACH ROW
    EXECUTE FUNCTION aceite_regra_decisao_anti_mutation_check();

-- =============================================================
-- avaliacao_periodica_subcontratado — RLS + WORM (P-CAL-R5 RBC)
-- =============================================================
ALTER TABLE avaliacao_periodica_subcontratado ENABLE ROW LEVEL SECURITY;
ALTER TABLE avaliacao_periodica_subcontratado FORCE ROW LEVEL SECURITY;

CREATE POLICY avalsub_tenant_isolation_select ON avaliacao_periodica_subcontratado
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY avalsub_tenant_isolation_update ON avaliacao_periodica_subcontratado
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY avalsub_tenant_isolation_delete ON avaliacao_periodica_subcontratado
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY avalsub_tenant_isolation_insert ON avaliacao_periodica_subcontratado
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

ALTER TABLE avaliacao_periodica_subcontratado ADD CONSTRAINT ck_avalsub_score
    CHECK (score BETWEEN 0 AND 10);

CREATE OR REPLACE FUNCTION avaliacao_periodica_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: AvaliacaoPeriodicaSubcontratado eh imutavel pos-INSERT (cl. 6.6.2).';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: AvaliacaoPeriodicaSubcontratado nao pode ser deletado.';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER avaliacao_periodica_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON avaliacao_periodica_subcontratado
    FOR EACH ROW
    EXECUTE FUNCTION avaliacao_periodica_anti_mutation_check();
"""

RLS_TRIGGERS_REVERSE = """
DROP TRIGGER IF EXISTS avaliacao_periodica_anti_mutation_trg ON avaliacao_periodica_subcontratado;
DROP FUNCTION IF EXISTS avaliacao_periodica_anti_mutation_check();
ALTER TABLE avaliacao_periodica_subcontratado DROP CONSTRAINT IF EXISTS ck_avalsub_score;
DROP POLICY IF EXISTS avalsub_tenant_isolation_insert ON avaliacao_periodica_subcontratado;
DROP POLICY IF EXISTS avalsub_tenant_isolation_delete ON avaliacao_periodica_subcontratado;
DROP POLICY IF EXISTS avalsub_tenant_isolation_update ON avaliacao_periodica_subcontratado;
DROP POLICY IF EXISTS avalsub_tenant_isolation_select ON avaliacao_periodica_subcontratado;
ALTER TABLE avaliacao_periodica_subcontratado DISABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS aceite_regra_decisao_anti_mutation_trg ON aceite_regra_decisao;
DROP FUNCTION IF EXISTS aceite_regra_decisao_anti_mutation_check();
ALTER TABLE aceite_regra_decisao DROP CONSTRAINT IF EXISTS ck_aceiterd_nivel_confianca;
DROP POLICY IF EXISTS aceiterd_tenant_isolation_insert ON aceite_regra_decisao;
DROP POLICY IF EXISTS aceiterd_tenant_isolation_delete ON aceite_regra_decisao;
DROP POLICY IF EXISTS aceiterd_tenant_isolation_update ON aceite_regra_decisao;
DROP POLICY IF EXISTS aceiterd_tenant_isolation_select ON aceite_regra_decisao;
ALTER TABLE aceite_regra_decisao DISABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS aceite_subcontratacao_anti_mutation_trg ON aceite_subcontratacao;
DROP FUNCTION IF EXISTS aceite_subcontratacao_anti_mutation_check();
ALTER TABLE aceite_subcontratacao DROP CONSTRAINT IF EXISTS ck_aceitesub_touch_declaracao;
DROP POLICY IF EXISTS aceitesub_tenant_isolation_insert ON aceite_subcontratacao;
DROP POLICY IF EXISTS aceitesub_tenant_isolation_delete ON aceite_subcontratacao;
DROP POLICY IF EXISTS aceitesub_tenant_isolation_update ON aceite_subcontratacao;
DROP POLICY IF EXISTS aceitesub_tenant_isolation_select ON aceite_subcontratacao;
ALTER TABLE aceite_subcontratacao DISABLE ROW LEVEL SECURITY;

ALTER TABLE laboratorio_subcontratado DROP CONSTRAINT IF EXISTS ck_labsub_vigencia_coerente;
ALTER TABLE laboratorio_subcontratado DROP CONSTRAINT IF EXISTS ck_labsub_dpa_internacional;
DROP POLICY IF EXISTS labsub_tenant_isolation_insert ON laboratorio_subcontratado;
DROP POLICY IF EXISTS labsub_tenant_isolation_delete ON laboratorio_subcontratado;
DROP POLICY IF EXISTS labsub_tenant_isolation_update ON laboratorio_subcontratado;
DROP POLICY IF EXISTS labsub_tenant_isolation_select ON laboratorio_subcontratado;
ALTER TABLE laboratorio_subcontratado DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0010_nc_proficiencia_planoacao'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratorioSubcontratado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razao_social_hash', models.CharField(help_text='HashVersionado v<NN>$<base64> (ADR-0064).', max_length=80)),
                ('razao_social_key_id', models.CharField(help_text='ID chave KMS p/ razao social cleartext (off-band).', max_length=40)),
                ('cnpj_hash', models.CharField(max_length=80)),
                ('cnpj_key_id', models.CharField(max_length=40)),
                ('credenciamento_atual', models.CharField(help_text="Ex: 'CGCRE-CAL-0123' (codigo acreditacao CGCRE).", max_length=50)),
                ('acreditacoes_vigentes', models.JSONField(help_text='Array [{grandeza, faixa_min, faixa_max, validade}]. Snapshot consultado em subcontratarCalibracao (US-CAL-017).')),
                ('contato_comercial_hash', models.CharField(max_length=80)),
                ('contato_tecnico_hash', models.CharField(max_length=80)),
                ('dpa_versao', models.CharField(help_text='Versao DPA assinada (cl. 4.7 ISO 17025).', max_length=20)),
                ('criterio_selecao_documento_id', models.UUIDField(blank=True, help_text='FK criterio-selecao-subcontratado-v1.0.md (REQUER OAB).', null=True)),
                ('ultima_avaliacao_periodica_em', models.DateTimeField(blank=True, null=True)),
                ('proxima_avaliacao_periodica_em', models.DateTimeField(help_text='Default vigencia_inicio + 12 meses (cl. 6.6.2).')),
                ('score_avaliacao_atual', models.DecimalField(blank=True, decimal_places=1, help_text='0-10 (avaliacao periodica).', max_digits=3, null=True)),
                ('avaliado_por_user_id', models.UUIDField(blank=True, null=True)),
                ('pais', models.CharField(default='BR', help_text='ISO 3166-1 alpha-2 (P-CAL-A1 transferencia internacional).', max_length=2)),
                ('dpa_clausulas_internacionais_id', models.UUIDField(blank=True, help_text="NOT NULL quando pais != 'BR' (CHECK na migration).", null=True)),
                ('vigencia_inicio', models.DateTimeField()),
                ('vigencia_fim', models.DateTimeField(blank=True, null=True)),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratorios_subcontratados', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Laboratorio Subcontratado',
                'verbose_name_plural': 'Laboratorios Subcontratados',
                'db_table': 'laboratorio_subcontratado',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoPeriodicaSubcontratado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avaliado_em', models.DateTimeField()),
                ('avaliado_por_user_id_hash', models.CharField(help_text='HashVersionado (ADR-0064) — gerente qualidade.', max_length=80)),
                ('score', models.DecimalField(decimal_places=1, help_text='0-10 (criterios cl. 6.6.2).', max_digits=3)),
                ('criterios_aplicados_json', models.JSONField(help_text='Snapshot do criterio-selecao-subcontratado-v1.0.md com marcacoes [aprovado|pendente|nao_atende].')),
                ('parecer_canonicalizado', models.TextField(help_text='>=100 chars + anti-PII + INV-DOC-CANON-001.')),
                ('parecer_hash', models.CharField(max_length=80)),
                ('decisao', models.CharField(choices=[('MANTER', 'Manter (subcontratado aprovado)'), ('ACOMPANHAMENTO', 'Manter com acompanhamento (score 6-8)'), ('DESCREDENCIAR', 'Descredenciar (score <6 ou nc grave)')], max_length=20)),
                ('proxima_avaliacao_em', models.DateTimeField(help_text='Default = avaliado_em + 12 meses (cl. 6.6.2).')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_subcontratado', to='tenant.tenant')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_periodicas', to='calibracao.laboratoriosubcontratado')),
            ],
            options={
                'verbose_name': 'Avaliacao Periodica Subcontratado',
                'verbose_name_plural': 'Avaliacoes Periodicas Subcontratado',
                'db_table': 'avaliacao_periodica_subcontratado',
                'ordering': ['-avaliado_em'],
            },
        ),
        migrations.CreateModel(
            name='AceiteRegraDecisao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_referencia_hash', models.CharField(help_text='HashVersionado cliente_id (ADR-0064 + ADR-0032).', max_length=80)),
                ('regra_decisao_escolhida', models.CharField(choices=[('ACEITACAO_SIMPLES', 'Aceitacao simples (ILAC G8 §4.2)'), ('BANDA_GUARDA_30', 'Banda de guarda 30% (ILAC G8 §4.4)'), ('RISCO_COMPARTILHADO', 'Risco compartilhado (ILAC G8 §4.3 + JCGM 106)')], max_length=25)),
                ('escopo_aplicacao', models.CharField(choices=[('CALIBRACAO_UNICA', 'Aplica-se a esta calibracao especifica'), ('CONTRATO_GUARDA_CHUVA', 'Aplica-se ao contrato vigente (guarda-chuva)')], default='CALIBRACAO_UNICA', max_length=25)),
                ('nivel_confianca_acordado', models.DecimalField(decimal_places=4, default='0.9545', help_text='Default 95.45% (k=2). Cliente pode pedir outro nivel.', max_digits=5)),
                ('texto_canonico_id', models.UUIDField(help_text='FK aceite-regra-decisao-v1.0.md (REQUER OAB).')),
                ('texto_hash', models.CharField(max_length=80)),
                ('assinatura_modo', models.CharField(choices=[('TOUCH', 'Touch (biometria simples — exige declaracao alto-risco)'), ('A3', 'A3 (certificado ICP-Brasil)')], max_length=10)),
                ('assinatura_payload_encrypted', models.BinaryField(blank=True, null=True)),
                ('ip_hash', models.CharField(max_length=80)),
                ('concedido_em', models.DateTimeField()),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('calibracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceites_regra_decisao', to='calibracao.calibracao')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceites_regra_decisao', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Aceite Regra Decisao',
                'verbose_name_plural': 'Aceites Regra Decisao',
                'db_table': 'aceite_regra_decisao',
                'ordering': ['-concedido_em'],
                'indexes': [models.Index(fields=['tenant', 'calibracao'], name='aceiterd_tenant_cal_idx')],
            },
        ),
        migrations.CreateModel(
            name='AceiteSubcontratacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_referencia_hash', models.CharField(help_text='HashVersionado do cliente_id (ADR-0064 + ADR-0032 — preserva evidencia pos-anonimizacao).', max_length=80)),
                ('texto_canonico_id', models.UUIDField(help_text='FK aceite-subcontratacao-v1.0.md (REQUER OAB). Texto exibido ao cliente — INV-DOC-CANON-001.')),
                ('texto_hash', models.CharField(help_text='SHA-256 do texto exibido (HashVersionado).', max_length=80)),
                ('assinatura_modo', models.CharField(choices=[('TOUCH', 'Touch (biometria simples — exige declaracao alto-risco)'), ('A3', 'A3 (certificado ICP-Brasil)')], help_text='TOUCH ou A3. §16.11.', max_length=10)),
                ('assinatura_payload_encrypted', models.BinaryField(blank=True, help_text='Touch: payload cifrado com BIOMETRIA_KEY_<tenant> (INV-OS-ACEITE-BIO-001 herdado). A3: PKCS#7.', null=True)),
                ('declaracao_aceite_touch_alto_risco_id', models.UUIDField(blank=True, help_text="NOT NULL quando assinatura_modo='TOUCH' (texto canonico extra P-CAL-A6 advogado). CHECK na migration.", null=True)),
                ('consentimento_contato_id', models.UUIDField(blank=True, help_text='FK ConsentimentoContatoTecnicoCliente — NOT NULL quando contato PF PJ-empregado assina (P-CAL-A6).', null=True)),
                ('motivo_subcontratacao_canonicalizado', models.TextField(help_text='>=30 chars + anti-PII + INV-DOC-CANON-001.')),
                ('motivo_hash', models.CharField(max_length=80)),
                ('ip_hash', models.CharField(help_text='HashVersionado do IP cliente — INV-CAL-SUBC-001: IP nunca persiste cleartext.', max_length=80)),
                ('concedido_em', models.DateTimeField()),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('calibracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceites_subcontratacao', to='calibracao.calibracao')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aceites_subcontratacao', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Aceite Subcontratacao',
                'verbose_name_plural': 'Aceites Subcontratacao',
                'db_table': 'aceite_subcontratacao',
                'ordering': ['-concedido_em'],
                'indexes': [models.Index(fields=['tenant', 'calibracao'], name='acsub_tenant_cal_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='laboratoriosubcontratado',
            index=models.Index(fields=['tenant', 'cnpj_hash'], name='labsub_tenant_cnpj_idx'),
        ),
        migrations.AddIndex(
            model_name='laboratoriosubcontratado',
            index=models.Index(fields=['tenant', 'proxima_avaliacao_periodica_em'], name='labsub_tenant_proxav_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacaoperiodicasubcontratado',
            index=models.Index(fields=['tenant', 'laboratorio'], name='avalsub_tenant_lab_idx'),
        ),
        migrations.RunSQL(sql=RLS_TRIGGERS_FORWARD, reverse_sql=RLS_TRIGGERS_REVERSE),
    ]
