# Generated by Django 5.2.14 on 2026-05-25 + edicao manual para acrescentar
# RLS + triggers + CHECK constraints (INV-CAL-WORM-001 + INV-CAL-DEC-002 +
# INV-CAL-CONT-001 + INV-CAL-BACKUP-001 + LGPD art. 7+9+18).
#
# T-CAL-018 OverrideRegraDecisaoCliente (ADR-0024 + P-CAL-A3 advogado).
# T-CAL-019 ReclamacaoCalibracao (US-CAL-018 + cl. 7.9 + CDC art. 26).
# T-CAL-020 ConsentimentoContatoTecnicoCliente (P-CAL-A6 + LGPD art. 7/9/18).
# T-CAL-018b ConsentimentoFotoRecusado (P-CAL-A5 advogado).
# T-CAL-023 EventoBackupMetrologico (P-CAL-R11 RBC + cl. 7.11.6).
#
# # audit-immutability: 4 entidades WORM + 1 estado-maquina parcial (Reclamacao)
# # rls-policy: inline (mesma migration)
# # tests-coverage: tests/regressao/test_inv_cal_p3.py (T-CAL-150+)

import django.db.models.deletion
import uuid
from django.db import migrations, models


RLS_TRIGGERS_FORWARD = """
-- =============================================================
-- override_regra_decisao_cliente — RLS + WORM (ADR-0024 + P-CAL-A3)
-- =============================================================
ALTER TABLE override_regra_decisao_cliente ENABLE ROW LEVEL SECURITY;
ALTER TABLE override_regra_decisao_cliente FORCE ROW LEVEL SECURITY;

CREATE POLICY overrd_tenant_isolation_select ON override_regra_decisao_cliente
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY overrd_tenant_isolation_update ON override_regra_decisao_cliente
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY overrd_tenant_isolation_delete ON override_regra_decisao_cliente
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY overrd_tenant_isolation_insert ON override_regra_decisao_cliente
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

CREATE OR REPLACE FUNCTION override_regra_decisao_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: OverrideRegraDecisaoCliente eh imutavel pos-INSERT (ADR-0024).';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: OverrideRegraDecisaoCliente nao pode ser deletado.';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER override_regra_decisao_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON override_regra_decisao_cliente
    FOR EACH ROW
    EXECUTE FUNCTION override_regra_decisao_anti_mutation_check();

-- =============================================================
-- reclamacao_calibracao — RLS + estado-maquina + CHECK transicao
-- =============================================================
ALTER TABLE reclamacao_calibracao ENABLE ROW LEVEL SECURITY;
ALTER TABLE reclamacao_calibracao FORCE ROW LEVEL SECURITY;

CREATE POLICY reclcal_tenant_isolation_select ON reclamacao_calibracao
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY reclcal_tenant_isolation_update ON reclamacao_calibracao
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY reclcal_tenant_isolation_delete ON reclamacao_calibracao
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY reclcal_tenant_isolation_insert ON reclamacao_calibracao
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- RESPONDIDA exige decisao + respondida_em + resposta_hash
ALTER TABLE reclamacao_calibracao ADD CONSTRAINT ck_reclcal_respondida_completa
    CHECK (
        estado <> 'RESPONDIDA'
        OR (
            decisao IN ('PROCEDENTE_RECALL', 'PROCEDENTE_ERRATA', 'IMPROCEDENTE')
            AND respondida_em IS NOT NULL
            AND resposta_hash <> ''
        )
    );

-- INV-CAL-WORM-001 parcial — campos forensicos imutaveis; estado avanca
CREATE OR REPLACE FUNCTION reclamacao_calibracao_estado_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
           OR NEW.calibracao_id IS DISTINCT FROM OLD.calibracao_id
           OR NEW.certificado_id IS DISTINCT FROM OLD.certificado_id
           OR NEW.cliente_referencia_hash IS DISTINCT FROM OLD.cliente_referencia_hash
           OR NEW.relato_hash IS DISTINCT FROM OLD.relato_hash
           OR NEW.aberta_em IS DISTINCT FROM OLD.aberta_em
           OR NEW.correlation_id IS DISTINCT FROM OLD.correlation_id
        THEN
            RAISE EXCEPTION
                'INV-CAL-WORM-001: ReclamacaoCalibracao campos forensicos imutaveis (tenant, calibracao, cert, cliente, relato, aberta_em).';
        END IF;
        -- transicoes validas: RECEBIDA -> EM_ANALISE -> RESPONDIDA -> ARQUIVADA
        IF OLD.estado = 'ARQUIVADA' AND NEW.estado <> 'ARQUIVADA' THEN
            RAISE EXCEPTION
                'INV-CAL-WORM-001: ReclamacaoCalibracao ARQUIVADA eh terminal.';
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: ReclamacaoCalibracao nao pode ser deletada (audit cl. 7.9).';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER reclamacao_calibracao_estado_trg
    BEFORE UPDATE OR DELETE ON reclamacao_calibracao
    FOR EACH ROW
    EXECUTE FUNCTION reclamacao_calibracao_estado_check();

-- =============================================================
-- consentimento_contato_tecnico_cliente — RLS + WORM parcial (revogavel)
-- =============================================================
ALTER TABLE consentimento_contato_tecnico_cliente ENABLE ROW LEVEL SECURITY;
ALTER TABLE consentimento_contato_tecnico_cliente FORCE ROW LEVEL SECURITY;

CREATE POLICY conscont_tenant_isolation_select ON consentimento_contato_tecnico_cliente
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY conscont_tenant_isolation_update ON consentimento_contato_tecnico_cliente
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY conscont_tenant_isolation_delete ON consentimento_contato_tecnico_cliente
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY conscont_tenant_isolation_insert ON consentimento_contato_tecnico_cliente
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- revogado_em > concedido_em quando preenchido
ALTER TABLE consentimento_contato_tecnico_cliente ADD CONSTRAINT ck_conscont_revogacao_coerente
    CHECK (revogado_em IS NULL OR revogado_em > concedido_em);

-- INV-CAL-CONT-001 — campos forensicos imutaveis; so revogado_em + motivo podem mudar
CREATE OR REPLACE FUNCTION consentimento_contato_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
           OR NEW.cliente_referencia_hash IS DISTINCT FROM OLD.cliente_referencia_hash
           OR NEW.contato_pf_hash IS DISTINCT FROM OLD.contato_pf_hash
           OR NEW.finalidade IS DISTINCT FROM OLD.finalidade
           OR NEW.texto_canonico_id IS DISTINCT FROM OLD.texto_canonico_id
           OR NEW.texto_hash IS DISTINCT FROM OLD.texto_hash
           OR NEW.assinatura_modo IS DISTINCT FROM OLD.assinatura_modo
           OR NEW.ip_hash IS DISTINCT FROM OLD.ip_hash
           OR NEW.concedido_em IS DISTINCT FROM OLD.concedido_em
           OR NEW.correlation_id IS DISTINCT FROM OLD.correlation_id
        THEN
            RAISE EXCEPTION
                'INV-CAL-CONT-001: ConsentimentoContatoTecnicoCliente campos forensicos imutaveis pos-INSERT. So revogado_em + motivo_revogacao podem mudar (LGPD art. 18).';
        END IF;
        -- nao pode "des-revogar"
        IF OLD.revogado_em IS NOT NULL AND NEW.revogado_em IS NULL THEN
            RAISE EXCEPTION
                'INV-CAL-CONT-001: revogacao eh terminal (LGPD art. 18). Novo consentimento exige novo registro.';
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-CONT-001: ConsentimentoContatoTecnicoCliente nao pode ser deletado (audit imutavel).';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER consentimento_contato_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON consentimento_contato_tecnico_cliente
    FOR EACH ROW
    EXECUTE FUNCTION consentimento_contato_anti_mutation_check();

-- =============================================================
-- consentimento_foto_recusado — RLS + WORM (P-CAL-A5)
-- =============================================================
ALTER TABLE consentimento_foto_recusado ENABLE ROW LEVEL SECURITY;
ALTER TABLE consentimento_foto_recusado FORCE ROW LEVEL SECURITY;

CREATE POLICY consfoto_tenant_isolation_select ON consentimento_foto_recusado
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY consfoto_tenant_isolation_update ON consentimento_foto_recusado
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY consfoto_tenant_isolation_delete ON consentimento_foto_recusado
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY consfoto_tenant_isolation_insert ON consentimento_foto_recusado
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

CREATE OR REPLACE FUNCTION consentimento_foto_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: ConsentimentoFotoRecusado eh imutavel pos-INSERT (P-CAL-A5).';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-WORM-001: ConsentimentoFotoRecusado nao pode ser deletado.';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER consentimento_foto_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON consentimento_foto_recusado
    FOR EACH ROW
    EXECUTE FUNCTION consentimento_foto_anti_mutation_check();

-- =============================================================
-- evento_backup_metrologico — RLS + WORM append-only (INV-CAL-BACKUP-001)
-- =============================================================
ALTER TABLE evento_backup_metrologico ENABLE ROW LEVEL SECURITY;
ALTER TABLE evento_backup_metrologico FORCE ROW LEVEL SECURITY;

CREATE POLICY evbkmet_tenant_isolation_select ON evento_backup_metrologico
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY evbkmet_tenant_isolation_update ON evento_backup_metrologico
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY evbkmet_tenant_isolation_delete ON evento_backup_metrologico
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY evbkmet_tenant_isolation_insert ON evento_backup_metrologico
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

CREATE OR REPLACE FUNCTION evento_backup_metrologico_anti_mutation_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION
            'INV-CAL-BACKUP-001: EventoBackupMetrologico eh append-only (cl. 7.11.6).';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION
            'INV-CAL-BACKUP-001: EventoBackupMetrologico nao pode ser deletado (audit retencao 25a).';
    END IF;
    RETURN NEW;
END;
$body$;

CREATE TRIGGER evento_backup_metrologico_anti_mutation_trg
    BEFORE UPDATE OR DELETE ON evento_backup_metrologico
    FOR EACH ROW
    EXECUTE FUNCTION evento_backup_metrologico_anti_mutation_check();
"""

RLS_TRIGGERS_REVERSE = """
DROP TRIGGER IF EXISTS evento_backup_metrologico_anti_mutation_trg ON evento_backup_metrologico;
DROP FUNCTION IF EXISTS evento_backup_metrologico_anti_mutation_check();
DROP POLICY IF EXISTS evbkmet_tenant_isolation_insert ON evento_backup_metrologico;
DROP POLICY IF EXISTS evbkmet_tenant_isolation_delete ON evento_backup_metrologico;
DROP POLICY IF EXISTS evbkmet_tenant_isolation_update ON evento_backup_metrologico;
DROP POLICY IF EXISTS evbkmet_tenant_isolation_select ON evento_backup_metrologico;
ALTER TABLE evento_backup_metrologico DISABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS consentimento_foto_anti_mutation_trg ON consentimento_foto_recusado;
DROP FUNCTION IF EXISTS consentimento_foto_anti_mutation_check();
DROP POLICY IF EXISTS consfoto_tenant_isolation_insert ON consentimento_foto_recusado;
DROP POLICY IF EXISTS consfoto_tenant_isolation_delete ON consentimento_foto_recusado;
DROP POLICY IF EXISTS consfoto_tenant_isolation_update ON consentimento_foto_recusado;
DROP POLICY IF EXISTS consfoto_tenant_isolation_select ON consentimento_foto_recusado;
ALTER TABLE consentimento_foto_recusado DISABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS consentimento_contato_anti_mutation_trg ON consentimento_contato_tecnico_cliente;
DROP FUNCTION IF EXISTS consentimento_contato_anti_mutation_check();
ALTER TABLE consentimento_contato_tecnico_cliente DROP CONSTRAINT IF EXISTS ck_conscont_revogacao_coerente;
DROP POLICY IF EXISTS conscont_tenant_isolation_insert ON consentimento_contato_tecnico_cliente;
DROP POLICY IF EXISTS conscont_tenant_isolation_delete ON consentimento_contato_tecnico_cliente;
DROP POLICY IF EXISTS conscont_tenant_isolation_update ON consentimento_contato_tecnico_cliente;
DROP POLICY IF EXISTS conscont_tenant_isolation_select ON consentimento_contato_tecnico_cliente;
ALTER TABLE consentimento_contato_tecnico_cliente DISABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS reclamacao_calibracao_estado_trg ON reclamacao_calibracao;
DROP FUNCTION IF EXISTS reclamacao_calibracao_estado_check();
ALTER TABLE reclamacao_calibracao DROP CONSTRAINT IF EXISTS ck_reclcal_respondida_completa;
DROP POLICY IF EXISTS reclcal_tenant_isolation_insert ON reclamacao_calibracao;
DROP POLICY IF EXISTS reclcal_tenant_isolation_delete ON reclamacao_calibracao;
DROP POLICY IF EXISTS reclcal_tenant_isolation_update ON reclamacao_calibracao;
DROP POLICY IF EXISTS reclcal_tenant_isolation_select ON reclamacao_calibracao;
ALTER TABLE reclamacao_calibracao DISABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS override_regra_decisao_anti_mutation_trg ON override_regra_decisao_cliente;
DROP FUNCTION IF EXISTS override_regra_decisao_anti_mutation_check();
DROP POLICY IF EXISTS overrd_tenant_isolation_insert ON override_regra_decisao_cliente;
DROP POLICY IF EXISTS overrd_tenant_isolation_delete ON override_regra_decisao_cliente;
DROP POLICY IF EXISTS overrd_tenant_isolation_update ON override_regra_decisao_cliente;
DROP POLICY IF EXISTS overrd_tenant_isolation_select ON override_regra_decisao_cliente;
ALTER TABLE override_regra_decisao_cliente DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0011_cluster_subcontratacao'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimentoContatoTecnicoCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_referencia_hash', models.CharField(help_text='HashVersionado cliente_id PJ (ADR-0064 + ADR-0032).', max_length=80)),
                ('contato_pf_hash', models.CharField(help_text='HashVersionado da PF que consente (nome + email + CPF se houver).', max_length=80)),
                ('finalidade', models.CharField(choices=[('CERTIFICADO_CONTATO_TECNICO', 'Aparecer em certificado como contato tecnico'), ('SUBCONTRATACAO_CONTATO', 'Ser contatado por subcontratado em escopo da OS'), ('PORTAL_CLIENTE', 'Acesso ao portal-cliente em nome do tenant cliente PJ')], max_length=40)),
                ('texto_canonico_id', models.UUIDField(help_text='FK consentimento-contato-tecnico-v1.0.md (REQUER OAB).')),
                ('texto_hash', models.CharField(max_length=80)),
                ('assinatura_modo', models.CharField(choices=[('TOUCH', 'Touch (biometria simples — exige declaracao alto-risco)'), ('A3', 'A3 (certificado ICP-Brasil)')], max_length=10)),
                ('assinatura_payload_encrypted', models.BinaryField(blank=True, null=True)),
                ('ip_hash', models.CharField(max_length=80)),
                ('concedido_em', models.DateTimeField()),
                ('revogado_em', models.DateTimeField(blank=True, help_text='Quando titular revoga (LGPD art. 18). Bloqueia uso pos-revogacao.', null=True)),
                ('motivo_revogacao_canonicalizado', models.TextField(blank=True, default='')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimentos_contato_tecnico', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Consentimento Contato Tecnico Cliente',
                'verbose_name_plural': 'Consentimentos Contato Tecnico Cliente',
                'db_table': 'consentimento_contato_tecnico_cliente',
                'ordering': ['-concedido_em'],
                'indexes': [models.Index(fields=['tenant', 'contato_pf_hash'], name='conscont_tenant_contato_idx'), models.Index(fields=['tenant', 'revogado_em'], name='conscont_tenant_revog_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsentimentoFotoRecusado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_referencia_hash', models.CharField(help_text='HashVersionado cliente_id (ADR-0064 + ADR-0032).', max_length=80)),
                ('motivo_recusa_canonicalizado', models.TextField(help_text='>=30 chars + anti-PII + INV-DOC-CANON-001.')),
                ('motivo_recusa_hash', models.CharField(max_length=80)),
                ('texto_aviso_canonico_id', models.UUIDField(help_text='FK aviso-foto-recepcao-v1.0.md (REQUER OAB) — texto que cliente leu e recusou.')),
                ('texto_aviso_hash', models.CharField(max_length=80)),
                ('assinatura_modo', models.CharField(choices=[('TOUCH', 'Touch (biometria simples — exige declaracao alto-risco)'), ('A3', 'A3 (certificado ICP-Brasil)')], max_length=10)),
                ('assinatura_payload_encrypted', models.BinaryField(blank=True, null=True)),
                ('ip_hash', models.CharField(max_length=80)),
                ('registrado_em', models.DateTimeField()),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimentos_foto_recusado', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Consentimento Foto Recusado',
                'verbose_name_plural': 'Consentimentos Foto Recusado',
                'db_table': 'consentimento_foto_recusado',
                'ordering': ['-registrado_em'],
                'indexes': [models.Index(fields=['tenant', 'registrado_em'], name='consfoto_tenant_reg_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventoBackupMetrologico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executado_em', models.DateTimeField(help_text='Inicio da execucao do backup.')),
                ('b2_object_key', models.CharField(help_text='Backblaze B2 object key (path WORM).', max_length=512)),
                ('hash_arquivo', models.CharField(help_text='HashVersionado v<NN>$<base64> do arquivo exportado (ADR-0064).', max_length=80)),
                ('tabelas_count', models.PositiveIntegerField(help_text='Numero de tabelas exportadas (snapshot da migration vigente).')),
                ('tamanho_bytes', models.BigIntegerField(help_text='Tamanho do arquivo exportado em bytes.')),
                ('duracao_segundos', models.PositiveIntegerField()),
                ('resultado', models.CharField(choices=[('OK', 'OK (todas tabelas exportadas + hash verificado)'), ('FALHA_PARCIAL', 'Falha parcial (algumas tabelas exportadas)'), ('FALHA_TOTAL', 'Falha total (nenhuma tabela exportada — alerta P1)')], max_length=20)),
                ('mensagem_erro_canonicalizada', models.TextField(blank=True, default='', help_text='Vazio quando resultado=OK. Anti-PII + INV-DOC-CANON-001.')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_backup_metrologico', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Evento Backup Metrologico',
                'verbose_name_plural': 'Eventos Backup Metrologico',
                'db_table': 'evento_backup_metrologico',
                'ordering': ['-executado_em'],
                'indexes': [models.Index(fields=['tenant', 'executado_em'], name='evbkmet_tenant_exec_idx'), models.Index(fields=['tenant', 'resultado'], name='evbkmet_tenant_result_idx')],
            },
        ),
        migrations.CreateModel(
            name='OverrideRegraDecisaoCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente_referencia_hash', models.CharField(help_text='HashVersionado cliente_id (ADR-0064 + ADR-0032).', max_length=80)),
                ('regra_escolhida', models.CharField(choices=[('ACEITACAO_SIMPLES', 'Aceitacao simples (ILAC G8 §4.2)'), ('BANDA_GUARDA_30', 'Banda de guarda 30% (ILAC G8 §4.4)'), ('RISCO_COMPARTILHADO', 'Risco compartilhado (ILAC G8 §4.3 + JCGM 106)')], help_text='Regra contratualmente acordada (sobrescreve default tenant).', max_length=25)),
                ('regra_default_tenant', models.CharField(choices=[('ACEITACAO_SIMPLES', 'Aceitacao simples (ILAC G8 §4.2)'), ('BANDA_GUARDA_30', 'Banda de guarda 30% (ILAC G8 §4.4)'), ('RISCO_COMPARTILHADO', 'Risco compartilhado (ILAC G8 §4.3 + JCGM 106)')], help_text='Snapshot da regra default do tenant no momento do override.', max_length=25)),
                ('contrato_clausula_id', models.UUIDField(help_text='FK clausula contratual que autoriza o override (documento-cliente cl. 7.1.3).')),
                ('justificativa_canonicalizada', models.TextField(help_text='>=50 chars + anti-PII + INV-DOC-CANON-001.')),
                ('justificativa_hash', models.CharField(max_length=80)),
                ('aprovado_por_user_id_hash', models.CharField(help_text='HashVersionado (ADR-0064) — gerente qualidade aprova.', max_length=80)),
                ('concedido_em', models.DateTimeField()),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('calibracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overrides_regra_decisao', to='calibracao.calibracao')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overrides_regra_decisao', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Override Regra Decisao Cliente',
                'verbose_name_plural': 'Overrides Regra Decisao Cliente',
                'db_table': 'override_regra_decisao_cliente',
                'ordering': ['-concedido_em'],
                'indexes': [models.Index(fields=['tenant', 'calibracao'], name='overrd_tenant_cal_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReclamacaoCalibracao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificado_id', models.UUIDField(help_text='FK Certificado (Marco 5 — db_constraint=False).')),
                ('cliente_referencia_hash', models.CharField(help_text='HashVersionado cliente_id (ADR-0064 + ADR-0032).', max_length=80)),
                ('relato_canonicalizado', models.TextField(help_text='>=100 chars + anti-PII (INV-CAL-TXT-001) + INV-DOC-CANON-001.')),
                ('relato_hash', models.CharField(max_length=80)),
                ('estado', models.CharField(choices=[('RECEBIDA', 'Recebida (registrada via portal cliente)'), ('EM_ANALISE', 'Em analise (RT independente atribuido)'), ('RESPONDIDA', 'Respondida (decisao registrada)'), ('ARQUIVADA', 'Arquivada (pos prazo CDC)')], default='RECEBIDA', max_length=20)),
                ('rt_atribuido_user_id_hash', models.CharField(blank=True, default='', help_text='HashVersionado — preenchido em EM_ANALISE.', max_length=80)),
                ('resposta_canonicalizada', models.TextField(blank=True, default='', help_text='>=100 chars quando estado=RESPONDIDA + anti-PII.')),
                ('resposta_hash', models.CharField(blank=True, default='', max_length=80)),
                ('decisao', models.CharField(blank=True, choices=[('PROCEDENTE_RECALL', 'Procedente — recall do certificado (saga ADR-0045)'), ('PROCEDENTE_ERRATA', 'Procedente — errata pontual (saga ADR-0045)'), ('IMPROCEDENTE', 'Improcedente (justificativa tecnica)')], default='', help_text='Preenchida em RESPONDIDA (CHECK constraint na migration).', max_length=25)),
                ('aberta_em', models.DateTimeField()),
                ('prazo_resposta_dia_util', models.PositiveSmallIntegerField(default=15, help_text='Default 15 dias uteis (AC-CAL-018-3).')),
                ('respondida_em', models.DateTimeField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('calibracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamacoes', to='calibracao.calibracao')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamacoes_calibracao', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Reclamacao Calibracao',
                'verbose_name_plural': 'Reclamacoes Calibracao',
                'db_table': 'reclamacao_calibracao',
                'ordering': ['-aberta_em'],
                'indexes': [models.Index(fields=['tenant', 'calibracao'], name='reclcal_tenant_cal_idx'), models.Index(fields=['tenant', 'estado'], name='reclcal_tenant_estado_idx')],
            },
        ),
        migrations.RunSQL(sql=RLS_TRIGGERS_FORWARD, reverse_sql=RLS_TRIGGERS_REVERSE),
    ]
