# Generated by Django 5.2.14 on 2026-05-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0015_perfil_no_evento_san_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventodecalibracao',
            name='escopos_acreditados_vigentes_no_momento',
            field=models.JSONField(default=list, help_text='R7 plan.md — escopos CGCRE vigentes no momento (perfil A). Fail-open lazy `[]` ate modulo metrologia/escopos-cmc Wave A. NIT-DICLA-030 item 8.2.6 — defesa em auditoria CGCRE retroativa.'),
        ),
        migrations.AlterField(
            model_name='eventodecalibracao',
            name='perfil_no_evento',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text="Snapshot perfil tenant no momento. Trigger BEFORE INSERT popula via current_setting('app.perfil_tenant') quando NULL. ADR-0067.", max_length=1, null=True),
        ),
    ]
