# Generated by Django 5.2.14 on 2026-05-30 13:24
#
# ADR-0076 — faixa calibrada declarada (portao de cobertura RBC na configuracao).
# Adiciona 4 colunas decompostas do VO FaixaMedicao + Grandeza (TL-C-02). Nullable,
# sem default destrutivo; tabela ja tem RLS (nao recria policy).
#
# metrologia-classificacao: OQ  (AddField — toca faixa metrologica; INV-CAL-VAL-002)
# replay-fixture: none
# replay-fixture-aceite: colunas nullable NAO consumidas pelo motor de calculo de
#   incerteza/conformidade — populacao comeca na configuracao daqui pra frente; replay
#   metrologico historico (que exercita o motor) nao e afetado por DDL aditivo de campo
#   de portao de cobertura. Determinismo do replay 25a preservado (ADR-0025 cl. 7.11.3).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0016_alter_eventodecalibracao_escopos_acreditados_vigentes_no_momento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibracao',
            name='faixa_calibrada_max',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Limite superior da faixa calibrada declarada (faixa_min < faixa_max). ADR-0076.', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='calibracao',
            name='faixa_calibrada_min',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Limite inferior da faixa calibrada declarada (Decimal). ADR-0076.', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='calibracao',
            name='grandeza_calibrada',
            field=models.CharField(blank=True, default='', help_text='Grandeza declarada na config (vocabulario canonico Grandeza). ADR-0076.', max_length=30),
        ),
        migrations.AddField(
            model_name='calibracao',
            name='unidade_calibrada',
            field=models.CharField(blank=True, default='', help_text='Unidade da faixa calibrada declarada (whitelist FaixaMedicao). ADR-0076.', max_length=10),
        ),
    ]
