# Generated by Django 5.2.14 on 2026-05-31 18:14
# metrologia-classificacao: OQ
# replay-fixture: none
# replay-fixture-aceite: migration aditiva ADR-0077 — 7 colunas probatorias
#   NULL-aveis em orcamento_por_ponto (tabela vazia; trigger WORM admite
#   INSERT). NAO altera calculo existente; suite M4 chave reverde identica.
#   Replay por ponto entra na fatia testes/drill/replay dedicada (cl. 7.11).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0017_calibracao_faixa_calibrada_max_and_more'),
        ('tenant', '0010_remove_tenantperfilhistorico_tph_tenant_recente_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoporponto',
            name='grau_liberdade_efetivo_no_ponto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='nu_eff Welch-Satterthwaite no ponto (999999 = infinito pratico).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orcamentoporponto',
            name='lei_escalonamento_aplicada',
            field=models.CharField(blank=True, choices=[('CONSTANTE', 'Constante (valor absoluto fixo na faixa)'), ('PROPORCIONAL', 'Proporcional (b*X)'), ('LINEAR_AFIM', 'Linear afim (a + b*X)')], default='', help_text='Lei de escalonamento Tipo B aplicada (1a fatia: CONSTANTE).', max_length=20),
        ),
        migrations.AddField(
            model_name='orcamentoporponto',
            name='metodo_tipo_a_ponto',
            field=models.CharField(blank=True, choices=[('SX_PROPRIO', 's_x das repeticoes do proprio ponto (n>=6)'), ('S_POOLED', 'Desvio-padrao combinado (pooled) do metodo (2<=n<6)'), ('AUSENTE', 'Sem Tipo A no ponto (n<2) — so Tipo B')], default='', help_text='Como o Tipo A foi obtido no ponto (Q-RBC-2).', max_length=20),
        ),
        migrations.AddField(
            model_name='orcamentoporponto',
            name='n_repeticoes_ponto',
            field=models.PositiveIntegerField(blank=True, help_text='Numero de repeticoes do ponto (regra n>=6 por ponto).', null=True),
        ),
        migrations.AddField(
            model_name='orcamentoporponto',
            name='nivel_confianca_no_ponto',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cobertura nominal no ponto (ex.: 0.9545).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='orcamentoporponto',
            name='replay_determinismo_hash_no_ponto',
            field=models.CharField(blank=True, default='', help_text='HashVersionado v<NN>$<base64> do calculo do ponto (ADR-0025 cl. 7.11).', max_length=255),
        ),
        migrations.AddField(
            model_name='orcamentoporponto',
            name='tipo_a_insuficiente',
            field=models.BooleanField(default=False, help_text='Ressalva B/C/D: ponto com 2<=n<6 sem s_pooled (nao bloqueia).'),
        ),
        migrations.AddIndex(
            model_name='orcamentoporponto',
            index=models.Index(fields=['tenant', 'orcamento_incerteza'], name='orcponto_tenant_orc_idx'),
        ),
    ]
