# Generated by Django 5.2.14 on 2026-05-31 19:39
# metrologia-classificacao: OQ
# replay-fixture: none
# replay-fixture-aceite: migration aditiva ADR-0077 — colunas NULL-aveis novas
#   (cadeia_pontos_hash em orcamento_incerteza; s_tipo_a_no_ponto em
#   orcamento_por_ponto). NAO altera nenhum calculo existente: tabelas
#   vazias no momento, suite M4 chave reverde byte-identica (748/748). O
#   replay determinístico por ponto entra na fatia testes/drill/replay
#   dedicada (ADR-0025 cl. 7.11 — fixtures por ponto), nao nesta DDL.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0018_orcamentoporponto_grau_liberdade_efetivo_no_ponto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoincerteza',
            name='cadeia_pontos_hash',
            field=models.CharField(blank=True, default='', help_text='HashVersionado de fecho dos pontos (ADR-0077). Vazio no path flat.', max_length=255),
        ),
        migrations.AddField(
            model_name='orcamentoporponto',
            name='s_tipo_a_no_ponto',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Desvio-padrao Tipo A aplicado no ponto (s_x ou s_pool). Completude probatoria CGCRE no caso S_POOLED. None quando AUSENTE.', max_digits=20, null=True),
        ),
    ]
