# Generated by Django 5.2.14 on 2026-05-18 05:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Slug do perfil (ex: 'admin_tenant'). Bate com UsuarioPerfilTenant.perfil.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        help_text="NULL = perfil global do sistema. UUID = perfil específico de tenant (Wave A+).",
                        null=True,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Perfil de autorização",
                "verbose_name_plural": "Perfis de autorização",
                "db_table": "authz_perfil",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="AuthzDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("usuario_id", models.UUIDField(db_index=True)),
                (
                    "tenant_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="NULL pra decisões pré-tenant (login, listar tenants).",
                        null=True,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=100)),
                (
                    "resource_summary",
                    models.JSONField(
                        default=dict, help_text="Snapshot mínimo do recurso (sem PII cru)."
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        help_text="Finalidade LGPD: 'execucao_contrato', 'cumprimento_obrigacao_legal', etc.",
                        max_length=50,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("allowed", "allowed"), ("denied", "denied")], max_length=20
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="String curta estável (ex: 'rbac_denied', 'feature_disabled').",
                        max_length=200,
                    ),
                ),
                (
                    "perfis_aplicados",
                    models.JSONField(
                        default=list,
                        help_text="Lista de codigos de perfil que pesaram (['tecnico']).",
                    ),
                ),
                (
                    "escopo_avaliado",
                    models.JSONField(
                        default=dict, help_text="JSON com atributos ABAC consultados."
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 do IP do request (sem armazenar IP cru — LGPD).",
                        max_length=64,
                    ),
                ),
                (
                    "hash_anterior",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 da linha anterior na cadeia. Vazio = primeira linha.",
                        max_length=64,
                    ),
                ),
                (
                    "hash_atual",
                    models.CharField(
                        help_text="SHA-256(hash_anterior || payload_canonico_desta_linha).",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "verbose_name": "Decisão de autorização (audit)",
                "verbose_name_plural": "Decisões de autorização (audit)",
                "db_table": "authz_decisions",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["tenant_id", "timestamp"], name="ix_authzdec_tenant_ts"),
                    models.Index(fields=["usuario_id", "timestamp"], name="ix_authzdec_user_ts"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PerfilAcao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        help_text="Slug 'modulo.acao' (ex: 'os.criar').", max_length=100
                    ),
                ),
                (
                    "pode_executar",
                    models.BooleanField(
                        default=True,
                        help_text="False = bloqueio explícito que sobrepõe herança (raro). True = permite. Ausência da linha = sem permissão (deny-by-default).",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acoes_permitidas",
                        to="authz.perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permissão por perfil",
                "verbose_name_plural": "Permissões por perfil",
                "db_table": "authz_perfil_acao",
                "indexes": [models.Index(fields=["acao"], name="ix_authz_acao")],
                "constraints": [
                    models.UniqueConstraint(fields=("perfil", "acao"), name="uq_authz_perfil_acao")
                ],
            },
        ),
    ]
