# Generated by Django 5.2.14 on 2026-05-30 18:14
#
# T-PROC-020/021 — M7 metrologia/procedimentos-calibracao schema inicial.
# procedimento_calibracao (raiz, colunas tipadas). UNIQUE documental
# (tenant,codigo,versao) + UNIQUE parcial nao-overlap 1 vigente por chave natural
# (tenant,codigo,grandeza,faixa_min,faixa_max) WHERE PUBLICADO/vigente (INV-PROC-008).
# Indice parcial resolucao (vigente_em).
#
# RLS policies = migration-irma 0002_rls_policies (ADR-0002 §6 pattern v2).
# Triggers WORM Padrao B (block-delete + campo tecnico PUBLICADO imutavel) =
# 0003_triggers_worm. GRANT app_user = 0004_grants_app_user.
# metrology-affecting: procedimento_calibracao metodo_norma/faixa tocam decisao RBC (ADR-0025 cl. 7.11)
#
# rls-policy: external 0002_rls_policies

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0010_remove_tenantperfilhistorico_tph_tenant_recente_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimentoCalibracao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Identidade do documento controlado (cl. 8.3), ex. PC-MASSA-001.', max_length=60)),
                ('titulo', models.CharField(help_text='Título do procedimento.', max_length=200)),
                ('grandeza', models.CharField(choices=[('massa', 'massa'), ('temperatura', 'temperatura'), ('pressao', 'pressao'), ('volume', 'volume'), ('comprimento', 'comprimento'), ('eletrica_tensao', 'eletrica_tensao'), ('eletrica_corrente', 'eletrica_corrente'), ('eletrica_resistencia', 'eletrica_resistencia'), ('eletrica_potencia', 'eletrica_potencia'), ('tempo', 'tempo'), ('frequencia', 'frequencia'), ('forca', 'forca'), ('torque', 'torque'), ('dureza', 'dureza'), ('umidade', 'umidade'), ('ph', 'ph'), ('densidade', 'densidade'), ('vazao', 'vazao'), ('velocidade', 'velocidade'), ('aceleracao', 'aceleracao')], help_text='UMA grandeza por código (D-PROC-2). Índice de resolução.', max_length=30)),
                ('faixa_min', models.DecimalField(decimal_places=12, help_text='Limite inferior da faixa (Decimal).', max_digits=30)),
                ('faixa_max', models.DecimalField(decimal_places=12, help_text='Limite superior (faixa_min < faixa_max).', max_digits=30)),
                ('unidade', models.CharField(help_text='Unidade SI da faixa (whitelist VO).', max_length=20)),
                ('metodo_norma', models.CharField(help_text='Método/norma de referência (NIT-DICLA / ABNT / OIML / ISO).', max_length=120)),
                ('tipo_metodo', models.CharField(choices=[('NORMALIZADO', 'NORMALIZADO'), ('NAO_NORMALIZADO', 'NAO_NORMALIZADO'), ('MODIFICADO', 'MODIFICADO')], default='NORMALIZADO', help_text='NORMALIZADO / NAO_NORMALIZADO / MODIFICADO (cl. 7.2.2 — INV-PROC-010).', max_length=20)),
                ('registro_validacao_id', models.UUIDField(blank=True, help_text='Evidência de validação de método não-normalizado (cl. 7.2.2; NULL=fail-open lazy).', null=True)),
                ('numero_revisao', models.CharField(blank=True, default='', help_text='Ex. "Rev. 03" — cl. 8.3.2c (distinto de versao).', max_length=40)),
                ('aprovado_em', models.DateTimeField(blank=True, help_text='Data do ato de aprovação (cl. 8.3.1; ≠ vigência).', null=True)),
                ('aprovado_por_id', models.UUIDField(blank=True, help_text='Quem aprovou (RT/gestor).', null=True)),
                ('aprovado_por_nome_snapshot', models.CharField(blank=True, default='', max_length=160)),
                ('anexo_pdf_storage_key', models.CharField(blank=True, default='', help_text='Chave opaca do PDF (storage).', max_length=200)),
                ('anexo_pdf_sha256', models.CharField(blank=True, default='', help_text='sha256 do binário, recalculado server-side (INV-PROC-007).', max_length=80)),
                ('versao', models.IntegerField(default=1, help_text='Revisão preserva versão anterior (AC-CAL-016-3).')),
                ('vigente_a_partir', models.DateTimeField(help_text='Início da vigência desta versão.')),
                ('estado', models.CharField(choices=[('RASCUNHO', 'RASCUNHO'), ('PUBLICADO', 'PUBLICADO'), ('REVOGADO', 'REVOGADO')], default='RASCUNHO', help_text='RASCUNHO (editável) → PUBLICADO (WORM) → REVOGADO (terminal).', max_length=20)),
                ('revision', models.IntegerField(default=0, help_text='Optimistic lock CAS. UPDATE WHERE revision=:esperada.')),
                ('vigencia_inicio', models.DateTimeField(help_text='Vigência canônica ADR-0030.')),
                ('vigencia_fim', models.DateTimeField(blank=True, help_text='NULL = aberta. One-shot ao ser superada por nova versão.', null=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, help_text='Cadeia forense.')),
                ('revogado_em', models.DateTimeField(blank=True, help_text='Soft-delete B (ADR-0031). NULL = vigente.', null=True)),
                ('motivo_revogacao', models.TextField(blank=True, default='', help_text='>=10 chars quando revogado (ADR-0030).')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimentos_calibracao', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Procedimento de Calibração',
                'verbose_name_plural': 'Procedimentos de Calibração',
                'db_table': 'procedimento_calibracao',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(condition=models.Q(('estado', 'PUBLICADO'), ('revogado_em__isnull', True)), fields=['tenant', 'grandeza', 'vigencia_fim'], name='proc_resolucao_idx'), models.Index(fields=['tenant', 'codigo'], name='proc_tenant_codigo_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'codigo', 'versao'), name='uq_proc_chave_documental'), models.UniqueConstraint(condition=models.Q(('estado', 'PUBLICADO'), ('revogado_em__isnull', True), ('vigencia_fim__isnull', True)), fields=('tenant', 'codigo', 'grandeza', 'faixa_min', 'faixa_max'), name='uq_proc_uma_vigente')],
            },
        ),
    ]
