# Generated by Django 5.2.14 on 2026-05-28 22:37
#
# T-PAD-010..014 — M5 metrologia/padroes schema inicial (6 tabelas).
# CreateModel das 6 entidades do dominio (PadraoMetrologico raiz + RecalExterno
# + VerificacaoIntermediaria + IntercomparacaoPT + AnaliseCartaControle +
# VinculoAuxiliar) + UNIQUE(tenant, numero_serie) (INV-PAD-001).
#
# RLS policies = migration-irma 0002_rls_policies (ADR-0002 §6 pattern v2).
# Triggers WORM + INV-PAD-006 (incertezas so via recal) = 0003_triggers_worm.
# GRANT app_user = 0004_grants_app_user.
#
# rls-policy: external 0002_rls_policies

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0010_remove_tenantperfilhistorico_tph_tenant_recente_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PadraoMetrologico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_serie', models.CharField(help_text='UNIQUE por tenant (INV-PAD-001). Imutavel pos 1o uso.', max_length=120)),
                ('fabricante', models.CharField(max_length=120)),
                ('modelo', models.CharField(max_length=120)),
                ('subtipo', models.CharField(choices=[('PRINCIPAL', 'PRINCIPAL'), ('AUXILIAR_AMBIENTAL', 'AUXILIAR_AMBIENTAL'), ('AUXILIAR_ELETRICO', 'AUXILIAR_ELETRICO'), ('AUXILIAR_TERMOMETRICO', 'AUXILIAR_TERMOMETRICO')], default='PRINCIPAL', help_text='PRINCIPAL vs auxiliar cl. 6.4.5 (C-8).', max_length=30)),
                ('grandezas', models.JSONField(default=list, help_text='Lista de Grandeza (VO) serializada. >=1. Adapter parseia.')),
                ('faixas', models.JSONField(default=list, help_text='Lista de FaixaMedicao (VO) serializada. >=1.')),
                ('incertezas_certificado', models.JSONField(default=list, help_text='Lista de IncertezaExpandida (VO). >=1. So muta via fluxo de recal (INV-PAD-006 — trigger PG exige GUC app.padrao_recal_em_curso).')),
                ('vinculacao', models.CharField(choices=[('BIPM', 'BIPM'), ('INMETRO', 'INMETRO'), ('RBC', 'RBC'), ('INTERNACIONAL', 'INTERNACIONAL')], help_text='Cadeia de rastreabilidade ao SI (cl. 6.5). RBC exige perfil A (INV-PAD-005).', max_length=20)),
                ('classe', models.CharField(choices=[('E1', 'E1'), ('E2', 'E2'), ('F1', 'F1'), ('F2', 'F2'), ('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('OUTRA', 'OUTRA')], max_length=10)),
                ('cert_externo_storage_key', models.CharField(blank=True, default='', help_text='Chave opaca do binario cifrado (KMS por-tenant — C-14). Nunca PII em claro.', max_length=200)),
                ('validade_certificado_rastreabilidade', models.DateField(help_text='So muta via recal (INV-PAD-006).')),
                ('proximo_recal', models.DateField(help_text='So muta via recal (INV-PAD-006).')),
                ('intervalo_recal_meses', models.IntegerField(help_text='Configuravel (C-9 — cl. 6.4.7 + ILAC-G24). NAO cravar valor R111.')),
                ('intervalo_vi_meses', models.IntegerField(help_text='Configuravel (C-9).')),
                ('criterio_intervalo', models.TextField(help_text='Justificativa do intervalo (cl. 6.4.7 — C-9). NAO PII.')),
                ('estado', models.CharField(choices=[('EM_USO', 'EM_USO'), ('EM_RECAL_EXTERNO', 'EM_RECAL_EXTERNO'), ('RECAL_RETORNADO_PENDENTE_APROVACAO', 'RECAL_RETORNADO_PENDENTE_APROVACAO'), ('INTERCOMPARACAO_PT_EM_CURSO', 'INTERCOMPARACAO_PT_EM_CURSO'), ('BAIXADO', 'BAIXADO'), ('SUCATEADO', 'SUCATEADO')], default='EM_USO', help_text='Maquina de estados (plan §14). Apenas EM_USO libera uso em calibracao.', max_length=40)),
                ('revision', models.IntegerField(default=0, help_text='Optimistic lock CAS (ADR-0065 paralelo). UPDATE WHERE revision=:esperada.')),
                ('rastreabilidade_origem_revogada', models.BooleanField(default=False, help_text='Flag transversal (C-5 FURO-4). True bloqueia uso INDEPENDENTE do estado (evento externo: lab de origem perdeu acreditacao — paralelo ADR-0045).')),
                ('vigencia_inicio', models.DateTimeField(help_text='Vigencia canonica ADR-0030.')),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, help_text='Cadeia forense.')),
                ('descricao', models.TextField(blank=True, default='', help_text='<=500 chars anti-PII.')),
                ('localizacao_lab', models.CharField(blank=True, default='', help_text='<=200 chars anti-PII (nao logar em claro).', max_length=200)),
                ('revogado_em', models.DateTimeField(blank=True, help_text='Soft-delete B (ADR-0031). NULL = vigente.', null=True)),
                ('motivo_revogacao', models.TextField(blank=True, default='', help_text='>=10 chars quando revogado (ADR-0030).')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='padroes_metrologicos', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Padrao Metrologico',
                'verbose_name_plural': 'Padroes Metrologicos',
                'db_table': 'padrao_metrologico',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='IntercomparacaoPT',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lab_organizador', models.CharField(max_length=200)),
                ('protocolo', models.CharField(max_length=120)),
                ('data_inicio', models.DateTimeField()),
                ('resultado', models.CharField(blank=True, choices=[('APROVADO', 'APROVADO'), ('REJEITADO', 'REJEITADO'), ('SOB_REVISAO', 'SOB_REVISAO')], max_length=20, null=True)),
                ('data_resultado', models.DateTimeField(blank=True, null=True)),
                ('zeta_score', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('relatorio_pt_storage_key', models.CharField(blank=True, default='', max_length=200)),
                ('nao_conformidade_id', models.UUIDField(blank=True, help_text='Ref modulo nao-conformidades (Wave B+).', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pts_padrao', to='tenant.tenant')),
                ('padrao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intercomparacoes_pt', to='padroes.padraometrologico')),
            ],
            options={
                'verbose_name': 'Intercomparacao / PT',
                'verbose_name_plural': 'Intercomparacoes / PT',
                'db_table': 'intercomparacao_pt',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseCartaControle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('regra_violada', models.CharField(choices=[('REGRA_1_FORA_3SIGMA', 'REGRA_1_FORA_3SIGMA'), ('REGRA_2_2DE3_2SIGMA', 'REGRA_2_2DE3_2SIGMA'), ('REGRA_3_4DE5_1SIGMA', 'REGRA_3_4DE5_1SIGMA'), ('REGRA_4_RUN_8', 'REGRA_4_RUN_8'), ('REGRA_5_TENDENCIA_7', 'REGRA_5_TENDENCIA_7')], max_length=30)),
                ('pontos_referenciados_ids', models.JSONField(default=list, help_text='FKs VIs/recais (sem copiar valor).')),
                ('linha_central', models.DecimalField(decimal_places=12, max_digits=30)),
                ('ucl', models.DecimalField(decimal_places=12, max_digits=30)),
                ('lcl', models.DecimalField(decimal_places=12, max_digits=30)),
                ('sigma', models.DecimalField(decimal_places=12, max_digits=30)),
                ('n_pontos', models.IntegerField()),
                ('janela_meses', models.IntegerField()),
                ('versao_motor_shewhart', models.CharField(max_length=50)),
                ('decisao_rt', models.CharField(choices=[('ACEITO_COM_JUSTIFICATIVA', 'ACEITO_COM_JUSTIFICATIVA'), ('RECALIBRAR', 'RECALIBRAR'), ('SUSPENDER_USO', 'SUSPENDER_USO')], max_length=30)),
                ('justificativa_canonicalizada', models.TextField(help_text='ADR-0029 anti-PII.')),
                ('justificativa_hash', models.CharField(max_length=80)),
                ('assinatura_a3_rt_id', models.UUIDField(blank=True, help_text='NULL ate A3 plugar (Wave A).', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_carta_controle', to='tenant.tenant')),
                ('padrao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_carta_controle', to='padroes.padraometrologico')),
            ],
            options={
                'verbose_name': 'Analise de Carta de Controle',
                'verbose_name_plural': 'Analises de Carta de Controle',
                'db_table': 'analise_carta_controle',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RecalExternoPadrao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enviado_em', models.DateTimeField()),
                ('lab_externo', models.CharField(help_text='Nome do lab (sem PII direta).', max_length=200)),
                ('responsavel_envio_id_hash', models.CharField(help_text='HashVersionado v<NN>$<base64> (ADR-0064) — funcionario.', max_length=80)),
                ('status', models.CharField(choices=[('ENVIADO', 'ENVIADO'), ('RETORNADO', 'RETORNADO'), ('EXTRAVIADO_NO_TRANSPORTE', 'EXTRAVIADO_NO_TRANSPORTE'), ('RECUSADO_PELO_LAB', 'RECUSADO_PELO_LAB')], max_length=30)),
                ('numero_protocolo_lab_externo', models.CharField(blank=True, default='', max_length=120)),
                ('retornado_em', models.DateTimeField(blank=True, null=True)),
                ('cert_externo_novo_storage_key', models.CharField(blank=True, default='', max_length=200)),
                ('incertezas_novas', models.JSONField(default=list)),
                ('validade_nova', models.DateField(blank=True, null=True)),
                ('valor_convencional_novo', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('aprovado_rt_em', models.DateTimeField(blank=True, help_text='C-4 — analise critica RT.', null=True)),
                ('aprovado_rt_id_hash', models.CharField(blank=True, default='', help_text='C-4 — RT que aprovou (HashVersionado).', max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('padrao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recais', to='padroes.padraometrologico')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recais_padrao', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Recal Externo de Padrao',
                'verbose_name_plural': 'Recais Externos de Padrao',
                'db_table': 'recal_externo_padrao',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='VerificacaoIntermediaria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_vi', models.DateTimeField()),
                ('executor_id_hash', models.CharField(help_text='HashVersionado (ADR-0064).', max_length=80)),
                ('metodo_canonicalizado', models.TextField(help_text='<=500 chars anti-PII (ADR-0029).')),
                ('metodo_hash', models.CharField(max_length=80)),
                ('resultado', models.CharField(choices=[('APROVADO', 'APROVADO'), ('REPROVADO', 'REPROVADO'), ('INCONCLUSIVO', 'INCONCLUSIVO')], max_length=20)),
                ('desvio_observado', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('acao_corretiva_canonicalizada', models.TextField(blank=True, default='', help_text='>=30 chars se REPROVADO (ADR-0029).')),
                ('acao_corretiva_hash', models.CharField(blank=True, default='', max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('padrao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verificacoes_intermediarias', to='padroes.padraometrologico')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vis_padrao', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Verificacao Intermediaria',
                'verbose_name_plural': 'Verificacoes Intermediarias',
                'db_table': 'verificacao_intermediaria',
                'ordering': ['-data_vi'],
            },
        ),
        migrations.CreateModel(
            name='VinculoAuxiliar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grandeza_influencia', models.JSONField(help_text='Grandeza (VO) que o auxiliar monitora (temp/umidade/pressao).')),
                ('vigencia_inicio', models.DateTimeField()),
                ('revogado_em', models.DateTimeField(blank=True, help_text='ADR-0030. NULL = vigente.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('padrao_auxiliar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_como_auxiliar', to='padroes.padraometrologico')),
                ('padrao_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_como_principal', to='padroes.padraometrologico')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_auxiliar', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Vinculo Auxiliar',
                'verbose_name_plural': 'Vinculos Auxiliares',
                'db_table': 'vinculo_auxiliar',
                'ordering': ['-vigencia_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='padraometrologico',
            index=models.Index(fields=['tenant', 'estado', 'proximo_recal'], name='pad_tenant_est_recal_idx'),
        ),
        migrations.AddIndex(
            model_name='padraometrologico',
            index=models.Index(fields=['tenant', 'subtipo'], name='pad_tenant_subtipo_idx'),
        ),
        migrations.AddConstraint(
            model_name='padraometrologico',
            constraint=models.UniqueConstraint(fields=('tenant', 'numero_serie'), name='uq_padrao_numero_serie_por_tenant'),
        ),
        migrations.AddIndex(
            model_name='intercomparacaopt',
            index=models.Index(fields=['tenant', 'padrao', 'data_inicio'], name='pt_tenant_pad_data_idx'),
        ),
        migrations.AddIndex(
            model_name='analisecartacontrole',
            index=models.Index(fields=['tenant', 'padrao', 'criado_em'], name='acc_tenant_pad_cri_idx'),
        ),
        migrations.AddIndex(
            model_name='recalexternopadrao',
            index=models.Index(fields=['tenant', 'padrao', 'status'], name='recal_tenant_pad_st_idx'),
        ),
        migrations.AddIndex(
            model_name='verificacaointermediaria',
            index=models.Index(fields=['tenant', 'padrao', 'data_vi'], name='vi_tenant_pad_data_idx'),
        ),
        migrations.AddIndex(
            model_name='vinculoauxiliar',
            index=models.Index(fields=['tenant', 'padrao_principal', 'revogado_em'], name='vinc_tenant_princ_rev_idx'),
        ),
    ]
