"""Marco 2 stub (2026-05-23) — tabela `certificados` + RLS pattern v2 +
trigger PG `equipamento_imutabilidade_pos_cert` (INV-025 / AC-EQP-002-2 /
P-EQP-A3 / T-EQP-013 trigger parte).

Quando Wave A construir modulo completo (emissao A3, PDF, RBC), expande
esta tabela e adiciona colunas — nao destrutivo.

Trigger PG: BEFORE UPDATE em `equipamentos` consulta esta tabela. Se ha
cert vigente (status='emitido' AND revogado_em IS NULL) referenciando o
equipamento, mutacao em (tag, numero_serie, fabricante) bloqueia com
texto canonico (Tn) — chave referenciada em
`docs/conformidade/equipamentos/textos-rejeicao-422.md`.

# tests-coverage: tests/test_certificados_inv_025_t_eqp_013_trigger.py
"""

# Generated by Django 5.2.14 on 2026-05-22 01:57

import uuid

import django.db.models.deletion
from django.db import migrations, models

RLS_E_TRIGGER_FORWARD = """
-- =============================================================
-- RLS pattern v2 (ADR-0002 sec.6)
-- =============================================================
ALTER TABLE certificados ENABLE ROW LEVEL SECURITY;
ALTER TABLE certificados FORCE ROW LEVEL SECURITY;

CREATE POLICY certificados_tenant_isolation_select ON certificados
    FOR SELECT
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY certificados_tenant_isolation_update ON certificados
    FOR UPDATE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')))
    WITH CHECK (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY certificados_tenant_isolation_delete ON certificados
    FOR DELETE
    USING (tenant_id::text = ANY(string_to_array(current_setting('app.tenant_ids'), ',')));

CREATE POLICY certificados_tenant_isolation_insert ON certificados
    FOR INSERT
    WITH CHECK (tenant_id = current_setting('app.active_tenant_id')::uuid);

-- =============================================================
-- INV-025 (T-EQP-013 trigger PG) - imutabilidade pos-cert.
-- Em UPDATE de equipamentos, se existir cert vigente, bloqueia
-- mutacao em (tag, numero_serie, fabricante).
-- =============================================================
CREATE OR REPLACE FUNCTION equipamento_imutabilidade_pos_cert_check()
RETURNS TRIGGER LANGUAGE plpgsql AS $body$
DECLARE
    v_tem_cert boolean;
BEGIN
    -- Sai cedo se nenhum dos campos criticos mudou.
    IF NEW.tag IS NOT DISTINCT FROM OLD.tag
       AND NEW.numero_serie IS NOT DISTINCT FROM OLD.numero_serie
       AND NEW.fabricante IS NOT DISTINCT FROM OLD.fabricante THEN
        RETURN NEW;
    END IF;

    -- Soft-delete nao deve disparar (equipamento sendo eliminado).
    IF NEW.deletado_em IS NOT NULL AND OLD.deletado_em IS NULL THEN
        RETURN NEW;
    END IF;

    -- Consulta cert vigente sem RLS (SECURITY DEFINER seria custoso
    -- aqui — este trigger roda no contexto da transacao do caller,
    -- que ja teve set app.active_tenant_id pelo middleware).
    SELECT EXISTS(
        SELECT 1 FROM certificados
        WHERE equipamento_id = OLD.id
          AND status = 'emitido'
          AND revogado_em IS NULL
    ) INTO v_tem_cert;

    IF v_tem_cert THEN
        IF NEW.tag IS DISTINCT FROM OLD.tag THEN
            RAISE EXCEPTION
                'INV-025 T1: TAG operacional nao pode ser alterada porque '
                'ja existe certificado emitido (ISO/IEC 17025 cl. 8.4). '
                'Crie nova versao via EquipamentoVersao ou registre NC.';
        END IF;
        IF NEW.numero_serie IS DISTINCT FROM OLD.numero_serie THEN
            RAISE EXCEPTION
                'INV-025 T2: numero de serie nao pode ser alterado porque '
                'ja existe certificado emitido (ISO/IEC 17025 cl. 8.4). '
                'Registre como nao conformidade no fluxo do laboratorio.';
        END IF;
        IF NEW.fabricante IS DISTINCT FROM OLD.fabricante THEN
            RAISE EXCEPTION
                'INV-025 T3: fabricante nao pode ser alterado porque '
                'ja existe certificado emitido (ISO/IEC 17025 cl. 8.4 + '
                'NIT-DICLA-030). Registre como nao conformidade.';
        END IF;
    END IF;

    RETURN NEW;
END;
$body$;

CREATE TRIGGER equipamento_imutabilidade_pos_cert_trg
    BEFORE UPDATE ON equipamentos
    FOR EACH ROW
    EXECUTE FUNCTION equipamento_imutabilidade_pos_cert_check();
"""

RLS_E_TRIGGER_REVERSE = """
DROP TRIGGER IF EXISTS equipamento_imutabilidade_pos_cert_trg ON equipamentos;
DROP FUNCTION IF EXISTS equipamento_imutabilidade_pos_cert_check();
DROP POLICY IF EXISTS certificados_tenant_isolation_insert ON certificados;
DROP POLICY IF EXISTS certificados_tenant_isolation_delete ON certificados;
DROP POLICY IF EXISTS certificados_tenant_isolation_update ON certificados;
DROP POLICY IF EXISTS certificados_tenant_isolation_select ON certificados;
ALTER TABLE certificados DISABLE ROW LEVEL SECURITY;
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipamentos', '0008_aprovacaopendenteequipamentoversao'),
        ('tenant', '0002_tenant_bloqueio_automatico_inadimplencia_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho (sem efeito legal)'), ('emitido', 'Emitido (vigente — bloqueia mutacao INV-025)'), ('revogado', 'Revogado (substituido ou erro)')], default='rascunho', max_length=20)),
                ('emitido_em', models.DateTimeField(blank=True, help_text='Quando o cert foi assinado (A3 Wave A). NULL enquanto rascunho. Marca a transicao para `emitido`.', null=True)),
                ('revogado_em', models.DateTimeField(blank=True, help_text='Quando o cert foi invalidado. INV-025 deixa de bloquear mutacao no equipamento quando todos os certs ficam revogados.', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to='equipamentos.equipamento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Certificado (stub Marco 2)',
                'verbose_name_plural': 'Certificados (stub Marco 2)',
                'db_table': 'certificados',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['equipamento', 'status', 'revogado_em'], name='ix_cert_eq_status_rev'), models.Index(fields=['tenant', 'status'], name='certificado_tenant__0e5016_idx')],
            },
        ),
        migrations.RunSQL(sql=RLS_E_TRIGGER_FORWARD, reverse_sql=RLS_E_TRIGGER_REVERSE),
    ]
