"""M8 `metrologia/certificados` — emissão metrológica (T-CER-020/021, ADR-0078).

ESTRITAMENTE ADITIVA sobre o stub Marco 2 (`certificados/0001`):
- `Certificado`: + colunas da emissão (numeração, perfil, faixa, snapshots,
  reconciliacao_hash, CAS revision) + choice `substituida` (reemissão US-CER-004,
  AlterField que só ESTENDE — o trigger INV-025 só filtra `'emitido'`, intocado).
- 2 tabelas novas WORM: `ponto_reconciliado` (1:N) + `analise_reconciliacao_cert`.

NÃO renomeia/dropa `db_table='certificados'`, `app_label='certificados'`, nem o
literal `'emitido'` — preserva o contrato cross-app do trigger
`equipamento_imutabilidade_pos_cert` (INV-025).

# metrologia-classificacao: IQ
# replay-fixture: none
# rls-policy: external 0003_rls_reconciliacao
"""

# Generated by Django 5.2.14 on 2026-06-01 00:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
        ('equipamentos', '0027_seed_authz_versionar'),
        ('tenant', '0010_remove_tenantperfilhistorico_tph_tenant_recente_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseReconciliacaoCert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calibracao_id', models.UUIDField(db_index=True)),
                ('ponto_calibracao', models.DecimalField(decimal_places=12, max_digits=30)),
                ('decisao_rt', models.CharField(choices=[('EXCLUIR_PONTO', 'EXCLUIR_PONTO'), ('EMITIR_NAO_RBC_NO_PONTO', 'EMITIR_NAO_RBC_NO_PONTO'), ('ABORTAR', 'ABORTAR')], max_length=30)),
                ('categoria_motivo', models.CharField(choices=[('PADRAO_FORA_VALIDADE', 'PADRAO_FORA_VALIDADE'), ('FALHA_REPETIBILIDADE', 'FALHA_REPETIBILIDADE'), ('U_MAIOR_QUE_CMC_BUG', 'U_MAIOR_QUE_CMC_BUG'), ('PONTO_FORA_FAIXA_DECLARADA', 'PONTO_FORA_FAIXA_DECLARADA'), ('CONDICAO_AMBIENTAL_NC', 'CONDICAO_AMBIENTAL_NC'), ('OUTRO', 'OUTRO')], max_length=30)),
                ('justificativa_canonicalizada', models.TextField()),
                ('justificativa_hash', models.CharField(max_length=120)),
                ('ressalva_nao_rbc', models.TextField(blank=True, default='')),
                ('decisor_id_hash', models.CharField(blank=True, default='', max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'verbose_name': 'Análise de reconciliação (certificado)',
                'verbose_name_plural': 'Análises de reconciliação (certificado)',
                'db_table': 'analise_reconciliacao_cert',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PontoReconciliado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ponto_calibracao', models.DecimalField(decimal_places=12, max_digits=30)),
                ('valor_reportado', models.DecimalField(decimal_places=12, max_digits=30)),
                ('u_no_ponto', models.DecimalField(decimal_places=12, help_text='U expandida no ponto (ADR-0077).', max_digits=30)),
                ('k_no_ponto', models.DecimalField(decimal_places=10, max_digits=20)),
                ('nivel_confianca_no_ponto', models.DecimalField(decimal_places=4, max_digits=6)),
                ('grau_liberdade_efetivo_no_ponto', models.DecimalField(decimal_places=6, help_text='nu_eff (999999 = infinito prático).', max_digits=20)),
                ('cmc_no_ponto', models.DecimalField(blank=True, decimal_places=12, help_text='CMC no ponto (NULL = não-RBC no ponto).', max_digits=30, null=True)),
                ('classificacao', models.CharField(choices=[('RBC_OK', 'RBC_OK'), ('FORA_DECLARADA', 'FORA_DECLARADA'), ('SEM_CMC', 'SEM_CMC'), ('U_MENOR_CMC', 'U_MENOR_CMC'), ('EXCLUIDO', 'EXCLUIDO')], max_length=20)),
                ('u_igual_cmc_suspeita', models.BooleanField(default=False)),
                ('incluido_no_certificado', models.BooleanField(default=True)),
                ('ressalva_nao_rbc', models.TextField(blank=True, default='', help_text='Obrigatória quando EMITIR_NAO_RBC_NO_PONTO (cl. 8.1.3 / C-03).')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Ponto reconciliado',
                'verbose_name_plural': 'Pontos reconciliados',
                'db_table': 'ponto_reconciliado',
                'ordering': ['ponto_calibracao'],
            },
        ),
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Certificado', 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AddField(
            model_name='certificado',
            name='calibracao_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Calibração APROVADA de origem (M4). UUIDField evita FK cross-app.', null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='correlation_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Cadeia forense.'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='faixa_certificado_max',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Maior ponto VÁLIDO (metadado; pontos discretos = verdade).', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='faixa_certificado_min',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Menor ponto VÁLIDO (metadado — INV-CER-RECONCILIA-003).', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='numero_certificado',
            field=models.CharField(blank=True, default='', help_text='VO NumeroCertificado visível <SLUG>-<YYYY>-<NNNNNN> (sem buracos).', max_length=40),
        ),
        migrations.AddField(
            model_name='certificado',
            name='numero_interno',
            field=models.BigIntegerField(blank=True, help_text='Sequence PG `certificado_numero_seq` (buracos OK — INV-CER-NUM-002).', null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='perfil_emissor_no_momento',
            field=models.CharField(blank=True, help_text='Perfil regulatório do tenant na emissão (CHAR(1) — ADR-0067 / INV-CER-SNAPSHOT-PERFIL-001). Preenchido server-side, imutável pós-emissão.', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='reconciliacao_hash',
            field=models.CharField(blank=True, default='', help_text='Fecho WORM da tabela ponto-a-ponto (v<NN>$<base64> — T-CER-011).', max_length=120),
        ),
        migrations.AddField(
            model_name='certificado',
            name='regra_decisao_snapshot',
            field=models.JSONField(blank=True, help_text='Regra de decisão congelada (cl. 7.8.6 / ADR-0024 — NC-04).', null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='revision',
            field=models.IntegerField(default=0, help_text='Optimistic lock CAS (UPDATE WHERE revision=:esperada).'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='snapshot_equipamento_json',
            field=models.JSONField(blank=True, default=dict, help_text='Equipamento congelado na emissão (paridade pós-baixa — US-CER-013).'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='snapshot_padroes_usados_json',
            field=models.JSONField(blank=True, default=list, help_text='Padrões usados + vigência congelada por padrão (NC-07 / cl. 6.5).'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='tipo_acreditacao',
            field=models.CharField(blank=True, choices=[('RBC', 'RBC'), ('NAO_RBC', 'NAO_RBC')], help_text='RBC (perfil A, pontos cobertos) / NAO_RBC (cl. 8.1.3 / ADR-0075).', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='versao',
            field=models.IntegerField(default=1, help_text='Reemissão cria v(N+1); v(N)→SUBSTITUIDA (US-CER-004).'),
        ),
        migrations.AddField(
            model_name='certificado',
            name='versao_anterior_id',
            field=models.UUIDField(blank=True, help_text='Link p/ v(N) na reemissão. NULL em v1.', null=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='emitido_em',
            field=models.DateTimeField(blank=True, help_text='Emissão metrológica (números definitivos + snapshot). A entrega normativa cl. 7.8 (RBC) é na assinatura A3 (Wave A).', null=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho (sem efeito legal)'), ('emitido', 'Emitido (vigente — bloqueia mutacao INV-025)'), ('substituida', 'Substituída (reemissão versionada US-CER-004)'), ('revogado', 'Revogado (substituido ou erro)')], default='rascunho', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.UniqueConstraint(condition=models.Q(('calibracao_id__isnull', False)), fields=('tenant', 'calibracao_id', 'versao'), name='uq_cert_calibracao_versao'),
        ),
        migrations.AddField(
            model_name='analisereconciliacaocert',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises_reconciliacao_cert', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='pontoreconciliado',
            name='certificado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pontos_reconciliados', to='certificados.certificado'),
        ),
        migrations.AddField(
            model_name='pontoreconciliado',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pontos_reconciliados', to='tenant.tenant'),
        ),
        migrations.AddIndex(
            model_name='analisereconciliacaocert',
            index=models.Index(fields=['tenant', 'calibracao_id'], name='ix_analise_recon_calib'),
        ),
        migrations.AddConstraint(
            model_name='analisereconciliacaocert',
            constraint=models.UniqueConstraint(fields=('tenant', 'calibracao_id', 'ponto_calibracao'), name='uq_analise_recon_calibracao_ponto'),
        ),
        migrations.AddIndex(
            model_name='pontoreconciliado',
            index=models.Index(fields=['certificado', 'ponto_calibracao'], name='ix_ponto_recon_cert'),
        ),
        migrations.AddConstraint(
            model_name='pontoreconciliado',
            constraint=models.UniqueConstraint(fields=('tenant', 'certificado', 'ponto_calibracao'), name='uq_ponto_recon_cert_ponto'),
        ),
    ]
